#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    
    #line 6 "..\..\Areas\Admin\Views\VisitStat\_List_Data.cshtml"
    using System.Web.Mvc;
    
    #line default
    #line hidden
    
    #line 7 "..\..\Areas\Admin\Views\VisitStat\_List_Data.cshtml"
    using System.Web.Mvc.Ajax;
    
    #line default
    #line hidden
    
    #line 8 "..\..\Areas\Admin\Views\VisitStat\_List_Data.cshtml"
    using System.Web.Mvc.Html;
    
    #line default
    #line hidden
    
    #line 9 "..\..\Areas\Admin\Views\VisitStat\_List_Data.cshtml"
    using System.Web.Routing;
    
    #line default
    #line hidden
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    
    #line 2 "..\..\Areas\Admin\Views\VisitStat\_List_Data.cshtml"
    using NewLife;
    
    #line default
    #line hidden
    using NewLife.Cube;
    using NewLife.Reflection;
    
    #line 3 "..\..\Areas\Admin\Views\VisitStat\_List_Data.cshtml"
    using NewLife.Web;
    
    #line default
    #line hidden
    
    #line 4 "..\..\Areas\Admin\Views\VisitStat\_List_Data.cshtml"
    using XCode;
    
    #line default
    #line hidden
    
    #line 5 "..\..\Areas\Admin\Views\VisitStat\_List_Data.cshtml"
    using XCode.Configuration;
    
    #line default
    #line hidden
    using XCode.Membership;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Areas/Admin/Views/VisitStat/_List_Data.cshtml")]
    public partial class _Areas_Admin_Views_VisitStat__List_Data_cshtml : System.Web.Mvc.WebViewPage<IList<XCode.Membership.VisitStat>>
    {
        public _Areas_Admin_Views_VisitStat__List_Data_cshtml()
        {
        }
        public override void Execute()
        {
            
            #line 10 "..\..\Areas\Admin\Views\VisitStat\_List_Data.cshtml"
  
    var fact = ViewBag.Factory as IEntityOperate;
    var page = ViewBag.Page as Pager;
    var fields = ViewBag.Fields as IList<FieldItem>;
    var set = ViewBag.PageSetting as PageSetting;

    var level = (XCode.Statistics.StatLevels)page["Level"].ToInt();

            
            #line default
            #line hidden
WriteLiteral("\r\n<div");

WriteLiteral(" class=\"kt-widget4\"");

WriteLiteral(" style=\"overflow-x:auto;\"");

WriteLiteral(">\r\n    <table");

WriteLiteral(" class=\"table table-striped table-bordered table-hover table-checkable kt-datatab" +
"le__table\"");

WriteLiteral(">\r\n        <thead>\r\n            <tr");

WriteLiteral(" class=\"kt-datatable__row\"");

WriteLiteral(">\r\n");

            
            #line 22 "..\..\Areas\Admin\Views\VisitStat\_List_Data.cshtml"
                
            
            #line default
            #line hidden
            
            #line 22 "..\..\Areas\Admin\Views\VisitStat\_List_Data.cshtml"
                 if (set.EnableSelect)
                {

            
            #line default
            #line hidden
WriteLiteral("                    <th");

WriteLiteral(" class=\"kt-datatable__cell--center kt-datatable__cell kt-datatable__cell--check\"");

WriteLiteral(" style=\"width:20px;\"");

WriteLiteral(">\r\n                        <lable");

WriteLiteral(" class=\"kt-checkbox kt-checkbox--single kt-checkbox--all kt-checkbox--solid\"");

WriteLiteral(">\r\n                            <input");

WriteLiteral(" type=\"checkbox\"");

WriteLiteral(" id=\"chkAll\"");

WriteLiteral(" title=\"全选\"");

WriteLiteral(" />\r\n                            <span></span>\r\n                        </lable>\r" +
"\n                    </th>\r\n");

            
            #line 30 "..\..\Areas\Admin\Views\VisitStat\_List_Data.cshtml"
                }

            
            #line default
            #line hidden
WriteLiteral("                <th");

WriteLiteral(" class=\"text-center hidden-md hidden-sm hidden-xs\"");

WriteLiteral("><a");

WriteAttribute("href", Tuple.Create(" href=\"", 1290), Tuple.Create("\"", 1329)
            
            #line 31 "..\..\Areas\Admin\Views\VisitStat\_List_Data.cshtml"
, Tuple.Create(Tuple.Create("", 1297), Tuple.Create<System.Object, System.Int32>(Html.Raw(page.GetSortUrl("ID"))
            
            #line default
            #line hidden
, 1297), false)
);

WriteLiteral(">编号</a></th>\r\n                <th");

WriteLiteral(" class=\"text-center\"");

WriteLiteral("><a");

WriteAttribute("href", Tuple.Create(" href=\"", 1386), Tuple.Create("\"", 1427)
            
            #line 32 "..\..\Areas\Admin\Views\VisitStat\_List_Data.cshtml"
, Tuple.Create(Tuple.Create("", 1393), Tuple.Create<System.Object, System.Int32>(Html.Raw(page.GetSortUrl("Time"))
            
            #line default
            #line hidden
, 1393), false)
);

WriteLiteral(">时间</a></th>\r\n                <th");

WriteLiteral(" class=\"text-center\"");

WriteLiteral("><a");

WriteAttribute("href", Tuple.Create(" href=\"", 1484), Tuple.Create("\"", 1525)
            
            #line 33 "..\..\Areas\Admin\Views\VisitStat\_List_Data.cshtml"
, Tuple.Create(Tuple.Create("", 1491), Tuple.Create<System.Object, System.Int32>(Html.Raw(page.GetSortUrl("Page"))
            
            #line default
            #line hidden
, 1491), false)
);

WriteLiteral(">页面</a></th>\r\n                <th");

WriteLiteral(" class=\"text-center\"");

WriteLiteral("><a");

WriteAttribute("href", Tuple.Create(" href=\"", 1582), Tuple.Create("\"", 1624)
            
            #line 34 "..\..\Areas\Admin\Views\VisitStat\_List_Data.cshtml"
, Tuple.Create(Tuple.Create("", 1589), Tuple.Create<System.Object, System.Int32>(Html.Raw(page.GetSortUrl("Title"))
            
            #line default
            #line hidden
, 1589), false)
);

WriteLiteral(">标题</a></th>\r\n                <th");

WriteLiteral(" class=\"text-center\"");

WriteLiteral("><a");

WriteAttribute("href", Tuple.Create(" href=\"", 1681), Tuple.Create("\"", 1723)
            
            #line 35 "..\..\Areas\Admin\Views\VisitStat\_List_Data.cshtml"
, Tuple.Create(Tuple.Create("", 1688), Tuple.Create<System.Object, System.Int32>(Html.Raw(page.GetSortUrl("Times"))
            
            #line default
            #line hidden
, 1688), false)
);

WriteLiteral(">次数</a></th>\r\n                <th");

WriteLiteral(" class=\"text-center\"");

WriteLiteral("><a");

WriteAttribute("href", Tuple.Create(" href=\"", 1780), Tuple.Create("\"", 1822)
            
            #line 36 "..\..\Areas\Admin\Views\VisitStat\_List_Data.cshtml"
, Tuple.Create(Tuple.Create("", 1787), Tuple.Create<System.Object, System.Int32>(Html.Raw(page.GetSortUrl("Users"))
            
            #line default
            #line hidden
, 1787), false)
);

WriteLiteral(">用户</a></th>\r\n                <th");

WriteLiteral(" class=\"text-center\"");

WriteLiteral("><a");

WriteAttribute("href", Tuple.Create(" href=\"", 1879), Tuple.Create("\"", 1919)
            
            #line 37 "..\..\Areas\Admin\Views\VisitStat\_List_Data.cshtml"
, Tuple.Create(Tuple.Create("", 1886), Tuple.Create<System.Object, System.Int32>(Html.Raw(page.GetSortUrl("IPs"))
            
            #line default
            #line hidden
, 1886), false)
);

WriteLiteral(">IP</a></th>\r\n                <th");

WriteLiteral(" class=\"text-center\"");

WriteLiteral("><a");

WriteAttribute("href", Tuple.Create(" href=\"", 1976), Tuple.Create("\"", 2018)
            
            #line 38 "..\..\Areas\Admin\Views\VisitStat\_List_Data.cshtml"
, Tuple.Create(Tuple.Create("", 1983), Tuple.Create<System.Object, System.Int32>(Html.Raw(page.GetSortUrl("Error"))
            
            #line default
            #line hidden
, 1983), false)
);

WriteLiteral(">错误</a></th>\r\n                <th");

WriteLiteral(" class=\"text-center\"");

WriteLiteral("><a");

WriteAttribute("href", Tuple.Create(" href=\"", 2075), Tuple.Create("\"", 2116)
            
            #line 39 "..\..\Areas\Admin\Views\VisitStat\_List_Data.cshtml"
, Tuple.Create(Tuple.Create("", 2082), Tuple.Create<System.Object, System.Int32>(Html.Raw(page.GetSortUrl("Cost"))
            
            #line default
            #line hidden
, 2082), false)
);

WriteLiteral(">平均耗时</a></th>\r\n                <th");

WriteLiteral(" class=\"text-center\"");

WriteLiteral("><a");

WriteAttribute("href", Tuple.Create(" href=\"", 2175), Tuple.Create("\"", 2219)
            
            #line 40 "..\..\Areas\Admin\Views\VisitStat\_List_Data.cshtml"
, Tuple.Create(Tuple.Create("", 2182), Tuple.Create<System.Object, System.Int32>(Html.Raw(page.GetSortUrl("MaxCost"))
            
            #line default
            #line hidden
, 2182), false)
);

WriteLiteral(">最大耗时</a></th>\r\n                <th");

WriteLiteral(" class=\"text-center\"");

WriteLiteral("><a");

WriteAttribute("href", Tuple.Create(" href=\"", 2278), Tuple.Create("\"", 2325)
            
            #line 41 "..\..\Areas\Admin\Views\VisitStat\_List_Data.cshtml"
, Tuple.Create(Tuple.Create("", 2285), Tuple.Create<System.Object, System.Int32>(Html.Raw(page.GetSortUrl("CreateTime"))
            
            #line default
            #line hidden
, 2285), false)
);

WriteLiteral(">创建时间</a></th>\r\n                <th");

WriteLiteral(" class=\"text-center\"");

WriteLiteral("><a");

WriteAttribute("href", Tuple.Create(" href=\"", 2384), Tuple.Create("\"", 2431)
            
            #line 42 "..\..\Areas\Admin\Views\VisitStat\_List_Data.cshtml"
, Tuple.Create(Tuple.Create("", 2391), Tuple.Create<System.Object, System.Int32>(Html.Raw(page.GetSortUrl("UpdateTime"))
            
            #line default
            #line hidden
, 2391), false)
);

WriteLiteral(">更新时间</a></th>\r\n");

            
            #line 43 "..\..\Areas\Admin\Views\VisitStat\_List_Data.cshtml"
                
            
            #line default
            #line hidden
            
            #line 43 "..\..\Areas\Admin\Views\VisitStat\_List_Data.cshtml"
                 if (this.Has(PermissionFlags.Detail, PermissionFlags.Update, PermissionFlags.Delete))
                {

            
            #line default
            #line hidden
WriteLiteral("                    <th");

WriteLiteral(" class=\"text-center\"");

WriteLiteral(">操作</th>\r\n");

            
            #line 46 "..\..\Areas\Admin\Views\VisitStat\_List_Data.cshtml"
                }

            
            #line default
            #line hidden
WriteLiteral("            </tr>\r\n        </thead>\r\n        <tbody>\r\n");

            
            #line 50 "..\..\Areas\Admin\Views\VisitStat\_List_Data.cshtml"
            
            
            #line default
            #line hidden
            
            #line 50 "..\..\Areas\Admin\Views\VisitStat\_List_Data.cshtml"
             foreach (var entity in Model)
            {
                var st = new VisitStatModel
                {
                    Level = level,
                    Time = entity.Time
                };

            
            #line default
            #line hidden
WriteLiteral("                <tr>\r\n");

            
            #line 58 "..\..\Areas\Admin\Views\VisitStat\_List_Data.cshtml"
                    
            
            #line default
            #line hidden
            
            #line 58 "..\..\Areas\Admin\Views\VisitStat\_List_Data.cshtml"
                     if (set.EnableSelect)
                    {

            
            #line default
            #line hidden
WriteLiteral("                        <td");

WriteLiteral(" class=\"text-center\"");

WriteLiteral(" style=\"width:20px;\"");

WriteLiteral(">\r\n                            <label");

WriteLiteral(" class=\"kt-checkbox kt-checkbox--single kt-checkbox--all kt-checkbox--solid\"");

WriteLiteral(">\r\n                                <input");

WriteLiteral(" type=\"checkbox\"");

WriteLiteral(" name=\"keys\"");

WriteAttribute("value", Tuple.Create(" value=\"", 3254), Tuple.Create("\"", 3272)
            
            #line 62 "..\..\Areas\Admin\Views\VisitStat\_List_Data.cshtml"
, Tuple.Create(Tuple.Create("", 3262), Tuple.Create<System.Object, System.Int32>(entity.ID
            
            #line default
            #line hidden
, 3262), false)
);

WriteLiteral(" />\r\n                                <span></span>\r\n                            <" +
"/label>\r\n                        </td>\r\n");

            
            #line 66 "..\..\Areas\Admin\Views\VisitStat\_List_Data.cshtml"
                    }

            
            #line default
            #line hidden
WriteLiteral("                    <td");

WriteLiteral(" class=\"text-center hidden-md hidden-sm hidden-xs\"");

WriteLiteral(">");

            
            #line 67 "..\..\Areas\Admin\Views\VisitStat\_List_Data.cshtml"
                                                                     Write(entity.ID);

            
            #line default
            #line hidden
WriteLiteral("</td>\r\n                    <td");

WriteLiteral(" class=\"text-right\"");

WriteLiteral(">");

            
            #line 68 "..\..\Areas\Admin\Views\VisitStat\_List_Data.cshtml"
                                      Write(st);

            
            #line default
            #line hidden
WriteLiteral("</td>\r\n                    <td>");

            
            #line 69 "..\..\Areas\Admin\Views\VisitStat\_List_Data.cshtml"
                   Write(entity.Page);

            
            #line default
            #line hidden
WriteLiteral("</td>\r\n                    <td>");

            
            #line 70 "..\..\Areas\Admin\Views\VisitStat\_List_Data.cshtml"
                   Write(entity.Title);

            
            #line default
            #line hidden
WriteLiteral("</td>\r\n                    <td");

WriteLiteral(" class=\"text-right\"");

WriteLiteral(">");

            
            #line 71 "..\..\Areas\Admin\Views\VisitStat\_List_Data.cshtml"
                                      Write(entity.Times.ToString("n0"));

            
            #line default
            #line hidden
WriteLiteral("</td>\r\n                    <td");

WriteLiteral(" class=\"text-right\"");

WriteLiteral(">");

            
            #line 72 "..\..\Areas\Admin\Views\VisitStat\_List_Data.cshtml"
                                      Write(entity.Users.ToString("n0"));

            
            #line default
            #line hidden
WriteLiteral("</td>\r\n                    <td");

WriteLiteral(" class=\"text-right\"");

WriteLiteral(">");

            
            #line 73 "..\..\Areas\Admin\Views\VisitStat\_List_Data.cshtml"
                                      Write(entity.IPs.ToString("n0"));

            
            #line default
            #line hidden
WriteLiteral("</td>\r\n                    <td");

WriteLiteral(" class=\"text-right\"");

WriteLiteral(">");

            
            #line 74 "..\..\Areas\Admin\Views\VisitStat\_List_Data.cshtml"
                                      Write(entity.Error.ToString("n0"));

            
            #line default
            #line hidden
WriteLiteral("</td>\r\n                    <td");

WriteLiteral(" class=\"text-right\"");

WriteLiteral(">");

            
            #line 75 "..\..\Areas\Admin\Views\VisitStat\_List_Data.cshtml"
                                      Write(entity.Cost.ToString("n0"));

            
            #line default
            #line hidden
WriteLiteral(" ms</td>\r\n                    <td");

WriteLiteral(" class=\"text-right\"");

WriteLiteral(">");

            
            #line 76 "..\..\Areas\Admin\Views\VisitStat\_List_Data.cshtml"
                                      Write(entity.MaxCost.ToString("n0"));

            
            #line default
            #line hidden
WriteLiteral(" ms</td>\r\n                    <td>");

            
            #line 77 "..\..\Areas\Admin\Views\VisitStat\_List_Data.cshtml"
                   Write(entity.CreateTime.ToFullString(""));

            
            #line default
            #line hidden
WriteLiteral("</td>\r\n                    <td>");

            
            #line 78 "..\..\Areas\Admin\Views\VisitStat\_List_Data.cshtml"
                   Write(entity.UpdateTime.ToFullString(""));

            
            #line default
            #line hidden
WriteLiteral("</td>\r\n");

            
            #line 79 "..\..\Areas\Admin\Views\VisitStat\_List_Data.cshtml"
                    
            
            #line default
            #line hidden
            
            #line 79 "..\..\Areas\Admin\Views\VisitStat\_List_Data.cshtml"
                     if (this.Has(PermissionFlags.Detail, PermissionFlags.Update, PermissionFlags.Delete))
                    {

            
            #line default
            #line hidden
WriteLiteral("                        <td");

WriteLiteral(" class=\"text-center\"");

WriteLiteral(" style=\"width: 50px;\"");

WriteLiteral(">\r\n");

WriteLiteral("                            ");

            
            #line 82 "..\..\Areas\Admin\Views\VisitStat\_List_Data.cshtml"
                       Write(Html.Partial("_List_Data_Action", (Object)entity));

            
            #line default
            #line hidden
WriteLiteral("\r\n                        </td>\r\n");

            
            #line 84 "..\..\Areas\Admin\Views\VisitStat\_List_Data.cshtml"
                    }

            
            #line default
            #line hidden
WriteLiteral("                </tr>\r\n");

            
            #line 86 "..\..\Areas\Admin\Views\VisitStat\_List_Data.cshtml"
            }

            
            #line default
            #line hidden
WriteLiteral("            ");

            
            #line 87 "..\..\Areas\Admin\Views\VisitStat\_List_Data.cshtml"
             if (page.State != null)
            {
                var entity = page.State as VisitStat;

            
            #line default
            #line hidden
WriteLiteral("                <tr>\r\n");

            
            #line 91 "..\..\Areas\Admin\Views\VisitStat\_List_Data.cshtml"
                    
            
            #line default
            #line hidden
            
            #line 91 "..\..\Areas\Admin\Views\VisitStat\_List_Data.cshtml"
                     if (set.EnableSelect)
                    {

            
            #line default
            #line hidden
WriteLiteral("                        <td></td>\r\n");

            
            #line 94 "..\..\Areas\Admin\Views\VisitStat\_List_Data.cshtml"
                    }

            
            #line default
            #line hidden
WriteLiteral("                    <td");

WriteLiteral(" class=\"text-center hidden-md hidden-sm hidden-xs\"");

WriteLiteral(">总计</td>\r\n                    <td></td>\r\n                    <td></td>\r\n         " +
"           <td></td>\r\n                    <td");

WriteLiteral(" class=\"text-right\"");

WriteLiteral(">");

            
            #line 99 "..\..\Areas\Admin\Views\VisitStat\_List_Data.cshtml"
                                      Write(entity.Times.ToString("n0"));

            
            #line default
            #line hidden
WriteLiteral("</td>\r\n                    <td");

WriteLiteral(" class=\"text-right\"");

WriteLiteral(">");

            
            #line 100 "..\..\Areas\Admin\Views\VisitStat\_List_Data.cshtml"
                                      Write(entity.Users.ToString("n0"));

            
            #line default
            #line hidden
WriteLiteral("</td>\r\n                    <td");

WriteLiteral(" class=\"text-right\"");

WriteLiteral(">");

            
            #line 101 "..\..\Areas\Admin\Views\VisitStat\_List_Data.cshtml"
                                      Write(entity.IPs.ToString("n0"));

            
            #line default
            #line hidden
WriteLiteral("</td>\r\n                    <td");

WriteLiteral(" class=\"text-right\"");

WriteLiteral(">");

            
            #line 102 "..\..\Areas\Admin\Views\VisitStat\_List_Data.cshtml"
                                      Write(entity.Error.ToString("n0"));

            
            #line default
            #line hidden
WriteLiteral("</td>\r\n                    <td");

WriteLiteral(" class=\"text-right\"");

WriteLiteral(">");

            
            #line 103 "..\..\Areas\Admin\Views\VisitStat\_List_Data.cshtml"
                                      Write(entity.Cost.ToString("n0"));

            
            #line default
            #line hidden
WriteLiteral(" ms</td>\r\n                    <td");

WriteLiteral(" class=\"text-right\"");

WriteLiteral(">");

            
            #line 104 "..\..\Areas\Admin\Views\VisitStat\_List_Data.cshtml"
                                      Write(entity.MaxCost.ToString("n0"));

            
            #line default
            #line hidden
WriteLiteral(" ms</td>\r\n                    <td>");

            
            #line 105 "..\..\Areas\Admin\Views\VisitStat\_List_Data.cshtml"
                   Write(entity.CreateTime.ToFullString(""));

            
            #line default
            #line hidden
WriteLiteral("</td>\r\n                    <td>");

            
            #line 106 "..\..\Areas\Admin\Views\VisitStat\_List_Data.cshtml"
                   Write(entity.UpdateTime.ToFullString(""));

            
            #line default
            #line hidden
WriteLiteral("</td>\r\n");

            
            #line 107 "..\..\Areas\Admin\Views\VisitStat\_List_Data.cshtml"
                    
            
            #line default
            #line hidden
            
            #line 107 "..\..\Areas\Admin\Views\VisitStat\_List_Data.cshtml"
                     if (this.Has(PermissionFlags.Detail, PermissionFlags.Update, PermissionFlags.Delete))
                    {

            
            #line default
            #line hidden
WriteLiteral("                        <td></td>\r\n");

            
            #line 110 "..\..\Areas\Admin\Views\VisitStat\_List_Data.cshtml"
                    }

            
            #line default
            #line hidden
WriteLiteral("                </tr>\r\n");

            
            #line 112 "..\..\Areas\Admin\Views\VisitStat\_List_Data.cshtml"
            }

            
            #line default
            #line hidden
WriteLiteral("        </tbody>\r\n    </table>\r\n</div>");

        }
    }
}
#pragma warning restore 1591
