#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using NewLife;
    using NewLife.Cube;
    using NewLife.Reflection;
    using NewLife.Web;
    using XCode;
    
    #line 1 "..\..\Areas\Admin\Views\User\_Form_Action.cshtml"
    using XCode.Configuration;
    
    #line default
    #line hidden
    
    #line 2 "..\..\Areas\Admin\Views\User\_Form_Action.cshtml"
    using XCode.Membership;
    
    #line default
    #line hidden
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Areas/Admin/Views/User/_Form_Action.cshtml")]
    public partial class _Areas_Admin_Views_User__Form_Action_cshtml : System.Web.Mvc.WebViewPage<dynamic>
    {
        public _Areas_Admin_Views_User__Form_Action_cshtml()
        {
        }
        public override void Execute()
        {
            
            #line 3 "..\..\Areas\Admin\Views\User\_Form_Action.cshtml"
  
    var entity = Model as IEntity;
    var isNew = entity.IsNullKey;
    var fields = entity.GetType().AsFactory().AllFields; // 通过实体工厂获取所有字段

    //var hasAttachment = entity.GetType().GetCustomAttributes(typeof(AttachmentAttribute), true).Length > 0;

            
            #line default
            #line hidden
WriteLiteral("\r\n<div");

WriteLiteral(" class=\"kt-portlet__head kt-portlet__head--lg\"");

WriteLiteral(">\r\n    <div");

WriteLiteral(" class=\"kt-portlet__head-label\"");

WriteLiteral(">\r\n        <a");

WriteAttribute("href", Tuple.Create(" href=\"", 425), Tuple.Create("\"", 452)
            
            #line 12 "..\..\Areas\Admin\Views\User\_Form_Action.cshtml"
, Tuple.Create(Tuple.Create("", 432), Tuple.Create<System.Object, System.Int32>(Url.Action("Index")
            
            #line default
            #line hidden
, 432), false)
);

WriteLiteral(" class=\"btn btn-secondary kt-margin-r-10\"");

WriteLiteral(">\r\n            <i");

WriteLiteral(" class=\"la la-arrow-left\"");

WriteLiteral("></i>\r\n            <span");

WriteLiteral(" class=\"kt-hidden-mobile\"");

WriteLiteral(">返 回</span>\r\n        </a>\r\n    </div>\r\n    <div");

WriteLiteral(" class=\"kt-portlet__head-toolbar\"");

WriteLiteral(">\r\n        <div");

WriteLiteral(" class=\"btn-group\"");

WriteLiteral(">\r\n            <button");

WriteLiteral(" type=\"submit\"");

WriteLiteral(" class=\"btn btn-brand\"");

WriteLiteral(">\r\n                <i");

WriteAttribute("class", Tuple.Create(" class=\"", 777), Tuple.Create("\"", 817)
, Tuple.Create(Tuple.Create("", 785), Tuple.Create("la", 785), true)
, Tuple.Create(Tuple.Create(" ", 787), Tuple.Create("la-", 788), true)
            
            #line 20 "..\..\Areas\Admin\Views\User\_Form_Action.cshtml"
, Tuple.Create(Tuple.Create("", 791), Tuple.Create<System.Object, System.Int32>(isNew ? "plus" : "save"
            
            #line default
            #line hidden
, 791), false)
);

WriteLiteral(" style=\"margin-top: -1px;\"");

WriteLiteral("></i>\r\n                <span");

WriteLiteral(" class=\"kt-hidden-mobile\"");

WriteLiteral(">");

            
            #line 21 "..\..\Areas\Admin\Views\User\_Form_Action.cshtml"
                                           Write(isNew ? "新 增" : "保 存");

            
            #line default
            #line hidden
WriteLiteral("</span>\r\n            </button>\r\n        </div>\r\n    </div>\r\n</div>");

        }
    }
}
#pragma warning restore 1591
