#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    
    #line 1 "..\..\Areas\Admin\Views\User\_List_Toolbar_Search_Udf.cshtml"
    using NewLife;
    
    #line default
    #line hidden
    using NewLife.Cube;
    using NewLife.Reflection;
    
    #line 2 "..\..\Areas\Admin\Views\User\_List_Toolbar_Search_Udf.cshtml"
    using NewLife.Web;
    
    #line default
    #line hidden
    
    #line 3 "..\..\Areas\Admin\Views\User\_List_Toolbar_Search_Udf.cshtml"
    using XCode;
    
    #line default
    #line hidden
    using XCode.Membership;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Areas/Admin/Views/User/_List_Toolbar_Search_Udf.cshtml")]
    public partial class _Areas_Admin_Views_User__List_Toolbar_Search_Udf_cshtml : System.Web.Mvc.WebViewPage<dynamic>
    {
        public _Areas_Admin_Views_User__List_Toolbar_Search_Udf_cshtml()
        {
        }
        public override void Execute()
        {
            
            #line 4 "..\..\Areas\Admin\Views\User\_List_Toolbar_Search_Udf.cshtml"
  
    var fact = ViewBag.Factory as IEntityOperate;
    var page = ViewBag.Page as Pager;

            
            #line default
            #line hidden
WriteLiteral("\r\n<div");

WriteLiteral(" class=\"flex flex-shrink-0 align-items-center kt-margin-t-5 kt-margin-b-5 kt-marg" +
"in-r-5 bars kt-hidden\"");

WriteLiteral(">\r\n    <div");

WriteLiteral(" class=\"flex-shrink-0 kt-margin-r-5\"");

WriteLiteral(">\r\n");

WriteLiteral("        ");

            
            #line 10 "..\..\Areas\Admin\Views\User\_List_Toolbar_Search_Udf.cshtml"
   Write(Html.ActionLink("用户链接", "Index", "UserConnect", null, new { @class = "btn btn-success btn-sm" }.ToDictionary()));

            
            #line default
            #line hidden
WriteLiteral("\r\n    </div>\r\n    <div");

WriteLiteral(" class=\"flex-shrink-0 kt-margin-r-5\"");

WriteLiteral(">\r\n");

WriteLiteral("        ");

            
            #line 13 "..\..\Areas\Admin\Views\User\_List_Toolbar_Search_Udf.cshtml"
   Write(Html.ActionLink("用户在线", "Index", "UserOnline", null, new { @class = "btn btn-success btn-sm" }.ToDictionary()));

            
            #line default
            #line hidden
WriteLiteral("\r\n    </div>\r\n    <label");

WriteLiteral(" for=\"RoleID\"");

WriteLiteral(" class=\"flex-shrink-0 kt-margin-r-5\"");

WriteLiteral(">角色</label>\r\n    ");

WriteLiteral("\r\n\r\n</div>\r\n");

        }
    }
}
#pragma warning restore 1591
