#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using NewLife;
    
    #line 1 "..\..\Areas\Admin\Views\User\_Login_Login.cshtml"
    using NewLife.Common;
    
    #line default
    #line hidden
    using NewLife.Cube;
    using NewLife.Reflection;
    using NewLife.Web;
    using XCode;
    using XCode.Membership;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Areas/Admin/Views/User/_Login_Login.cshtml")]
    public partial class _Areas_Admin_Views_User__Login_Login_cshtml : System.Web.Mvc.WebViewPage<dynamic>
    {
        public _Areas_Admin_Views_User__Login_Login_cshtml()
        {
        }
        public override void Execute()
        {
            
            #line 2 "..\..\Areas\Admin\Views\User\_Login_Login.cshtml"
  
    /**/

    var set = NewLife.Cube.Setting.Current;

            
            #line default
            #line hidden
WriteLiteral("\r\n<div");

WriteLiteral(" class=\"kt-login__signin\"");

WriteLiteral(">\r\n    <div");

WriteLiteral(" class=\"kt-login__head\"");

WriteLiteral(">\r\n        <h3");

WriteLiteral(" class=\"kt-login__title\"");

WriteLiteral(">登录</h3>\r\n    </div>\r\n    <div");

WriteLiteral(" class=\"kt-login__form kt-form\"");

WriteLiteral(">\r\n");

            
            #line 12 "..\..\Areas\Admin\Views\User\_Login_Login.cshtml"
        
            
            #line default
            #line hidden
            
            #line 12 "..\..\Areas\Admin\Views\User\_Login_Login.cshtml"
         using (Html.BeginForm("Login", "User", new { r = ViewBag.ReturnUrl }, FormMethod.Post))
        {
            
            
            #line default
            #line hidden
            
            #line 14 "..\..\Areas\Admin\Views\User\_Login_Login.cshtml"
       Write(Html.ValidationSummary());

            
            #line default
            #line hidden
            
            #line 14 "..\..\Areas\Admin\Views\User\_Login_Login.cshtml"
                                     
            if (set.AllowLogin)
            {

            
            #line default
            #line hidden
WriteLiteral("                <div");

WriteLiteral(" class=\"form-group\"");

WriteLiteral(">\r\n                    <input");

WriteLiteral(" class=\"form-control\"");

WriteLiteral(" type=\"text\"");

WriteLiteral(" name=\"username\"");

WriteLiteral(" id=\"username\"");

WriteLiteral(" autocomplete=\"off\"");

WriteLiteral(" placeholder=\"用户名\"");

WriteLiteral(">\r\n                </div>\r\n");

WriteLiteral("                <div");

WriteLiteral(" class=\"form-group\"");

WriteLiteral(">\r\n                    <input");

WriteLiteral(" class=\"form-control form-control-last\"");

WriteLiteral(" type=\"password\"");

WriteLiteral(" id=\"password\"");

WriteLiteral(" placeholder=\"密码\"");

WriteLiteral(" name=\"password\"");

WriteLiteral(" autocomplete=\"off\"");

WriteLiteral(">\r\n                </div>\r\n");

WriteLiteral("                <div");

WriteLiteral(" class=\"kt-login__extra\"");

WriteLiteral(">\r\n                    <label");

WriteLiteral(" class=\"kt-checkbox\"");

WriteLiteral(">\r\n                        <input");

WriteLiteral(" type=\"checkbox\"");

WriteLiteral(" value=\"true\"");

WriteLiteral(" id=\"remember\"");

WriteLiteral(" name=\"remember\"");

WriteLiteral("> 记住我\r\n                        <span></span>\r\n                    </label>\r\n     " +
"               <a");

WriteLiteral(" href=\"javascript:;\"");

WriteLiteral(" id=\"kt_login_forgot\"");

WriteLiteral(" class=\"kt-link\"");

WriteLiteral(">忘记密码 ?</a>\r\n                </div>\r\n");

WriteLiteral("                <div");

WriteLiteral(" class=\"kt-login__actions\"");

WriteLiteral(">\r\n                    <button");

WriteLiteral(" type=\"submit\"");

WriteLiteral(" class=\"btn btn-brand btn-pill btn-elevate\"");

WriteLiteral(">登录</button>\r\n                </div>\r\n");

            
            #line 33 "..\..\Areas\Admin\Views\User\_Login_Login.cshtml"
            }
        }

            
            #line default
            #line hidden
WriteLiteral("    </div>\r\n</div>\r\n\r\n\r\n\r\n\r\n");

        }
    }
}
#pragma warning restore 1591
