#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using NewLife;
    
    #line 1 "..\..\Areas\Admin\Views\User\_Login_Register.cshtml"
    using NewLife.Common;
    
    #line default
    #line hidden
    using NewLife.Cube;
    using NewLife.Reflection;
    using NewLife.Web;
    using XCode;
    using XCode.Membership;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Areas/Admin/Views/User/_Login_Register.cshtml")]
    public partial class _Areas_Admin_Views_User__Login_Register_cshtml : System.Web.Mvc.WebViewPage<dynamic>
    {
        public _Areas_Admin_Views_User__Login_Register_cshtml()
        {
        }
        public override void Execute()
        {
WriteLiteral("\r\n<div");

WriteLiteral(" class=\"kt-login__signup\"");

WriteLiteral(">\r\n    <div");

WriteLiteral(" class=\"kt-login__head\"");

WriteLiteral(">\r\n        <h3");

WriteLiteral(" class=\"kt-login__title\"");

WriteLiteral(">注册</h3>\r\n        <div");

WriteLiteral(" class=\"kt-login__desc\"");

WriteLiteral(">输入您的详细信息以创建账户</div>\r\n    </div>\r\n    <div");

WriteLiteral(" class=\"kt-login__form kt-form\"");

WriteLiteral(">\r\n");

            
            #line 9 "..\..\Areas\Admin\Views\User\_Login_Register.cshtml"
        
            
            #line default
            #line hidden
            
            #line 9 "..\..\Areas\Admin\Views\User\_Login_Register.cshtml"
         using (Html.BeginForm("Register", "User", new { r = ViewBag.ReturnUrl }, FormMethod.Post))
        {

            
            #line default
            #line hidden
WriteLiteral("            <div");

WriteLiteral(" class=\"form-group kt-form__group\"");

WriteLiteral(">\r\n                <input");

WriteLiteral(" class=\"form-control\"");

WriteLiteral(" type=\"text\"");

WriteLiteral(" id=\"username_reg\"");

WriteLiteral(" placeholder=\"用户名\"");

WriteLiteral(" name=\"username\"");

WriteLiteral(">\r\n            </div>\r\n");

WriteLiteral("            <div");

WriteLiteral(" class=\"form-group kt-form__group\"");

WriteLiteral(">\r\n                <input");

WriteLiteral(" class=\"form-control\"");

WriteLiteral(" type=\"text\"");

WriteLiteral(" placeholder=\"邮箱\"");

WriteLiteral(" id=\"email\"");

WriteLiteral(" name=\"email\"");

WriteLiteral(" autocomplete=\"off\"");

WriteLiteral(">\r\n            </div>\r\n");

WriteLiteral("            <div");

WriteLiteral(" class=\"form-group kt-form__group\"");

WriteLiteral(">\r\n                <input");

WriteLiteral(" class=\"form-control\"");

WriteLiteral(" type=\"password\"");

WriteLiteral(" placeholder=\"密码\"");

WriteLiteral(" id=\"password_reg\"");

WriteLiteral(" name=\"password\"");

WriteLiteral(">\r\n            </div>\r\n");

WriteLiteral("            <div");

WriteLiteral(" class=\"form-group kt-form__group\"");

WriteLiteral(">\r\n                <input");

WriteLiteral(" class=\"form-control form-control-last\"");

WriteLiteral(" type=\"password\"");

WriteLiteral(" id=\"password2\"");

WriteLiteral(" placeholder=\"确认密码\"");

WriteLiteral(" name=\"password2\"");

WriteLiteral(">\r\n            </div>\r\n");

WriteLiteral("            <div");

WriteLiteral(" class=\"kt-login__extra\"");

WriteLiteral(">\r\n                <label");

WriteLiteral(" class=\"kt-checkbox\"");

WriteLiteral(">\r\n                    <input");

WriteLiteral(" type=\"checkbox\"");

WriteLiteral(" name=\"agree\"");

WriteLiteral(">我同意 <a");

WriteLiteral(" href=\"#\"");

WriteLiteral(" class=\"kt-link\"");

WriteLiteral(">条款和协议</a>.\r\n                    <span></span>\r\n                </label>\r\n       " +
"     </div>\r\n");

WriteLiteral("            <div");

WriteLiteral(" class=\"kt-login__actions\"");

WriteLiteral(">\r\n                <button");

WriteLiteral(" id=\"kt_login_register_submit\"");

WriteLiteral(" type=\"submit\"");

WriteLiteral(" class=\"btn btn-brand btn-pill btn-elevate\"");

WriteLiteral(">注册</button>\r\n                <button");

WriteLiteral(" id=\"kt_login_signup_cancel\"");

WriteLiteral(" class=\"btn btn-outline-brand btn-pill\"");

WriteLiteral(">返回</button>\r\n            </div>\r\n");

            
            #line 33 "..\..\Areas\Admin\Views\User\_Login_Register.cshtml"
        }

            
            #line default
            #line hidden
WriteLiteral("    </div>\r\n</div>\r\n");

        }
    }
}
#pragma warning restore 1591
