#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Optimization;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using MUI.WebSite;
    using NewLife;
    
    #line 1 "..\..\Views\Shared\_Ace_Layout.cshtml"
    using NewLife.Common;
    
    #line default
    #line hidden
    
    #line 2 "..\..\Views\Shared\_Ace_Layout.cshtml"
    using NewLife.Cube;
    
    #line default
    #line hidden
    using NewLife.Reflection;
    using NewLife.Web;
    using XCode;
    using XCode.Membership;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Shared/_Ace_Layout.cshtml")]
    public partial class _Views_Shared__Ace_Layout_cshtml : System.Web.Mvc.WebViewPage<dynamic>
    {
        public _Views_Shared__Ace_Layout_cshtml()
        {
        }
        public override void Execute()
        {
            
            #line 3 "..\..\Views\Shared\_Ace_Layout.cshtml"
  
    var set = NewLife.Cube.Setting.Current;

            
            #line default
            #line hidden
WriteLiteral("\r\n<!DOCTYPE html>\r\n<html>\r\n<head>\r\n    <meta");

WriteLiteral(" charset=\"utf-8\"");

WriteLiteral(" />\r\n    <title>");

            
            #line 10 "..\..\Views\Shared\_Ace_Layout.cshtml"
      Write(ViewBag.Title);

            
            #line default
            #line hidden
WriteLiteral(" - ");

            
            #line 10 "..\..\Views\Shared\_Ace_Layout.cshtml"
                       Write(SysConfig.Current.DisplayName);

            
            #line default
            #line hidden
WriteLiteral("</title>\r\n    <meta");

WriteLiteral(" name=\"description\"");

WriteAttribute("content", Tuple.Create(" content=\"", 256), Tuple.Create("\"", 325)
, Tuple.Create(Tuple.Create("", 266), Tuple.Create("新生命团队,NewLife,魔方,Cube,XCode,XIoT,", 266), true)
            
            #line 11 "..\..\Views\Shared\_Ace_Layout.cshtml"
, Tuple.Create(Tuple.Create("", 299), Tuple.Create<System.Object, System.Int32>(SysConfig.Current.Company
            
            #line default
            #line hidden
, 299), false)
);

WriteLiteral(">\r\n    <meta");

WriteLiteral(" name=\"viewport\"");

WriteLiteral(" content=\"width=device-width, initial-scale=1, shrink-to-fit=no\"");

WriteLiteral(">\r\n    <link");

WriteAttribute("href", Tuple.Create(" href=\"", 430), Tuple.Create("\"", 450)
, Tuple.Create(Tuple.Create("", 437), Tuple.Create<System.Object, System.Int32>(Href("~/favicon.ico")
, 437), false)
);

WriteLiteral(" rel=\"shortcut icon\"");

WriteLiteral(" type=\"image/x-icon\"");

WriteLiteral(">\r\n    <!--网页字体 -->\r\n    <script");

WriteLiteral(" src=\"https://cdn.bootcss.com/webfont/1.6.28/webfontloader.js\"");

WriteLiteral(@"></script>
    <script>
        WebFont.load({
            google: {
                ""families"": [""Poppins:300,400,500,600,700"", ""Roboto:300,400,500,600,700""]
            },
            active: function () {
                sessionStorage.fonts = true;
            }
        });
    </script>

    <!--页面自定义样式-->
    <link");

WriteAttribute("href", Tuple.Create(" href=\"", 920), Tuple.Create("\"", 951)
, Tuple.Create(Tuple.Create("", 927), Tuple.Create<System.Object, System.Int32>(Href("~/assets/cube.styles.css")
, 927), false)
);

WriteLiteral(" rel=\"stylesheet\"");

WriteLiteral(" />\r\n    <link");

WriteAttribute("href", Tuple.Create(" href=\"", 983), Tuple.Create("\"", 1032)
, Tuple.Create(Tuple.Create("", 990), Tuple.Create<System.Object, System.Int32>(Href("~/assets/css/demo1/pages/login/login-6.css")
, 990), false)
);

WriteLiteral(" rel=\"stylesheet\"");

WriteLiteral(" type=\"text/css\"");

WriteLiteral(" />\r\n\r\n    <!--强制页面样式s -->\r\n    <link");

WriteAttribute("href", Tuple.Create(" href=\"", 1103), Tuple.Create("\"", 1178)
, Tuple.Create(Tuple.Create("", 1110), Tuple.Create<System.Object, System.Int32>(Href("~/assets/vendors/general/perfect-scrollbar/css/perfect-scrollbar.css")
, 1110), false)
);

WriteLiteral(" rel=\"stylesheet\"");

WriteLiteral(" type=\"text/css\"");

WriteLiteral(" />\r\n\r\n    <!--可选页面样式 -->\r\n    <link");

WriteAttribute("href", Tuple.Create(" href=\"", 1248), Tuple.Create("\"", 1324)
, Tuple.Create(Tuple.Create("", 1255), Tuple.Create<System.Object, System.Int32>(Href("~/assets/vendors/general/fortawesome/fontawesome-free/css/all.min.css")
, 1255), false)
);

WriteLiteral(" rel=\"stylesheet\"");

WriteLiteral(" type=\"text/css\"");

WriteLiteral(" />\r\n    <link");

WriteAttribute("href", Tuple.Create(" href=\"", 1372), Tuple.Create("\"", 1430)
, Tuple.Create(Tuple.Create("", 1379), Tuple.Create<System.Object, System.Int32>(Href("~/assets/vendors/general/tether/dist/css/tether.css")
, 1379), false)
);

WriteLiteral(" rel=\"stylesheet\"");

WriteLiteral(" type=\"text/css\"");

WriteLiteral(" />\r\n    <link");

WriteAttribute("href", Tuple.Create(" href=\"", 1478), Tuple.Create("\"", 1565)
, Tuple.Create(Tuple.Create("", 1485), Tuple.Create<System.Object, System.Int32>(Href("~/assets/vendors/general/bootstrap-datepicker/dist/css/bootstrap-datepicker3.css")
, 1485), false)
);

WriteLiteral(" rel=\"stylesheet\"");

WriteLiteral(" type=\"text/css\"");

WriteLiteral(" />\r\n    <link");

WriteAttribute("href", Tuple.Create(" href=\"", 1613), Tuple.Create("\"", 1703)
, Tuple.Create(Tuple.Create("", 1620), Tuple.Create<System.Object, System.Int32>(Href("~/assets/vendors/general/bootstrap-datetime-picker/css/bootstrap-datetimepicker.c" +
"ss")
, 1620), false)
);

WriteLiteral(" rel=\"stylesheet\"");

WriteLiteral(" type=\"text/css\"");

WriteLiteral(" />\r\n    <link");

WriteAttribute("href", Tuple.Create(" href=\"", 1751), Tuple.Create("\"", 1832)
, Tuple.Create(Tuple.Create("", 1758), Tuple.Create<System.Object, System.Int32>(Href("~/assets/vendors/general/bootstrap-timepicker/css/bootstrap-timepicker.css")
, 1758), false)
);

WriteLiteral(" rel=\"stylesheet\"");

WriteLiteral(" type=\"text/css\"");

WriteLiteral(" />\r\n    <link");

WriteAttribute("href", Tuple.Create(" href=\"", 1880), Tuple.Create("\"", 1957)
, Tuple.Create(Tuple.Create("", 1887), Tuple.Create<System.Object, System.Int32>(Href("~/assets/vendors/general/bootstrap-daterangepicker/daterangepicker.css")
, 1887), false)
);

WriteLiteral(" rel=\"stylesheet\"");

WriteLiteral(" type=\"text/css\"");

WriteLiteral(" />\r\n    <link");

WriteAttribute("href", Tuple.Create(" href=\"", 2005), Tuple.Create("\"", 2092)
, Tuple.Create(Tuple.Create("", 2012), Tuple.Create<System.Object, System.Int32>(Href("~/assets/vendors/general/bootstrap-touchspin/dist/jquery.bootstrap-touchspin.css")
, 2012), false)
);

WriteLiteral(" rel=\"stylesheet\"");

WriteLiteral(" type=\"text/css\"");

WriteLiteral(" />\r\n    <link");

WriteAttribute("href", Tuple.Create(" href=\"", 2140), Tuple.Create("\"", 2218)
, Tuple.Create(Tuple.Create("", 2147), Tuple.Create<System.Object, System.Int32>(Href("~/assets/vendors/general/bootstrap-select/dist/css/bootstrap-select.css")
, 2147), false)
);

WriteLiteral(" rel=\"stylesheet\"");

WriteLiteral(" type=\"text/css\"");

WriteLiteral(" />\r\n    <link");

WriteAttribute("href", Tuple.Create(" href=\"", 2266), Tuple.Create("\"", 2355)
, Tuple.Create(Tuple.Create("", 2273), Tuple.Create<System.Object, System.Int32>(Href("~/assets/vendors/general/bootstrap-switch/dist/css/bootstrap3/bootstrap-switch.cs" +
"s")
, 2273), false)
);

WriteLiteral(" rel=\"stylesheet\"");

WriteLiteral(" type=\"text/css\"");

WriteLiteral(" />\r\n    <link");

WriteAttribute("href", Tuple.Create(" href=\"", 2403), Tuple.Create("\"", 2463)
, Tuple.Create(Tuple.Create("", 2410), Tuple.Create<System.Object, System.Int32>(Href("~/assets/vendors/general/select2/dist/css/select2.css")
, 2410), false)
);

WriteLiteral(" rel=\"stylesheet\"");

WriteLiteral(" type=\"text/css\"");

WriteLiteral(" />\r\n    <link");

WriteAttribute("href", Tuple.Create(" href=\"", 2511), Tuple.Create("\"", 2582)
, Tuple.Create(Tuple.Create("", 2518), Tuple.Create<System.Object, System.Int32>(Href("~/assets/vendors/general/ion-rangeslider/css/ion.rangeSlider.css")
, 2518), false)
);

WriteLiteral(" rel=\"stylesheet\"");

WriteLiteral(" type=\"text/css\"");

WriteLiteral(" />\r\n    <link");

WriteAttribute("href", Tuple.Create(" href=\"", 2630), Tuple.Create("\"", 2698)
, Tuple.Create(Tuple.Create("", 2637), Tuple.Create<System.Object, System.Int32>(Href("~/assets/vendors/general/nouislider/distribute/nouislider.css")
, 2637), false)
);

WriteLiteral(" rel=\"stylesheet\"");

WriteLiteral(" type=\"text/css\"");

WriteLiteral(" />\r\n    <link");

WriteAttribute("href", Tuple.Create(" href=\"", 2746), Tuple.Create("\"", 2819)
, Tuple.Create(Tuple.Create("", 2753), Tuple.Create<System.Object, System.Int32>(Href("~/assets/vendors/general/owl.carousel/dist/assets/owl.carousel.css")
, 2753), false)
);

WriteLiteral(" rel=\"stylesheet\"");

WriteLiteral(" type=\"text/css\"");

WriteLiteral(" />\r\n    <link");

WriteAttribute("href", Tuple.Create(" href=\"", 2867), Tuple.Create("\"", 2945)
, Tuple.Create(Tuple.Create("", 2874), Tuple.Create<System.Object, System.Int32>(Href("~/assets/vendors/general/owl.carousel/dist/assets/owl.theme.default.css")
, 2874), false)
);

WriteLiteral(" rel=\"stylesheet\"");

WriteLiteral(" type=\"text/css\"");

WriteLiteral(" />\r\n    <link");

WriteAttribute("href", Tuple.Create(" href=\"", 2993), Tuple.Create("\"", 3051)
, Tuple.Create(Tuple.Create("", 3000), Tuple.Create<System.Object, System.Int32>(Href("~/assets/vendors/general/dropzone/dist/dropzone.css")
, 3000), false)
);

WriteLiteral(" rel=\"stylesheet\"");

WriteLiteral(" type=\"text/css\"");

WriteLiteral(" />\r\n    <link");

WriteAttribute("href", Tuple.Create(" href=\"", 3099), Tuple.Create("\"", 3161)
, Tuple.Create(Tuple.Create("", 3106), Tuple.Create<System.Object, System.Int32>(Href("~/assets/vendors/general/summernote/dist/summernote.css")
, 3106), false)
);

WriteLiteral(" rel=\"stylesheet\"");

WriteLiteral(" type=\"text/css\"");

WriteLiteral(" />\r\n    <link");

WriteAttribute("href", Tuple.Create(" href=\"", 3209), Tuple.Create("\"", 3290)
, Tuple.Create(Tuple.Create("", 3216), Tuple.Create<System.Object, System.Int32>(Href("~/assets/vendors/general/bootstrap-markdown/css/bootstrap-markdown.min.css")
, 3216), false)
);

WriteLiteral(" rel=\"stylesheet\"");

WriteLiteral(" type=\"text/css\"");

WriteLiteral(" />\r\n    <link");

WriteAttribute("href", Tuple.Create(" href=\"", 3338), Tuple.Create("\"", 3393)
, Tuple.Create(Tuple.Create("", 3345), Tuple.Create<System.Object, System.Int32>(Href("~/assets/vendors/general/animate.css/animate.css")
, 3345), false)
);

WriteLiteral(" rel=\"stylesheet\"");

WriteLiteral(" type=\"text/css\"");

WriteLiteral(" />\r\n    <link");

WriteAttribute("href", Tuple.Create(" href=\"", 3441), Tuple.Create("\"", 3496)
, Tuple.Create(Tuple.Create("", 3448), Tuple.Create<System.Object, System.Int32>(Href("~/assets/vendors/general/toastr/build/toastr.css")
, 3448), false)
);

WriteLiteral(" rel=\"stylesheet\"");

WriteLiteral(" type=\"text/css\"");

WriteLiteral(" />\r\n    <link");

WriteAttribute("href", Tuple.Create(" href=\"", 3544), Tuple.Create("\"", 3596)
, Tuple.Create(Tuple.Create("", 3551), Tuple.Create<System.Object, System.Int32>(Href("~/assets/vendors/general/morris.js/morris.css")
, 3551), false)
);

WriteLiteral(" rel=\"stylesheet\"");

WriteLiteral(" type=\"text/css\"");

WriteLiteral(" />\r\n    <link");

WriteAttribute("href", Tuple.Create(" href=\"", 3644), Tuple.Create("\"", 3708)
, Tuple.Create(Tuple.Create("", 3651), Tuple.Create<System.Object, System.Int32>(Href("~/assets/vendors/general/sweetalert2/dist/sweetalert2.css")
, 3651), false)
);

WriteLiteral(" rel=\"stylesheet\"");

WriteLiteral(" type=\"text/css\"");

WriteLiteral(" />\r\n    <link");

WriteAttribute("href", Tuple.Create(" href=\"", 3756), Tuple.Create("\"", 3811)
, Tuple.Create(Tuple.Create("", 3763), Tuple.Create<System.Object, System.Int32>(Href("~/assets/vendors/general/socicon/css/socicon.css")
, 3763), false)
);

WriteLiteral(" rel=\"stylesheet\"");

WriteLiteral(" type=\"text/css\"");

WriteLiteral(" />\r\n    <link");

WriteAttribute("href", Tuple.Create(" href=\"", 3859), Tuple.Create("\"", 3931)
, Tuple.Create(Tuple.Create("", 3866), Tuple.Create<System.Object, System.Int32>(Href("~/assets/vendors/custom/vendors/line-awesome/css/line-awesome.css")
, 3866), false)
);

WriteLiteral(" rel=\"stylesheet\"");

WriteLiteral(" type=\"text/css\"");

WriteLiteral(" />\r\n    <link");

WriteAttribute("href", Tuple.Create(" href=\"", 3979), Tuple.Create("\"", 4039)
, Tuple.Create(Tuple.Create("", 3986), Tuple.Create<System.Object, System.Int32>(Href("~/assets/vendors/custom/vendors/flaticon/flaticon.css")
, 3986), false)
);

WriteLiteral(" rel=\"stylesheet\"");

WriteLiteral(" type=\"text/css\"");

WriteLiteral(" />\r\n    <link");

WriteAttribute("href", Tuple.Create(" href=\"", 4087), Tuple.Create("\"", 4148)
, Tuple.Create(Tuple.Create("", 4094), Tuple.Create<System.Object, System.Int32>(Href("~/assets/vendors/custom/vendors/flaticon2/flaticon.css")
, 4094), false)
);

WriteLiteral(" rel=\"stylesheet\"");

WriteLiteral(" type=\"text/css\"");

WriteLiteral(" />\r\n    <link");

WriteAttribute("href", Tuple.Create(" href=\"", 4196), Tuple.Create("\"", 4248)
, Tuple.Create(Tuple.Create("", 4203), Tuple.Create<System.Object, System.Int32>(Href("~/assets/vendors/custom/viewer/viewer.min.css")
, 4203), false)
);

WriteLiteral(" rel=\"stylesheet\"");

WriteLiteral(" />\r\n\r\n    <!--主题样式-->\r\n    <link");

WriteAttribute("href", Tuple.Create(" href=\"", 4299), Tuple.Create("\"", 4341)
, Tuple.Create(Tuple.Create("", 4306), Tuple.Create<System.Object, System.Int32>(Href("~/assets/css/demo1/style.bundle.css")
, 4306), false)
);

WriteLiteral(" rel=\"stylesheet\"");

WriteLiteral(" type=\"text/css\"");

WriteLiteral(" />\r\n    <link");

WriteAttribute("href", Tuple.Create(" href=\"", 4389), Tuple.Create("\"", 4442)
, Tuple.Create(Tuple.Create("", 4396), Tuple.Create<System.Object, System.Int32>(Href("~/assets/css/demo1/skins/header/base/light.css")
, 4396), false)
);

WriteLiteral(" rel=\"stylesheet\"");

WriteLiteral(" type=\"text/css\"");

WriteLiteral(" />\r\n    <link");

WriteAttribute("href", Tuple.Create(" href=\"", 4490), Tuple.Create("\"", 4543)
, Tuple.Create(Tuple.Create("", 4497), Tuple.Create<System.Object, System.Int32>(Href("~/assets/css/demo1/skins/header/menu/light.css")
, 4497), false)
);

WriteLiteral(" rel=\"stylesheet\"");

WriteLiteral(" type=\"text/css\"");

WriteLiteral(" />\r\n    <link");

WriteAttribute("href", Tuple.Create(" href=\"", 4591), Tuple.Create("\"", 4637)
, Tuple.Create(Tuple.Create("", 4598), Tuple.Create<System.Object, System.Int32>(Href("~/assets/css/demo1/skins/brand/dark.css")
, 4598), false)
);

WriteLiteral(" rel=\"stylesheet\"");

WriteLiteral(" type=\"text/css\"");

WriteLiteral(" />\r\n    <link");

WriteAttribute("href", Tuple.Create(" href=\"", 4685), Tuple.Create("\"", 4731)
, Tuple.Create(Tuple.Create("", 4692), Tuple.Create<System.Object, System.Int32>(Href("~/assets/css/demo1/skins/aside/dark.css")
, 4692), false)
);

WriteLiteral(" rel=\"stylesheet\"");

WriteLiteral(" type=\"text/css\"");

WriteLiteral(" />\r\n\r\n    <!-- 自定义样式 -->\r\n\r\n");

WriteLiteral("    ");

            
            #line 71 "..\..\Views\Shared\_Ace_Layout.cshtml"
Write(RenderSection("css", required: false));

            
            #line default
            #line hidden
WriteLiteral(@"

    <!-- 全局配置-->
    <script>
        var KTAppOptions = {
            ""colors"": {
                ""state"": {
                    ""brand"": ""#5d78ff"",
                    ""dark"": ""#282a3c"",
                    ""light"": ""#ffffff"",
                    ""primary"": ""#5867dd"",
                    ""success"": ""#34bfa3"",
                    ""info"": ""#36a3f7"",
                    ""warning"": ""#ffb822"",
                    ""danger"": ""#fd3995""
                },
                ""base"": {
                    ""label"": [""#c5cbe3"", ""#a1a8c3"", ""#3d4465"", ""#3e4466""],
                    ""shape"": [""#f0f3ff"", ""#d9dffa"", ""#afb4d4"", ""#646c9a""]
                }
            }
        };
    </script>

    <!--核心脚本 -->
    <script");

WriteAttribute("src", Tuple.Create(" src=\"", 5577), Tuple.Create("\"", 5629)
, Tuple.Create(Tuple.Create("", 5583), Tuple.Create<System.Object, System.Int32>(Href("~/assets/vendors/general/jquery/dist/jquery.js")
, 5583), false)
);

WriteLiteral(" type=\"text/javascript\"");

WriteLiteral("></script>\r\n    <script");

WriteAttribute("src", Tuple.Create(" src=\"", 5676), Tuple.Create("\"", 5735)
, Tuple.Create(Tuple.Create("", 5682), Tuple.Create<System.Object, System.Int32>(Href("~/assets/vendors/general/popper.js/dist/umd/popper.js")
, 5682), false)
);

WriteLiteral(" type=\"text/javascript\"");

WriteLiteral("></script>\r\n    <script");

WriteAttribute("src", Tuple.Create(" src=\"", 5782), Tuple.Create("\"", 5847)
, Tuple.Create(Tuple.Create("", 5788), Tuple.Create<System.Object, System.Int32>(Href("~/assets/vendors/general/bootstrap/dist/js/bootstrap.min.js")
, 5788), false)
);

WriteLiteral(" type=\"text/javascript\"");

WriteLiteral("></script>\r\n    <script");

WriteAttribute("src", Tuple.Create(" src=\"", 5894), Tuple.Create("\"", 5951)
, Tuple.Create(Tuple.Create("", 5900), Tuple.Create<System.Object, System.Int32>(Href("~/assets/vendors/general/js-cookie/src/js.cookie.js")
, 5900), false)
);

WriteLiteral(" type=\"text/javascript\"");

WriteLiteral("></script>\r\n    <script");

WriteAttribute("src", Tuple.Create(" src=\"", 5998), Tuple.Create("\"", 6053)
, Tuple.Create(Tuple.Create("", 6004), Tuple.Create<System.Object, System.Int32>(Href("~/assets/vendors/general/moment/min/moment.min.js")
, 6004), false)
);

WriteLiteral(" type=\"text/javascript\"");

WriteLiteral("></script>\r\n    <script");

WriteAttribute("src", Tuple.Create(" src=\"", 6100), Tuple.Create("\"", 6165)
, Tuple.Create(Tuple.Create("", 6106), Tuple.Create<System.Object, System.Int32>(Href("~/assets/vendors/general/tooltip.js/dist/umd/tooltip.min.js")
, 6106), false)
);

WriteLiteral(" type=\"text/javascript\"");

WriteLiteral("></script>\r\n    <script");

WriteAttribute("src", Tuple.Create(" src=\"", 6212), Tuple.Create("\"", 6286)
, Tuple.Create(Tuple.Create("", 6218), Tuple.Create<System.Object, System.Int32>(Href("~/assets/vendors/general/perfect-scrollbar/dist/perfect-scrollbar.js")
, 6218), false)
);

WriteLiteral(" type=\"text/javascript\"");

WriteLiteral("></script>\r\n    <script");

WriteAttribute("src", Tuple.Create(" src=\"", 6333), Tuple.Create("\"", 6392)
, Tuple.Create(Tuple.Create("", 6339), Tuple.Create<System.Object, System.Int32>(Href("~/assets/vendors/general/sticky-js/dist/sticky.min.js")
, 6339), false)
);

WriteLiteral(" type=\"text/javascript\"");

WriteLiteral("></script>\r\n    <script");

WriteAttribute("src", Tuple.Create(" src=\"", 6439), Tuple.Create("\"", 6484)
, Tuple.Create(Tuple.Create("", 6445), Tuple.Create<System.Object, System.Int32>(Href("~/assets/vendors/general/wnumb/wNumb.js")
, 6445), false)
);

WriteLiteral(" type=\"text/javascript\"");

WriteLiteral("></script>\r\n\r\n</head>\r\n<body");

WriteLiteral(" class=\"kt-quick-panel--right kt-demo-panel--right kt-offcanvas-panel--right kt-h" +
"eader--fixed kt-header-mobile--fixed kt-subheader--enabled kt-subheader--fixed k" +
"t-subheader--solid kt-aside--enabled kt-aside--fixed kt-page--loading\"");

WriteLiteral(">\r\n\r\n    <!-- 手机菜单栏 -->\r\n    <div");

WriteLiteral(" id=\"kt_header_mobile\"");

WriteLiteral(" class=\"kt-header-mobile  kt-header-mobile--fixed \"");

WriteLiteral(">\r\n        <div");

WriteLiteral(" class=\"kt-header-mobile__logo\"");

WriteLiteral(">\r\n            <a");

WriteAttribute("href", Tuple.Create(" href=\"", 6936), Tuple.Create("\"", 6957)
            
            #line 112 "..\..\Views\Shared\_Ace_Layout.cshtml"
, Tuple.Create(Tuple.Create("", 6943), Tuple.Create<System.Object, System.Int32>(set.StartPage
            
            #line default
            #line hidden
, 6943), false)
);

WriteLiteral(">\r\n                <img");

WriteAttribute("alt", Tuple.Create(" alt=\"", 6981), Tuple.Create("\"", 7027)
            
            #line 113 "..\..\Views\Shared\_Ace_Layout.cshtml"
, Tuple.Create(Tuple.Create("", 6987), Tuple.Create<System.Object, System.Int32>(MUI.WebSite.CompanySetting.Current.Name
            
            #line default
            #line hidden
, 6987), false)
);

WriteAttribute("src", Tuple.Create(" src=\"", 7028), Tuple.Create("\"", 7057)
, Tuple.Create(Tuple.Create("", 7034), Tuple.Create<System.Object, System.Int32>(Href("~/assets/image/logo.png")
, 7034), false)
);

WriteLiteral(" style=\"width:40px;height:40px;\"");

WriteLiteral(" />\r\n            </a>\r\n        </div>\r\n        <div");

WriteLiteral(" class=\"kt-header-mobile__toolbar\"");

WriteLiteral(">\r\n            <button");

WriteLiteral(" class=\"kt-header-mobile__toggler kt-header-mobile__toggler--left\"");

WriteLiteral(" id=\"kt_aside_mobile_toggler\"");

WriteLiteral("><span></span></button>\r\n            <button");

WriteLiteral(" class=\"kt-header-mobile__topbar-toggler\"");

WriteLiteral(" id=\"kt_header_mobile_topbar_toggler\"");

WriteLiteral("><i");

WriteLiteral(" class=\"flaticon-more\"");

WriteLiteral("></i></button>\r\n        </div>\r\n    </div>\r\n\r\n    <!--网页显示内容-->\r\n    <div");

WriteLiteral(" class=\"kt-grid kt-grid--hor kt-grid--root\"");

WriteLiteral(">\r\n        <div");

WriteLiteral(" class=\"kt-grid__item kt-grid__item--fluid kt-grid kt-grid--ver kt-page\"");

WriteLiteral(">\r\n\r\n            <!-- 侧边栏 -->\r\n            <button");

WriteLiteral(" class=\"kt-aside-close \"");

WriteLiteral(" id=\"kt_aside_close_btn\"");

WriteLiteral("><i");

WriteLiteral(" class=\"la la-close\"");

WriteLiteral("></i></button>\r\n            <div");

WriteLiteral(" class=\"kt-aside  kt-aside--fixed  kt-grid__item kt-grid kt-grid--desktop kt-grid" +
"--hor-desktop\"");

WriteLiteral(" id=\"kt_aside\"");

WriteLiteral(">\r\n                <!--侧边栏Logo-->\r\n");

WriteLiteral("                ");

            
            #line 130 "..\..\Views\Shared\_Ace_Layout.cshtml"
           Write(Html.Partial("_Nav_Aside"));

            
            #line default
            #line hidden
WriteLiteral("\r\n                <!--侧边栏菜单-->\r\n");

WriteLiteral("                ");

            
            #line 132 "..\..\Views\Shared\_Ace_Layout.cshtml"
           Write(Html.Partial("_Nav_AsideMenu"));

            
            #line default
            #line hidden
WriteLiteral("\r\n            </div>\r\n\r\n            <!--右边内容页-->\r\n            <div");

WriteLiteral(" class=\"kt-grid__item kt-grid__item--fluid kt-grid kt-grid--hor kt-wrapper\"");

WriteLiteral(" id=\"kt_wrapper\"");

WriteLiteral(">\r\n                <!-- 顶部菜单-->\r\n                <div");

WriteLiteral(" id=\"kt_header\"");

WriteLiteral(" class=\"kt-header kt-grid__item  kt-header--fixed \"");

WriteLiteral(">\r\n");

WriteLiteral("                    ");

            
            #line 139 "..\..\Views\Shared\_Ace_Layout.cshtml"
               Write(Html.Partial("_Nav_TopMenu"));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("                    ");

            
            #line 140 "..\..\Views\Shared\_Ace_Layout.cshtml"
               Write(Html.Partial("_Nav_TopBar"));

            
            #line default
            #line hidden
WriteLiteral("\r\n                </div>\r\n\r\n                <!-- 详细内容-->\r\n                <div");

WriteLiteral(" class=\"kt-content  kt-grid__item kt-grid__item--fluid kt-grid kt-grid--hor p-0\"");

WriteLiteral(" id=\"kt_content\"");

WriteLiteral(">\r\n\r\n                    <div");

WriteLiteral(" class=\"kt-container  kt-container--fluid  kt-grid__item kt-grid__item--fluid pl-" +
"0 pr-0\"");

WriteLiteral(">\r\n");

WriteLiteral("                        ");

            
            #line 147 "..\..\Views\Shared\_Ace_Layout.cshtml"
                   Write(RenderBody());

            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n");

            
            #line 149 "..\..\Views\Shared\_Ace_Layout.cshtml"
                        
            
            #line default
            #line hidden
            
            #line 149 "..\..\Views\Shared\_Ace_Layout.cshtml"
                         if (DbRunTimeModule.Enable)
                        {

            
            #line default
            #line hidden
WriteLiteral("                            <div");

WriteLiteral(" class=\"kt-padding-0\"");

WriteLiteral(">\r\n                                <div");

WriteLiteral(" class=\"alert alert-secondary\"");

WriteLiteral(" role=\"alert\"");

WriteLiteral(">\r\n                                    <div");

WriteLiteral(" class=\"alert-text\"");

WriteLiteral(">\r\n");

WriteLiteral("                                        ");

            
            #line 154 "..\..\Views\Shared\_Ace_Layout.cshtml"
                                   Write(Html.Raw(DbRunTimeModule.GetInfo()));

            
            #line default
            #line hidden
WriteLiteral("\r\n                                    </div>\r\n                                </d" +
"iv>\r\n                            </div>\r\n");

            
            #line 158 "..\..\Views\Shared\_Ace_Layout.cshtml"
                        }

            
            #line default
            #line hidden
WriteLiteral("                    </div>\r\n                </div>\r\n\r\n            </div>\r\n\r\n     " +
"   </div>\r\n    </div>\r\n\r\n    <!--购物车-->\r\n    <div");

WriteLiteral(" id=\"kt_quick_panel\"");

WriteLiteral(" class=\"kt-quick-panel\"");

WriteLiteral(" >\r\n        <a");

WriteLiteral(" href=\"#\"");

WriteLiteral(" class=\"kt-quick-panel__close\"");

WriteLiteral(" id=\"kt_quick_panel_close_btn\"");

WriteLiteral("><i");

WriteLiteral(" class=\"flaticon2-delete\"");

WriteLiteral("></i></a>\r\n        <div");

WriteLiteral(" id=\"kt_quick_panel_content\"");

WriteLiteral(">\r\n");

WriteLiteral("            ");

            
            #line 171 "..\..\Views\Shared\_Ace_Layout.cshtml"
       Write(Html.Partial("_Quick_Panel"));

            
            #line default
            #line hidden
WriteLiteral("\r\n        </div>\r\n\r\n    </div>\r\n\r\n    <!--滚动条-->\r\n    <div");

WriteLiteral(" id=\"kt_scrolltop\"");

WriteLiteral(" class=\"kt-scrolltop\"");

WriteLiteral(">\r\n        <i");

WriteLiteral(" class=\"fa fa-arrow-up\"");

WriteLiteral("></i>\r\n    </div>\r\n\r\n    <div");

WriteLiteral(" id=\"div_footer\"");

WriteLiteral(">\r\n\r\n    </div>\r\n\r\n    <!----------------------------------------以下为js脚本区域-------" +
"---------------------------------------------------------->\r\n    <!-- 可选脚本 -->\r\n" +
"    <script");

WriteAttribute("src", Tuple.Create(" src=\"", 10009), Tuple.Create("\"", 10075)
, Tuple.Create(Tuple.Create("", 10015), Tuple.Create<System.Object, System.Int32>(Href("~/assets/vendors/general/jquery-form/dist/jquery.form.min.js")
, 10015), false)
);

WriteLiteral(" type=\"text/javascript\"");

WriteLiteral("></script>\r\n    <script");

WriteAttribute("src", Tuple.Create(" src=\"", 10122), Tuple.Create("\"", 10179)
, Tuple.Create(Tuple.Create("", 10128), Tuple.Create<System.Object, System.Int32>(Href("~/assets/vendors/general/block-ui/jquery.blockUI.js")
, 10128), false)
);

WriteLiteral(" type=\"text/javascript\"");

WriteLiteral("></script>\r\n    <script");

WriteAttribute("src", Tuple.Create(" src=\"", 10226), Tuple.Create("\"", 10313)
, Tuple.Create(Tuple.Create("", 10232), Tuple.Create<System.Object, System.Int32>(Href("~/assets/vendors/general/bootstrap-datepicker/dist/js/bootstrap-datepicker.min.js" +
"")
, 10232), false)
);

WriteLiteral(" type=\"text/javascript\"");

WriteLiteral("></script>\r\n    <script");

WriteAttribute("src", Tuple.Create(" src=\"", 10360), Tuple.Create("\"", 10429)
, Tuple.Create(Tuple.Create("", 10366), Tuple.Create<System.Object, System.Int32>(Href("~/assets/vendors/custom/js/vendors/bootstrap-datepicker.init.js")
, 10366), false)
);

WriteLiteral(" type=\"text/javascript\"");

WriteLiteral("></script>\r\n    <script");

WriteAttribute("src", Tuple.Create(" src=\"", 10476), Tuple.Create("\"", 10567)
, Tuple.Create(Tuple.Create("", 10482), Tuple.Create<System.Object, System.Int32>(Href("~/assets/vendors/general/bootstrap-datetime-picker/js/bootstrap-datetimepicker.mi" +
"n.js")
, 10482), false)
);

WriteLiteral(" type=\"text/javascript\"");

WriteLiteral("></script>\r\n    <script");

WriteAttribute("src", Tuple.Create(" src=\"", 10614), Tuple.Create("\"", 10715)
, Tuple.Create(Tuple.Create("", 10620), Tuple.Create<System.Object, System.Int32>(Href("~/assets/vendors/general/bootstrap-datetime-picker/js/locales/bootstrap-datetimep" +
"icker.zh-CN.js")
, 10620), false)
);

WriteLiteral("></script>\r\n    <script");

WriteAttribute("src", Tuple.Create(" src=\"", 10739), Tuple.Create("\"", 10821)
, Tuple.Create(Tuple.Create("", 10745), Tuple.Create<System.Object, System.Int32>(Href("~/assets/vendors/general/bootstrap-timepicker/js/bootstrap-timepicker.min.js")
, 10745), false)
);

WriteLiteral(" type=\"text/javascript\"");

WriteLiteral("></script>\r\n    <script");

WriteAttribute("src", Tuple.Create(" src=\"", 10868), Tuple.Create("\"", 10937)
, Tuple.Create(Tuple.Create("", 10874), Tuple.Create<System.Object, System.Int32>(Href("~/assets/vendors/custom/js/vendors/bootstrap-timepicker.init.js")
, 10874), false)
);

WriteLiteral(" type=\"text/javascript\"");

WriteLiteral("></script>\r\n    <script");

WriteAttribute("src", Tuple.Create(" src=\"", 10984), Tuple.Create("\"", 11059)
, Tuple.Create(Tuple.Create("", 10990), Tuple.Create<System.Object, System.Int32>(Href("~/assets/vendors/general/bootstrap-daterangepicker/daterangepicker.js")
, 10990), false)
);

WriteLiteral(" type=\"text/javascript\"");

WriteLiteral("></script>\r\n    <script");

WriteAttribute("src", Tuple.Create(" src=\"", 11106), Tuple.Create("\"", 11191)
, Tuple.Create(Tuple.Create("", 11112), Tuple.Create<System.Object, System.Int32>(Href("~/assets/vendors/general/bootstrap-touchspin/dist/jquery.bootstrap-touchspin.js")
, 11112), false)
);

WriteLiteral(" type=\"text/javascript\"");

WriteLiteral("></script>\r\n    <script");

WriteAttribute("src", Tuple.Create(" src=\"", 11238), Tuple.Create("\"", 11315)
, Tuple.Create(Tuple.Create("", 11244), Tuple.Create<System.Object, System.Int32>(Href("~/assets/vendors/general/bootstrap-maxlength/src/bootstrap-maxlength.js")
, 11244), false)
);

WriteLiteral(" type=\"text/javascript\"");

WriteLiteral("></script>\r\n    <script");

WriteAttribute("src", Tuple.Create(" src=\"", 11362), Tuple.Create("\"", 11466)
, Tuple.Create(Tuple.Create("", 11368), Tuple.Create<System.Object, System.Int32>(Href("~/assets/vendors/custom/vendors/bootstrap-multiselectsplitter/bootstrap-multisele" +
"ctsplitter.min.js")
, 11368), false)
);

WriteLiteral(" type=\"text/javascript\"");

WriteLiteral("></script>\r\n    <script");

WriteAttribute("src", Tuple.Create(" src=\"", 11513), Tuple.Create("\"", 11588)
, Tuple.Create(Tuple.Create("", 11519), Tuple.Create<System.Object, System.Int32>(Href("~/assets/vendors/general/bootstrap-select/dist/js/bootstrap-select.js")
, 11519), false)
);

WriteLiteral(" type=\"text/javascript\"");

WriteLiteral("></script>\r\n    <script");

WriteAttribute("src", Tuple.Create(" src=\"", 11635), Tuple.Create("\"", 11710)
, Tuple.Create(Tuple.Create("", 11641), Tuple.Create<System.Object, System.Int32>(Href("~/assets/vendors/general/bootstrap-switch/dist/js/bootstrap-switch.js")
, 11641), false)
);

WriteLiteral(" type=\"text/javascript\"");

WriteLiteral("></script>\r\n    <script");

WriteAttribute("src", Tuple.Create(" src=\"", 11757), Tuple.Create("\"", 11822)
, Tuple.Create(Tuple.Create("", 11763), Tuple.Create<System.Object, System.Int32>(Href("~/assets/vendors/custom/js/vendors/bootstrap-switch.init.js")
, 11763), false)
);

WriteLiteral(" type=\"text/javascript\"");

WriteLiteral("></script>\r\n    <script");

WriteAttribute("src", Tuple.Create(" src=\"", 11869), Tuple.Create("\"", 11931)
, Tuple.Create(Tuple.Create("", 11875), Tuple.Create<System.Object, System.Int32>(Href("~/assets/vendors/general/select2/dist/js/select2.full.js")
, 11875), false)
);

WriteLiteral(" type=\"text/javascript\"");

WriteLiteral("></script>\r\n    <script");

WriteAttribute("src", Tuple.Create(" src=\"", 11978), Tuple.Create("\"", 12046)
, Tuple.Create(Tuple.Create("", 11984), Tuple.Create<System.Object, System.Int32>(Href("~/assets/vendors/general/ion-rangeslider/js/ion.rangeSlider.js")
, 11984), false)
);

WriteLiteral(" type=\"text/javascript\"");

WriteLiteral("></script>\r\n    <script");

WriteAttribute("src", Tuple.Create(" src=\"", 12093), Tuple.Create("\"", 12161)
, Tuple.Create(Tuple.Create("", 12099), Tuple.Create<System.Object, System.Int32>(Href("~/assets/vendors/general/typeahead.js/dist/typeahead.bundle.js")
, 12099), false)
);

WriteLiteral(" type=\"text/javascript\"");

WriteLiteral("></script>\r\n    <script");

WriteAttribute("src", Tuple.Create(" src=\"", 12208), Tuple.Create("\"", 12268)
, Tuple.Create(Tuple.Create("", 12214), Tuple.Create<System.Object, System.Int32>(Href("~/assets/vendors/general/handlebars/dist/handlebars.js")
, 12214), false)
);

WriteLiteral(" type=\"text/javascript\"");

WriteLiteral("></script>\r\n    <script");

WriteAttribute("src", Tuple.Create(" src=\"", 12315), Tuple.Create("\"", 12387)
, Tuple.Create(Tuple.Create("", 12321), Tuple.Create<System.Object, System.Int32>(Href("~/assets/vendors/general/inputmask/dist/jquery.inputmask.bundle.js")
, 12321), false)
);

WriteLiteral(" type=\"text/javascript\"");

WriteLiteral("></script>\r\n    <script");

WriteAttribute("src", Tuple.Create(" src=\"", 12434), Tuple.Create("\"", 12518)
, Tuple.Create(Tuple.Create("", 12440), Tuple.Create<System.Object, System.Int32>(Href("~/assets/vendors/general/inputmask/dist/inputmask/inputmask.date.extensions.js")
, 12440), false)
);

WriteLiteral(" type=\"text/javascript\"");

WriteLiteral("></script>\r\n    <script");

WriteAttribute("src", Tuple.Create(" src=\"", 12565), Tuple.Create("\"", 12652)
, Tuple.Create(Tuple.Create("", 12571), Tuple.Create<System.Object, System.Int32>(Href("~/assets/vendors/general/inputmask/dist/inputmask/inputmask.numeric.extensions.js" +
"")
, 12571), false)
);

WriteLiteral(" type=\"text/javascript\"");

WriteLiteral("></script>\r\n    <script");

WriteAttribute("src", Tuple.Create(" src=\"", 12699), Tuple.Create("\"", 12765)
, Tuple.Create(Tuple.Create("", 12705), Tuple.Create<System.Object, System.Int32>(Href("~/assets/vendors/general/nouislider/distribute/nouislider.js")
, 12705), false)
);

WriteLiteral(" type=\"text/javascript\"");

WriteLiteral("></script>\r\n    <script");

WriteAttribute("src", Tuple.Create(" src=\"", 12812), Tuple.Create("\"", 12876)
, Tuple.Create(Tuple.Create("", 12818), Tuple.Create<System.Object, System.Int32>(Href("~/assets/vendors/general/owl.carousel/dist/owl.carousel.js")
, 12818), false)
);

WriteLiteral(" type=\"text/javascript\"");

WriteLiteral("></script>\r\n    <script");

WriteAttribute("src", Tuple.Create(" src=\"", 12923), Tuple.Create("\"", 12979)
, Tuple.Create(Tuple.Create("", 12929), Tuple.Create<System.Object, System.Int32>(Href("~/assets/vendors/general/autosize/dist/autosize.js")
, 12929), false)
);

WriteLiteral(" type=\"text/javascript\"");

WriteLiteral("></script>\r\n    <script");

WriteAttribute("src", Tuple.Create(" src=\"", 13026), Tuple.Create("\"", 13088)
, Tuple.Create(Tuple.Create("", 13032), Tuple.Create<System.Object, System.Int32>(Href("~/assets/vendors/general/clipboard/dist/clipboard.min.js")
, 13032), false)
);

WriteLiteral(" type=\"text/javascript\"");

WriteLiteral("></script>\r\n    <script");

WriteAttribute("src", Tuple.Create(" src=\"", 13135), Tuple.Create("\"", 13191)
, Tuple.Create(Tuple.Create("", 13141), Tuple.Create<System.Object, System.Int32>(Href("~/assets/vendors/general/dropzone/dist/dropzone.js")
, 13141), false)
);

WriteLiteral(" type=\"text/javascript\"");

WriteLiteral("></script>\r\n    <script");

WriteAttribute("src", Tuple.Create(" src=\"", 13238), Tuple.Create("\"", 13298)
, Tuple.Create(Tuple.Create("", 13244), Tuple.Create<System.Object, System.Int32>(Href("~/assets/vendors/general/summernote/dist/summernote.js")
, 13244), false)
);

WriteLiteral(" type=\"text/javascript\"");

WriteLiteral("></script>\r\n    <script");

WriteAttribute("src", Tuple.Create(" src=\"", 13345), Tuple.Create("\"", 13400)
, Tuple.Create(Tuple.Create("", 13351), Tuple.Create<System.Object, System.Int32>(Href("~/assets/vendors/general/markdown/lib/markdown.js")
, 13351), false)
);

WriteLiteral(" type=\"text/javascript\"");

WriteLiteral("></script>\r\n    <script");

WriteAttribute("src", Tuple.Create(" src=\"", 13447), Tuple.Create("\"", 13521)
, Tuple.Create(Tuple.Create("", 13453), Tuple.Create<System.Object, System.Int32>(Href("~/assets/vendors/general/bootstrap-markdown/js/bootstrap-markdown.js")
, 13453), false)
);

WriteLiteral(" type=\"text/javascript\"");

WriteLiteral("></script>\r\n    <script");

WriteAttribute("src", Tuple.Create(" src=\"", 13568), Tuple.Create("\"", 13635)
, Tuple.Create(Tuple.Create("", 13574), Tuple.Create<System.Object, System.Int32>(Href("~/assets/vendors/custom/js/vendors/bootstrap-markdown.init.js")
, 13574), false)
);

WriteLiteral(" type=\"text/javascript\"");

WriteLiteral("></script>\r\n    <script");

WriteAttribute("src", Tuple.Create(" src=\"", 13682), Tuple.Create("\"", 13753)
, Tuple.Create(Tuple.Create("", 13688), Tuple.Create<System.Object, System.Int32>(Href("~/assets/vendors/general/bootstrap-notify/bootstrap-notify.min.js")
, 13688), false)
);

WriteLiteral(" type=\"text/javascript\"");

WriteLiteral("></script>\r\n    <script");

WriteAttribute("src", Tuple.Create(" src=\"", 13800), Tuple.Create("\"", 13865)
, Tuple.Create(Tuple.Create("", 13806), Tuple.Create<System.Object, System.Int32>(Href("~/assets/vendors/custom/js/vendors/bootstrap-notify.init.js")
, 13806), false)
);

WriteLiteral(" type=\"text/javascript\"");

WriteLiteral("></script>\r\n    <script");

WriteAttribute("src", Tuple.Create(" src=\"", 13912), Tuple.Create("\"", 13984)
, Tuple.Create(Tuple.Create("", 13918), Tuple.Create<System.Object, System.Int32>(Href("~/assets/vendors/general/jquery-validation/dist/jquery.validate.js")
, 13918), false)
);

WriteLiteral(" type=\"text/javascript\"");

WriteLiteral("></script>\r\n    <script");

WriteAttribute("src", Tuple.Create(" src=\"", 14031), Tuple.Create("\"", 14106)
, Tuple.Create(Tuple.Create("", 14037), Tuple.Create<System.Object, System.Int32>(Href("~/assets/vendors/general/jquery-validation/dist/additional-methods.js")
, 14037), false)
);

WriteLiteral(" type=\"text/javascript\"");

WriteLiteral("></script>\r\n    <script");

WriteAttribute("src", Tuple.Create(" src=\"", 14153), Tuple.Create("\"", 14219)
, Tuple.Create(Tuple.Create("", 14159), Tuple.Create<System.Object, System.Int32>(Href("~/assets/vendors/custom/js/vendors/jquery-validation.init.js")
, 14159), false)
);

WriteLiteral(" type=\"text/javascript\"");

WriteLiteral("></script>\r\n    <script");

WriteAttribute("src", Tuple.Create(" src=\"", 14266), Tuple.Create("\"", 14323)
, Tuple.Create(Tuple.Create("", 14272), Tuple.Create<System.Object, System.Int32>(Href("~/assets/vendors/general/toastr/build/toastr.min.js")
, 14272), false)
);

WriteLiteral(" type=\"text/javascript\"");

WriteLiteral("></script>\r\n    <script");

WriteAttribute("src", Tuple.Create(" src=\"", 14370), Tuple.Create("\"", 14419)
, Tuple.Create(Tuple.Create("", 14376), Tuple.Create<System.Object, System.Int32>(Href("~/assets/vendors/general/raphael/raphael.js")
, 14376), false)
);

WriteLiteral(" type=\"text/javascript\"");

WriteLiteral("></script>\r\n    <script");

WriteAttribute("src", Tuple.Create(" src=\"", 14466), Tuple.Create("\"", 14516)
, Tuple.Create(Tuple.Create("", 14472), Tuple.Create<System.Object, System.Int32>(Href("~/assets/vendors/general/morris.js/morris.js")
, 14472), false)
);

WriteLiteral(" type=\"text/javascript\"");

WriteLiteral("></script>\r\n    <script");

WriteAttribute("src", Tuple.Create(" src=\"", 14563), Tuple.Create("\"", 14623)
, Tuple.Create(Tuple.Create("", 14569), Tuple.Create<System.Object, System.Int32>(Href("~/assets/vendors/general/chart.js/dist/Chart.bundle.js")
, 14569), false)
);

WriteLiteral(" type=\"text/javascript\"");

WriteLiteral("></script>\r\n    <script");

WriteAttribute("src", Tuple.Create(" src=\"", 14670), Tuple.Create("\"", 14771)
, Tuple.Create(Tuple.Create("", 14676), Tuple.Create<System.Object, System.Int32>(Href("~/assets/vendors/custom/vendors/bootstrap-session-timeout/dist/bootstrap-session-" +
"timeout.min.js")
, 14676), false)
);

WriteLiteral(" type=\"text/javascript\"");

WriteLiteral("></script>\r\n    <script");

WriteAttribute("src", Tuple.Create(" src=\"", 14818), Tuple.Create("\"", 14890)
, Tuple.Create(Tuple.Create("", 14824), Tuple.Create<System.Object, System.Int32>(Href("~/assets/vendors/custom/vendors/jquery-idletimer/idle-timer.min.js")
, 14824), false)
);

WriteLiteral(" type=\"text/javascript\"");

WriteLiteral("></script>\r\n    <script");

WriteAttribute("src", Tuple.Create(" src=\"", 14937), Tuple.Create("\"", 15001)
, Tuple.Create(Tuple.Create("", 14943), Tuple.Create<System.Object, System.Int32>(Href("~/assets/vendors/general/waypoints/lib/jquery.waypoints.js")
, 14943), false)
);

WriteLiteral(" type=\"text/javascript\"");

WriteLiteral("></script>\r\n    <script");

WriteAttribute("src", Tuple.Create(" src=\"", 15048), Tuple.Create("\"", 15108)
, Tuple.Create(Tuple.Create("", 15054), Tuple.Create<System.Object, System.Int32>(Href("~/assets/vendors/general/counterup/jquery.counterup.js")
, 15054), false)
);

WriteLiteral(" type=\"text/javascript\"");

WriteLiteral("></script>\r\n    <script");

WriteAttribute("src", Tuple.Create(" src=\"", 15155), Tuple.Create("\"", 15221)
, Tuple.Create(Tuple.Create("", 15161), Tuple.Create<System.Object, System.Int32>(Href("~/assets/vendors/general/es6-promise-polyfill/promise.min.js")
, 15161), false)
);

WriteLiteral(" type=\"text/javascript\"");

WriteLiteral("></script>\r\n    <script");

WriteAttribute("src", Tuple.Create(" src=\"", 15268), Tuple.Create("\"", 15334)
, Tuple.Create(Tuple.Create("", 15274), Tuple.Create<System.Object, System.Int32>(Href("~/assets/vendors/general/sweetalert2/dist/sweetalert2.min.js")
, 15274), false)
);

WriteLiteral(" type=\"text/javascript\"");

WriteLiteral("></script>\r\n    <script");

WriteAttribute("src", Tuple.Create(" src=\"", 15381), Tuple.Create("\"", 15441)
, Tuple.Create(Tuple.Create("", 15387), Tuple.Create<System.Object, System.Int32>(Href("~/assets/vendors/custom/js/vendors/sweetalert2.init.js")
, 15387), false)
);

WriteLiteral(" type=\"text/javascript\"");

WriteLiteral("></script>\r\n    <script");

WriteAttribute("src", Tuple.Create(" src=\"", 15488), Tuple.Create("\"", 15545)
, Tuple.Create(Tuple.Create("", 15494), Tuple.Create<System.Object, System.Int32>(Href("~/assets/vendors/general/jquery.repeater/src/lib.js")
, 15494), false)
);

WriteLiteral(" type=\"text/javascript\"");

WriteLiteral("></script>\r\n    <script");

WriteAttribute("src", Tuple.Create(" src=\"", 15592), Tuple.Create("\"", 15658)
, Tuple.Create(Tuple.Create("", 15598), Tuple.Create<System.Object, System.Int32>(Href("~/assets/vendors/general/jquery.repeater/src/jquery.input.js")
, 15598), false)
);

WriteLiteral(" type=\"text/javascript\"");

WriteLiteral("></script>\r\n    <script");

WriteAttribute("src", Tuple.Create(" src=\"", 15705), Tuple.Create("\"", 15767)
, Tuple.Create(Tuple.Create("", 15711), Tuple.Create<System.Object, System.Int32>(Href("~/assets/vendors/general/jquery.repeater/src/repeater.js")
, 15711), false)
);

WriteLiteral(" type=\"text/javascript\"");

WriteLiteral("></script>\r\n    <script");

WriteAttribute("src", Tuple.Create(" src=\"", 15814), Tuple.Create("\"", 15869)
, Tuple.Create(Tuple.Create("", 15820), Tuple.Create<System.Object, System.Int32>(Href("~/assets/vendors/general/dompurify/dist/purify.js")
, 15820), false)
);

WriteLiteral(" type=\"text/javascript\"");

WriteLiteral("></script>\r\n    <script");

WriteAttribute("src", Tuple.Create(" src=\"", 15916), Tuple.Create("\"", 15973)
, Tuple.Create(Tuple.Create("", 15922), Tuple.Create<System.Object, System.Int32>(Href("~/assets/vendors/custom/viewer/viewer-jquery.min.js")
, 15922), false)
);

WriteLiteral("></script>\r\n\r\n    <!--主题样式脚本 -->\r\n    <script");

WriteAttribute("src", Tuple.Create(" src=\"", 16019), Tuple.Create("\"", 16060)
, Tuple.Create(Tuple.Create("", 16025), Tuple.Create<System.Object, System.Int32>(Href("~/assets/js/demo1/scripts.bundle.js")
, 16025), false)
);

WriteLiteral(" type=\"text/javascript\"");

WriteLiteral("></script>\r\n\r\n\r\n    <!--登录页面脚本 -->\r\n    <script");

WriteAttribute("src", Tuple.Create(" src=\"", 16131), Tuple.Create("\"", 16183)
, Tuple.Create(Tuple.Create("", 16137), Tuple.Create<System.Object, System.Int32>(Href("~/assets/js/demo1/pages/login/login-general.js")
, 16137), false)
);

WriteLiteral(" type=\"text/javascript\"");

WriteLiteral("></script>\r\n\r\n\r\n    <!-- 添加导航点击后点亮事件 -->\r\n    <script");

WriteLiteral(" type=\"text/javascript\"");

WriteLiteral(">\r\n        $(\'.kt-menu__subnav .kt-menu__item\').click(function () {\r\n            " +
"$(\".kt-menu__item\").removeClass(\"kt-menu__item--active\");\r\n            $(this).a" +
"ddClass(\"kt-menu__item--active\");\r\n        });\r\n    </script>\r\n    <!--控件支持-->\r\n" +
"    <script>\r\n        $(function () {\r\n            $(\"input.chkSwitch\").bootstra" +
"pSwitch();\r\n            $(\'.form_datetime\').datetimepicker({\r\n                fo" +
"rmat: \"yyyy-mm-dd\",\r\n                language: \"zh-CN\",\r\n                todayBt" +
"n: true,\r\n                clearBtn: true,\r\n                todayHighlight: true," +
"\r\n                autoclose: true,\r\n                startView: 2,\r\n             " +
"   minView: 2,\r\n                forceParse: 0,\r\n                pickerPosition: " +
"\'bottom-left\'\r\n             });\r\n            $(\'.form_datepicker\').datetimepicke" +
"r({\r\n                format: \"yyyy-mm-dd HH:ii:ss\",\r\n                language: \"" +
"zh-CN\",\r\n                todayBtn: true,\r\n                clearBtn: true,\r\n     " +
"           todayHighlight: true,\r\n                autoclose: true,\r\n            " +
"    startView: 2,\r\n                minView: 2,\r\n                forceParse: 0,\r\n" +
"                pickerPosition: \'bottom-left\'\r\n            });\r\n            $(\'." +
"form_datetime_mm\').datetimepicker({\r\n                format: \"yyyy-mm\",\r\n       " +
"         language: \"zh-CN\",\r\n                todayBtn: true,\r\n                cl" +
"earBtn: true,\r\n                todayHighlight: true,\r\n                autoclose:" +
" true,\r\n                startView: 3,\r\n                minView: 3,\r\n            " +
"    forceParse: 0,\r\n                pickerPosition: \'bottom-left\'\r\n            }" +
");\r\n             $(\'.form_datetime_yyyy\').datetimepicker({\r\n                form" +
"at: \"yyyy-mm\",\r\n                language: \"zh-CN\",\r\n                todayBtn: tr" +
"ue,\r\n                clearBtn: true,\r\n                todayHighlight: true,\r\n   " +
"             autoclose: true,\r\n                startView: 4,\r\n                mi" +
"nView: 4,\r\n                forceParse: 0,\r\n                pickerPosition: \'bott" +
"om-left\'\r\n             });\r\n            toastr.options = {\r\n                \"clo" +
"seButton\": true,\r\n                \"debug\": false,\r\n                \"newestOnTop\"" +
": false,\r\n                \"progressBar\": true,\r\n                \"positionClass\":" +
" \"toast-top-right\",\r\n                \"preventDuplicates\": false,\r\n              " +
"  \"onclick\": null,\r\n                \"showDuration\": \"300\",\r\n                \"hid" +
"eDuration\": \"1000\",\r\n                \"timeOut\": \"5000\",\r\n                \"extend" +
"edTimeOut\": \"1000\",\r\n                \"showEasing\": \"swing\",\r\n                \"hi" +
"deEasing\": \"linear\",\r\n                \"showMethod\": \"fadeIn\",\r\n                \"" +
"hideMethod\": \"fadeOut\"\r\n            };\r\n\r\n            ");

WriteLiteral(@"
            $('tr').dblclick(function () {
                var $this = $(this);
                var row = $this.closest(""tr"");
                //优先加载侧边栏
                var dblp = row.find('.dblclickpanel');
                if (dblp.length > 0) {
                   var id = $(dblp).data(""id"");
                    var url = $(dblp).data(""url"");
                    $.ajax({
                        url: url,
                        data: { id: id },
                        success: function (data) {
                            $(""#kt_quick_panel_toggler_btn"").trigger(""click"");
                            $(""#kt_quick_panel_content"").html(data);
                            //$(""#kt_quick_panel"").css(""opacity"",1);
                            console.log(Date.now());
                        }
                    });
                    return;
                }
                //编辑页面
                var findcell = row.find('.editcell');
                if (findcell.length > 0) {
                    window.location.href = findcell.attr(""href"");
                }


            });
        });
    </script>

    <!--自定义脚本-->
    <script");

WriteAttribute("src", Tuple.Create(" src=\"", 20298), Tuple.Create("\"", 20320)
, Tuple.Create(Tuple.Create("", 20304), Tuple.Create<System.Object, System.Int32>(Href("~/assets/cube.js")
, 20304), false)
);

WriteLiteral("></script>\r\n");

WriteLiteral("    ");

            
            #line 361 "..\..\Views\Shared\_Ace_Layout.cshtml"
Write(RenderSection("scripts", required: false));

            
            #line default
            #line hidden
WriteLiteral("\r\n</body>\r\n</html>\r\n");

        }
    }
}
#pragma warning restore 1591
