#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Optimization;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using MUI.WebSite;
    
    #line 1 "..\..\Views\Shared\_Form_Item.cshtml"
    using NewLife;
    
    #line default
    #line hidden
    using NewLife.Cube;
    using NewLife.Reflection;
    using NewLife.Web;
    
    #line 2 "..\..\Views\Shared\_Form_Item.cshtml"
    using XCode;
    
    #line default
    #line hidden
    
    #line 3 "..\..\Views\Shared\_Form_Item.cshtml"
    using XCode.Configuration;
    
    #line default
    #line hidden
    using XCode.Membership;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Shared/_Form_Item.cshtml")]
    public partial class _Views_Shared__Form_Item_cshtml : System.Web.Mvc.WebViewPage<dynamic>
    {
        public _Views_Shared__Form_Item_cshtml()
        {
        }
        public override void Execute()
        {
WriteLiteral("\r\n");

            
            #line 5 "..\..\Views\Shared\_Form_Item.cshtml"
  
    var pair = Model as Pair;
    var entity = pair.First as IEntity;
    var item = pair.Second as FieldItem;

    var err = 0;
    ModelState st = null;
    if (ViewData.ModelState.TryGetValue(item.Name, out st) && st != null) { err = st.Errors.Count; }
    var des = item.Description.TrimStart(item.DisplayName).TrimStart(",", ".", "，", "。");

            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n\r\n\r\n<label");

WriteLiteral(" class=\"col-3 col-form-label\"");

WriteLiteral(">\r\n");

WriteLiteral("    ");

            
            #line 19 "..\..\Views\Shared\_Form_Item.cshtml"
Write(item.DisplayName);

            
            #line default
            #line hidden
WriteLiteral("\r\n");

            
            #line 20 "..\..\Views\Shared\_Form_Item.cshtml"
    
            
            #line default
            #line hidden
            
            #line 20 "..\..\Views\Shared\_Form_Item.cshtml"
     if (!des.IsNullOrEmpty())
    {
        var ds = item.Description.Split("。");

            
            #line default
            #line hidden
WriteLiteral("        <i");

WriteLiteral(" class=\"la la-question-circle\"");

WriteLiteral(" data-toggle=\"kt-tooltip\"");

WriteLiteral(" data-placement=\"top\"");

WriteLiteral(" title=\"\"");

WriteLiteral(" data-original-title=\"");

            
            #line 23 "..\..\Views\Shared\_Form_Item.cshtml"
                                                                                                                 Write(ds.Length>1?ds[1]:"");

            
            #line default
            #line hidden
WriteLiteral("\"");

WriteLiteral("></i>\r\n");

            
            #line 24 "..\..\Views\Shared\_Form_Item.cshtml"
    }

            
            #line default
            #line hidden
WriteLiteral("</label>\r\n<div");

WriteLiteral(" class=\"col-9\"");

WriteLiteral(">\r\n    <div");

WriteLiteral(" class=\"input-group\"");

WriteLiteral(">\r\n");

WriteLiteral("        ");

            
            #line 28 "..\..\Views\Shared\_Form_Item.cshtml"
   Write(Html.ForEditorX(item, entity, new { @class = "form-control" }.ToDictionary()));

            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n\r\n    </div>\r\n\r\n</div>");

        }
    }
}
#pragma warning restore 1591
