#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Optimization;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using MUI.WebSite;
    using NewLife;
    using NewLife.Cube;
    using NewLife.Reflection;
    using NewLife.Web;
    
    #line 2 "..\..\Views\Shared\_Form_TaskView_Tags.cshtml"
    using XCode;
    
    #line default
    #line hidden
    
    #line 3 "..\..\Views\Shared\_Form_TaskView_Tags.cshtml"
    using XCode.Configuration;
    
    #line default
    #line hidden
    using XCode.Membership;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Shared/_Form_TaskView_Tags.cshtml")]
    public partial class _Views_Shared__Form_TaskView_Tags_cshtml : System.Web.Mvc.WebViewPage<dynamic>
    {
        public _Views_Shared__Form_TaskView_Tags_cshtml()
        {
        }
        public override void Execute()
        {
WriteLiteral("\r\n");

            
            #line 4 "..\..\Views\Shared\_Form_TaskView_Tags.cshtml"
  
    var entity = Model as IEntity;
    var tags = (entity["Tags"] as String).Split(",", ";", "|"); // 分隔标签
 
            
            #line default
            #line hidden
WriteLiteral("\r\n<div>标签</div>\r\n<div");

WriteLiteral(" class=\"tags-content\"");

WriteLiteral(">\r\n    <div");

WriteLiteral(" class=\"tags-box flex flex-wrap align-items-center\"");

WriteLiteral(" style=\"margin-top: calc(1.25rem - 5px);\"");

WriteLiteral(">\r\n");

            
            #line 11 "..\..\Views\Shared\_Form_TaskView_Tags.cshtml"
        
            
            #line default
            #line hidden
            
            #line 11 "..\..\Views\Shared\_Form_TaskView_Tags.cshtml"
         foreach (var tag in tags)
        {

            
            #line default
            #line hidden
WriteLiteral("            <div");

WriteLiteral(" class=\"kt-margin-r-5 kt-margin-t-5\"");

WriteLiteral(">\r\n                <span");

WriteLiteral(" class=\"btn btn-secondary kt-padding-l-10 kt-padding-r-10 kt-padding-t-5 kt-paddi" +
"ng-b-5\"");

WriteLiteral(">");

            
            #line 14 "..\..\Views\Shared\_Form_TaskView_Tags.cshtml"
                                                                                                         Write(tag);

            
            #line default
            #line hidden
WriteLiteral("</span>\r\n            </div>\r\n");

            
            #line 16 "..\..\Views\Shared\_Form_TaskView_Tags.cshtml"
        }

            
            #line default
            #line hidden
WriteLiteral("        <div");

WriteLiteral(" class=\"kt-margin-r-5 kt-margin-t-5\"");

WriteLiteral(">\r\n            <div");

WriteLiteral(" class=\"btn btn-primary kt-padding-l-10 kt-padding-r-10 kt-padding-t-5 kt-padding" +
"-b-5 tags-change\"");

WriteLiteral(">修改标签...</div>\r\n        </div>\r\n    </div>\r\n    <div");

WriteLiteral(" class=\"margin-top-125\"");

WriteLiteral(" style=\"display: none;\"");

WriteLiteral(">\r\n        <textarea");

WriteLiteral(" class=\"form-control\"");

WriteLiteral(" rows=\"3\"");

WriteLiteral(" placeholder=\"标签之间用英文“,”“;”“|”隔开\"");

WriteLiteral("></textarea>\r\n        <div");

WriteLiteral(" class=\"flex justify-content-end align-items-center kt-margin-t-10 kt-padding-r-1" +
"0\"");

WriteLiteral(">\r\n            <input");

WriteLiteral(" type=\"button\"");

WriteLiteral(" class=\"btn btn-secondary kt-padding-l-10 kt-padding-r-10 kt-padding-t-5 kt-paddi" +
"ng-b-5 kt-margin-r-10 tags-change\"");

WriteLiteral(" value=\"取消\"");

WriteLiteral(">\r\n            <input");

WriteLiteral(" type=\"button\"");

WriteLiteral(" class=\"btn btn-primary kt-padding-l-10 kt-padding-r-10 kt-padding-t-5 kt-padding" +
"-b-5 tags-sunmit\"");

WriteLiteral(" value=\"确认\"");

WriteLiteral(">\r\n        </div>\r\n    </div>\r\n</div>\r\n\r\n<script");

WriteLiteral(" type=\"text/javascript\"");

WriteLiteral(@">
    $('.tags-change').click(function () {
        var textarea = $(this).parents('.tags-content').find('textarea');
        $(this).parent().parent().hide();
        $(this).parent().parent().siblings().show();
        var spans = $(this).parents('.tags-content').find('span');
        var tags = [];
        spans.each(function (index) {
            if (index < spans.length - 1) {
                tags += $(this).html() + ',';
            } else {
                tags += $(this).html();
            }            
        })
        textarea.val(tags);
    });
    $('.tags-sunmit').click(function () {
        var textarea = $(this).parents('.tags-content').find('textarea').val();
        var tagsNew = textarea.split(/,|;|\|/);
        var tagsBox = $('.tags-box');
        var tags = tagsBox.find('span').parent();
        tags.remove();
        for (let i = tagsNew.length-1; i >=0; i--) {
            var tag = tagsNew[i].replace(/(^\s*)|(\s*$)/g, """")
            console.log(tag);
            if (tag != '') {
                tagsBox.prepend('<div class=""kt-margin-r-5 kt-margin-t-5""><span class=""btn btn-secondary kt-padding-l-10 kt-padding-r-10 kt-padding-t-5 kt-padding-b-5"">' + tagsNew[i].replace(/(^\s*)|(\s*$)/g, """") + '</span></div>');
            }             
        }
        $(this).parent().parent().hide();
        $(this).parent().parent().siblings().show();
    });
</script>

        ");

        }
    }
}
#pragma warning restore 1591
