#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Optimization;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using MUI.WebSite;
    using NewLife;
    using NewLife.Cube;
    using NewLife.Reflection;
    using NewLife.Web;
    using XCode;
    using XCode.Membership;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Shared/_Form_TaskView_Attachment.cshtml")]
    public partial class _Views_Shared__Form_TaskView_Attachment_cshtml : System.Web.Mvc.WebViewPage<dynamic>
    {
        public _Views_Shared__Form_TaskView_Attachment_cshtml()
        {
        }
        public override void Execute()
        {
WriteLiteral("\r\n\r\n");

            
            #line 3 "..\..\Views\Shared\_Form_TaskView_Attachment.cshtml"
  
    var entity = Model as IEntity;
    var fact = EntityFactory.CreateOperate(entity.GetType());
    var id = entity[fact.Unique.Name];

            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n<div");

WriteLiteral(" class=\"flex align-items-center justify-content-between margin-top-125\"");

WriteLiteral(">\r\n    <div>附件</div>\r\n    <div");

WriteLiteral(" class=\"file-box flex align-items-center\"");

WriteLiteral(">\r\n        <form");

WriteLiteral(" action=\"\"");

WriteLiteral(" method=\"post\"");

WriteLiteral(" enctype=\"multipart/form-data\"");

WriteLiteral(">\r\n            <input");

WriteLiteral(" type=\'text\'");

WriteLiteral(" name=\'textfield\'");

WriteLiteral(" id=\'textfield\'");

WriteLiteral(" class=\'txt kt-margin-r-5\'");

WriteLiteral(" readonly />\r\n            <input");

WriteLiteral(" type=\'button\'");

WriteLiteral(" class=\'cube-file kt-margin-r-5\'");

WriteLiteral(" value=\'浏览...\'");

WriteLiteral(" />\r\n            <input");

WriteLiteral(" id=\"submit_upload\"");

WriteLiteral(" class=\"cube-file\"");

WriteLiteral(" type=\"submit\"");

WriteLiteral(" value=\"上传\"");

WriteLiteral(" disabled=\"disabled\"");

WriteLiteral(" />\r\n            <input");

WriteLiteral(" type=\"file\"");

WriteLiteral(" name=\"input\"");

WriteLiteral(" class=\"file\"");

WriteLiteral(" id=\"input\"");

WriteLiteral(" multiple=\"multiple\"");

WriteLiteral(" size=\"28\"");

WriteLiteral(" />\r\n        </form>\r\n    </div>\r\n</div>\r\n<div");

WriteLiteral(" class=\"files-content margin-top-125\"");

WriteLiteral(">\r\n    <div");

WriteLiteral(" class=\"file-list flex align-items-center justify-content-between kt-padding-l-10" +
" kt-padding-r-10\"");

WriteLiteral(">\r\n        <div");

WriteLiteral(" class=\"cube-flex-1 kt-margin-r-5\"");

WriteLiteral(">文件名字不要太长文件名字不要太长文件名字不要太长</div>\r\n        <div");

WriteLiteral(" class=\"cube-flex-none\"");

WriteLiteral(">删除</div>\r\n    </div>\r\n    <div");

WriteLiteral(" class=\"file-list flex align-items-center justify-content-between kt-padding-l-10" +
" kt-padding-r-10\"");

WriteLiteral(">\r\n        <div");

WriteLiteral(" class=\"cube-flex-1 kt-margin-r-5\"");

WriteLiteral(">文件名字不要太长文件名字不要太长文件名字不要太长</div>\r\n        <div");

WriteLiteral(" class=\"cube-flex-none\"");

WriteLiteral(">删除</div>\r\n    </div>\r\n    <div");

WriteLiteral(" class=\"file-list flex align-items-center justify-content-between kt-padding-l-10" +
" kt-padding-r-10\"");

WriteLiteral(">\r\n        <div");

WriteLiteral(" class=\"cube-flex-1 kt-margin-r-5\"");

WriteLiteral(">文件名字不要太长文件名字不要太长文件名字不要太长</div>\r\n        <div");

WriteLiteral(" class=\"cube-flex-none\"");

WriteLiteral(">删除</div>\r\n    </div>\r\n</div>\r\n<script");

WriteLiteral(" type=\"text/javascript\"");

WriteLiteral(@">
    var selectedFileList = []; //已选文件列表
    var paramTaskId = """"; //请求参数
    var succsessCount = 0; //上传成功文件个数
    var errorCount = 0; //上传失败文件个数
    var values = [];
    $(function () {
        $(""#input"").bind(""change"", function () { //绑定文件选择事件
            var files = $(""#input"").prop(""files"");
            $.each(files, function (index, item) {
                if (values.length > 0) { //文件去重
                    var count = 0;
                    $.each(values, function (index1, item1) {
                        if (item.name == item1.innerText) {
                            count++;
                        }
                    });
                    if (count == 0) {
                        values.push(item.name);
                        selectedFileList.push(item);
                        $(""#submit_upload"").attr(""disabled"", false);
                    }
                } else {
                    values.push(item.name);
                    selectedFileList.push(item);
                    $(""#submit_upload"").attr(""disabled"", false);
                }
            });
            console.log(values);
            console.log(selectedFileList);
            $(""#textfield"").val(values)
        });
        $(""submit_upload"").on(click,function () {
            $.ajax({
                url: ""/BaseEntity/UploadAttachment"",
                type: ""post"",
                data: JSON.stringify({
                    ID:");

            
            #line 71 "..\..\Views\Shared\_Form_TaskView_Attachment.cshtml"
                  Write(id);

            
            #line default
            #line hidden
WriteLiteral(@",
                    Files: values
                }),
                cache: true,
                contentType: 'application/json',
                async: true,
                processData: false,
                success: function () {
                    console.log(""上传失败"");

                }
            });
        })
    });
    //判断文件是否超过限制大小
    function checkFileLength(fileLen) {
        if (fileLen > 4194304) {
            $.messager.alert(""提示"", ""上传文件大小不能超过4M"", ""error"");
            return false;
        }
        return true;
    }
    //上传文件
</script>
");

        }
    }
}
#pragma warning restore 1591
