#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Optimization;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using MUI.WebSite;
    using NewLife;
    
    #line 1 "..\..\Views\Shared\_Form_Footer.cshtml"
    using NewLife.Cube;
    
    #line default
    #line hidden
    using NewLife.Reflection;
    using NewLife.Web;
    using XCode;
    
    #line 2 "..\..\Views\Shared\_Form_Footer.cshtml"
    using XCode.Configuration;
    
    #line default
    #line hidden
    using XCode.Membership;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Shared/_Form_Footer.cshtml")]
    public partial class _Views_Shared__Form_Footer_cshtml : System.Web.Mvc.WebViewPage<dynamic>
    {
        public _Views_Shared__Form_Footer_cshtml()
        {
        }
        public override void Execute()
        {
            
            #line 3 "..\..\Views\Shared\_Form_Footer.cshtml"
  
    /**/

    var entity = Model as IEntity;
    var fact = EntityFactory.CreateOperate(entity.GetType());
    var fields = ViewBag.Fields as IList<FieldItem>;

    var set = NewLife.Cube.Setting.Current;
    var cls = set.FormGroupClass;
    if (cls.IsNullOrEmpty()) { cls = "form-group col-12 col-sm-6 col-lg-4"; }

    var total = 12;
    var label = 3;
    var span = 4;
    var input = total - label - span;

    var cid = fact.Table.FindByName("CreateUserID") as FieldItem;
    var uid = fact.Table.FindByName("UpdateUserID") as FieldItem;
    var cip = fact.Table.FindByName("CreateIP") as FieldItem;
    var uip = fact.Table.FindByName("UpdateIP") as FieldItem;
    var remark = fact.Table.FindByName("Remark") as FieldItem;
    if (remark == null) { remark = fact.Table.FindByName("Description"); }

    var hasUser = cid != null || uid != null;
    if (hasUser && ViewData["Provider"] == null) { ViewData["Provider"] = ManageProvider.Provider; }
    var provider = ViewData["Provider"] as IManageProvider;

    var set1 = NewLife.Cube.Setting.Current;
    var cls1 = set.FormGroupClass;
    var s = Convert.ToInt32(cls1.Split('-').Last());
    var r = (Decimal)s * Math.Floor((Decimal)12 / (Decimal)s) * (Decimal)100 / 12;
    var l = (Decimal)s * (Decimal)20 / 12;

            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n");

            
            #line 37 "..\..\Views\Shared\_Form_Footer.cshtml"
 if (cid != null && !fields.Contains(cid))
{
    var user = fact.Table.FindByName("CreateUserID") as FieldItem;
    var time = fact.Table.FindByName("CreateTime") as FieldItem;

            
            #line default
            #line hidden
WriteLiteral("    <div");

WriteLiteral(" class=\"form-group flex align-items-center\"");

WriteAttribute("style", Tuple.Create(" style=\"", 1599), Tuple.Create("\"", 1631)
, Tuple.Create(Tuple.Create("", 1607), Tuple.Create("width:", 1607), true)
            
            #line 41 "..\..\Views\Shared\_Form_Footer.cshtml"
, Tuple.Create(Tuple.Create("", 1613), Tuple.Create<System.Object, System.Int32>(r
            
            #line default
            #line hidden
, 1613), false)
, Tuple.Create(Tuple.Create("", 1615), Tuple.Create("%;", 1615), true)
, Tuple.Create(Tuple.Create(" ", 1617), Tuple.Create("height:", 1618), true)
, Tuple.Create(Tuple.Create(" ", 1625), Tuple.Create("3rem;", 1626), true)
);

WriteLiteral(">\r\n        <div");

WriteLiteral(" class=\"item-label\"");

WriteAttribute("style", Tuple.Create(" style=\"", 1666), Tuple.Create("\"", 1684)
, Tuple.Create(Tuple.Create("", 1674), Tuple.Create("width:", 1674), true)
            
            #line 42 "..\..\Views\Shared\_Form_Footer.cshtml"
, Tuple.Create(Tuple.Create("", 1680), Tuple.Create<System.Object, System.Int32>(l
            
            #line default
            #line hidden
, 1680), false)
, Tuple.Create(Tuple.Create("", 1682), Tuple.Create("%;", 1682), true)
);

WriteLiteral(">\r\n            <label");

WriteLiteral(" class=\"control-label kt-margin-r-5\"");

WriteLiteral(">创建</label>\r\n            <div");

WriteLiteral(" class=\"kt-margin-l-5 kt-margin-r-5 toggle-show\"");

WriteLiteral(" style=\"width:18px;\"");

WriteLiteral("></div>\r\n        </div>\r\n        <div");

WriteLiteral(" class=\"flex align-items-center flex-grow-1\"");

WriteLiteral(">\r\n");

            
            #line 47 "..\..\Views\Shared\_Form_Footer.cshtml"
            
            
            #line default
            #line hidden
            
            #line 47 "..\..\Views\Shared\_Form_Footer.cshtml"
             if (user != null)
            {
                var val = entity[user.Name];

            
            #line default
            #line hidden
WriteLiteral("                <span");

WriteLiteral(" class=\"text-primary\"");

WriteAttribute("title", Tuple.Create(" title=\"", 2058), Tuple.Create("\"", 2070)
            
            #line 50 "..\..\Views\Shared\_Form_Footer.cshtml"
, Tuple.Create(Tuple.Create("", 2066), Tuple.Create<System.Object, System.Int32>(val
            
            #line default
            #line hidden
, 2066), false)
);

WriteLiteral(">");

            
            #line 50 "..\..\Views\Shared\_Form_Footer.cshtml"
                                                   Write(provider.FindByID(val));

            
            #line default
            #line hidden
WriteLiteral("</span>\r\n");

            
            #line 51 "..\..\Views\Shared\_Form_Footer.cshtml"
            }

            
            #line default
            #line hidden
WriteLiteral("            ");

            
            #line 52 "..\..\Views\Shared\_Form_Footer.cshtml"
             if (time != null)
            {
                var dt = (DateTime)entity[time.Name];

            
            #line default
            #line hidden
WriteLiteral("                <span");

WriteLiteral(" class=\"text-success\"");

WriteLiteral(">");

            
            #line 55 "..\..\Views\Shared\_Form_Footer.cshtml"
                                      Write(dt.ToFullString());

            
            #line default
            #line hidden
WriteLiteral("</span>\r\n");

            
            #line 56 "..\..\Views\Shared\_Form_Footer.cshtml"
            }

            
            #line default
            #line hidden
WriteLiteral("            ");

            
            #line 57 "..\..\Views\Shared\_Form_Footer.cshtml"
             if (cip != null)
            {
                var ip = entity[cip.Name] + "";

            
            #line default
            #line hidden
WriteLiteral("                <span");

WriteLiteral(" class=\"text-primary\"");

WriteLiteral(">");

            
            #line 60 "..\..\Views\Shared\_Form_Footer.cshtml"
                                      Write(ip);

            
            #line default
            #line hidden
WriteLiteral(" ");

            
            #line 60 "..\..\Views\Shared\_Form_Footer.cshtml"
                                          Write(ip.IPToAddress());

            
            #line default
            #line hidden
WriteLiteral("</span>\r\n");

            
            #line 61 "..\..\Views\Shared\_Form_Footer.cshtml"
            }

            
            #line default
            #line hidden
WriteLiteral("        </div>\r\n    </div>\r\n");

            
            #line 64 "..\..\Views\Shared\_Form_Footer.cshtml"
}

            
            #line default
            #line hidden
            
            #line 65 "..\..\Views\Shared\_Form_Footer.cshtml"
 if (uid != null && !fields.Contains(uid))
{
    var user = fact.Table.FindByName("UpdateUserID") as FieldItem;
    var time = fact.Table.FindByName("UpdateTime") as FieldItem;

            
            #line default
            #line hidden
WriteLiteral("    <div");

WriteLiteral(" class=\"form-group flex align-items-center\"");

WriteAttribute("style", Tuple.Create(" style=\"", 2752), Tuple.Create("\"", 2784)
, Tuple.Create(Tuple.Create("", 2760), Tuple.Create("width:", 2760), true)
            
            #line 69 "..\..\Views\Shared\_Form_Footer.cshtml"
, Tuple.Create(Tuple.Create("", 2766), Tuple.Create<System.Object, System.Int32>(r
            
            #line default
            #line hidden
, 2766), false)
, Tuple.Create(Tuple.Create("", 2768), Tuple.Create("%;", 2768), true)
, Tuple.Create(Tuple.Create(" ", 2770), Tuple.Create("height:", 2771), true)
, Tuple.Create(Tuple.Create(" ", 2778), Tuple.Create("3rem;", 2779), true)
);

WriteLiteral(">\r\n        <div");

WriteLiteral(" class=\"item-label\"");

WriteAttribute("style", Tuple.Create(" style=\"", 2819), Tuple.Create("\"", 2837)
, Tuple.Create(Tuple.Create("", 2827), Tuple.Create("width:", 2827), true)
            
            #line 70 "..\..\Views\Shared\_Form_Footer.cshtml"
, Tuple.Create(Tuple.Create("", 2833), Tuple.Create<System.Object, System.Int32>(l
            
            #line default
            #line hidden
, 2833), false)
, Tuple.Create(Tuple.Create("", 2835), Tuple.Create("%;", 2835), true)
);

WriteLiteral(">\r\n            <label");

WriteLiteral(" class=\"control-label kt-margin-r-5\"");

WriteLiteral(">更新</label>\r\n            <div");

WriteLiteral(" class=\"kt-margin-l-5 kt-margin-r-5 toggle-show\"");

WriteLiteral(" style=\"width:18px;\"");

WriteLiteral("></div>\r\n        </div>\r\n        <div");

WriteLiteral(" class=\"flex align-items-center flex-grow-1\"");

WriteLiteral(">\r\n");

            
            #line 75 "..\..\Views\Shared\_Form_Footer.cshtml"
            
            
            #line default
            #line hidden
            
            #line 75 "..\..\Views\Shared\_Form_Footer.cshtml"
             if (user != null)
            {
                var val = entity[user.Name];

            
            #line default
            #line hidden
WriteLiteral("                <span");

WriteLiteral(" class=\"text-primary\"");

WriteAttribute("title", Tuple.Create(" title=\"", 3211), Tuple.Create("\"", 3223)
            
            #line 78 "..\..\Views\Shared\_Form_Footer.cshtml"
, Tuple.Create(Tuple.Create("", 3219), Tuple.Create<System.Object, System.Int32>(val
            
            #line default
            #line hidden
, 3219), false)
);

WriteLiteral(">");

            
            #line 78 "..\..\Views\Shared\_Form_Footer.cshtml"
                                                   Write(provider.FindByID(val));

            
            #line default
            #line hidden
WriteLiteral("</span>\r\n");

            
            #line 79 "..\..\Views\Shared\_Form_Footer.cshtml"
            }

            
            #line default
            #line hidden
WriteLiteral("            ");

            
            #line 80 "..\..\Views\Shared\_Form_Footer.cshtml"
             if (time != null)
            {
                var dt = (DateTime)entity[time.Name];

            
            #line default
            #line hidden
WriteLiteral("                <span");

WriteLiteral(" class=\"text-success\"");

WriteLiteral(">");

            
            #line 83 "..\..\Views\Shared\_Form_Footer.cshtml"
                                      Write(dt.ToFullString());

            
            #line default
            #line hidden
WriteLiteral("</span>\r\n");

            
            #line 84 "..\..\Views\Shared\_Form_Footer.cshtml"
            }

            
            #line default
            #line hidden
WriteLiteral("            ");

            
            #line 85 "..\..\Views\Shared\_Form_Footer.cshtml"
             if (uip != null)
            {
                var ip = entity[uip.Name] + "";

            
            #line default
            #line hidden
WriteLiteral("                <span");

WriteLiteral(" class=\"text-primary\"");

WriteLiteral(">");

            
            #line 88 "..\..\Views\Shared\_Form_Footer.cshtml"
                                      Write(ip);

            
            #line default
            #line hidden
WriteLiteral(" ");

            
            #line 88 "..\..\Views\Shared\_Form_Footer.cshtml"
                                          Write(ip.IPToAddress());

            
            #line default
            #line hidden
WriteLiteral("</span>\r\n");

            
            #line 89 "..\..\Views\Shared\_Form_Footer.cshtml"
            }

            
            #line default
            #line hidden
WriteLiteral("        </div>\r\n    </div>\r\n");

            
            #line 92 "..\..\Views\Shared\_Form_Footer.cshtml"
}

            
            #line default
            #line hidden
            
            #line 93 "..\..\Views\Shared\_Form_Footer.cshtml"
 if (remark != null && !fields.Contains(remark))
{

            
            #line default
            #line hidden
WriteLiteral("    <div");

WriteLiteral(" class=\"form-group flex kt-margin-0\"");

WriteAttribute("style", Tuple.Create(" style=\"", 3770), Tuple.Create("\"", 3788)
, Tuple.Create(Tuple.Create("", 3778), Tuple.Create("width:", 3778), true)
            
            #line 95 "..\..\Views\Shared\_Form_Footer.cshtml"
, Tuple.Create(Tuple.Create("", 3784), Tuple.Create<System.Object, System.Int32>(r
            
            #line default
            #line hidden
, 3784), false)
, Tuple.Create(Tuple.Create("", 3786), Tuple.Create("%;", 3786), true)
);

WriteLiteral(">\r\n        <div");

WriteLiteral(" class=\"item-label\"");

WriteAttribute("style", Tuple.Create(" style=\"", 3823), Tuple.Create("\"", 3855)
, Tuple.Create(Tuple.Create("", 3831), Tuple.Create("width:", 3831), true)
            
            #line 96 "..\..\Views\Shared\_Form_Footer.cshtml"
, Tuple.Create(Tuple.Create("", 3837), Tuple.Create<System.Object, System.Int32>(l
            
            #line default
            #line hidden
, 3837), false)
, Tuple.Create(Tuple.Create("", 3839), Tuple.Create("%;", 3839), true)
, Tuple.Create(Tuple.Create(" ", 3841), Tuple.Create("height:", 3842), true)
, Tuple.Create(Tuple.Create(" ", 3849), Tuple.Create("3rem;", 3850), true)
);

WriteLiteral(">\r\n            <label");

WriteLiteral(" class=\"control-label kt-margin-r-5\"");

WriteLiteral(">");

            
            #line 97 "..\..\Views\Shared\_Form_Footer.cshtml"
                                                  Write(remark.DisplayName);

            
            #line default
            #line hidden
WriteLiteral("</label>\r\n            <div");

WriteLiteral(" class=\"kt-margin-l-5 kt-margin-r-5 toggle-show\"");

WriteLiteral(" style=\"width:18px;\"");

WriteLiteral("></div>\r\n        </div>\r\n        <div");

WriteLiteral(" class=\"flex align-items-center flex-grow-1\"");

WriteLiteral(">\r\n");

WriteLiteral("            ");

            
            #line 101 "..\..\Views\Shared\_Form_Footer.cshtml"
       Write(Html.ForStringX(remark.Name, (String)entity[remark.Name], -1));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("            ");

            
            #line 102 "..\..\Views\Shared\_Form_Footer.cshtml"
       Write(Html.ForDescriptionX(remark));

            
            #line default
            #line hidden
WriteLiteral("\r\n        </div>\r\n    </div>\r\n");

            
            #line 105 "..\..\Views\Shared\_Form_Footer.cshtml"
}



            
            #line default
            #line hidden
            
            #line 125 "..\..\Views\Shared\_Form_Footer.cshtml"
           
            
            #line default
            #line hidden
        }
    }
}
#pragma warning restore 1591
