#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Optimization;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using MUI.WebSite;
    using NewLife;
    using NewLife.Cube;
    using NewLife.Reflection;
    using NewLife.Web;
    
    #line 2 "..\..\Views\Shared\_Form_TaskView.cshtml"
    using XCode;
    
    #line default
    #line hidden
    
    #line 3 "..\..\Views\Shared\_Form_TaskView.cshtml"
    using XCode.Configuration;
    
    #line default
    #line hidden
    using XCode.Membership;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Shared/_Form_TaskView.cshtml")]
    public partial class _Views_Shared__Form_TaskView_cshtml : System.Web.Mvc.WebViewPage<dynamic>
    {
        public _Views_Shared__Form_TaskView_cshtml()
        {
        }
        public override void Execute()
        {
WriteLiteral("\r\n");

            
            #line 4 "..\..\Views\Shared\_Form_TaskView.cshtml"
  
    var entity = Model as IEntity;
    var IsNew = entity.IsNullKey;
    var fields = entity.GetType().AsFactory().AllFields; // 通过实体工厂获取所有字段
    //var hasAttachment = entity.GetType().GetCustomAttributes(typeof(AttachmentAttribute), true).Length > 0;

            
            #line default
            #line hidden
WriteLiteral("\r\n<style>\r\n    .margin-top-125 {\r\n        margin-top: 1.25rem;\r\n    }\r\n    /*附件列表" +
"*/\r\n    .file-box {\r\n        position: relative;\r\n        width: 330px\r\n    }\r\n\r" +
"\n    .txt {\r\n        height: 24px;\r\n        border: 1px solid #cdcdcd;\r\n        " +
"width: 180px;\r\n    }\r\n\r\n    .cube-file {\r\n        background-color: #FFF;\r\n     " +
"   border: 1px solid #CDCDCD;\r\n        height: 24px;\r\n        width: 70px;\r\n    " +
"    line-height: 24px;\r\n    }\r\n\r\n    .file {\r\n        position: absolute;\r\n     " +
"   top: 50%;\r\n        left: 185px;\r\n        height: 24px;\r\n        filter: alpha" +
"(opacity:0);\r\n        opacity: 0;\r\n        width: 70px;\r\n        margin-top: -12" +
"px;\r\n    }\r\n\r\n    .files-content {\r\n        width: 100%;\r\n        background-col" +
"or: #fbfbfb;\r\n        border: 1px solid #eee;\r\n    }\r\n\r\n    .file-list {\r\n      " +
"  border-top: 1px solid #eee;\r\n        height: 2.5rem;\r\n    }\r\n\r\n        .file-l" +
"ist:first-child {\r\n            border-top: 0;\r\n        }\r\n    /* 地图容器 */\r\n    .c" +
"ube-map-container, #allmap {\r\n        width: 100%;\r\n        height: 250px;\r\n    " +
"}\r\n\r\n    /* 地图定位及搜索控件 */\r\n    .cube-map-search-box {\r\n        position: absolute" +
";\r\n        top: 10px;\r\n        left: 0;\r\n        right: 0;\r\n        z-index: 999" +
"9;\r\n        display: flex;\r\n        height: 30px;\r\n        align-items: center;\r" +
"\n        justify-content: center;\r\n    }\r\n\r\n    .anchorBL,\r\n    .BMap_cpyCtrl.BM" +
"ap_noprint.anchorBL,\r\n    .BMap_stdMpCtrl.BMap_stdMpType0.BMap_noprint.anchorTL " +
"{\r\n        display: none;\r\n    }\r\n\r\n    .BMap_noprint.anchorBL {\r\n        displa" +
"y: block;\r\n    }\r\n    /*滚动条*/\r\n    .scrollbar {\r\n        width: 30px;\r\n        h" +
"eight: 300px;\r\n        margin: 0 auto;\r\n    }\r\n\r\n    .test-5::-webkit-scrollbar " +
"{ /*滚动条整体样式*/\r\n        width: 5px; /*高宽分别对应横竖滚动条的尺寸*/\r\n        height: 1px;\r\n   " +
" }\r\n\r\n    .test-5::-webkit-scrollbar-thumb { /*滚动条里面小方块*/\r\n        border-radius" +
": 10px;\r\n        background-color: #c1c1c1;\r\n        /*background-color: #F90;\r\n" +
"        background-image: -webkit-linear-gradient(45deg, rgba(255, 255, 255, .2)" +
" 25%, transparent 25%, transparent 50%, rgba(255, 255, 255, .2) 50%, rgba(255, 2" +
"55, 255, .2) 75%, transparent 75%, transparent);*/\r\n    }\r\n\r\n    .test-5::-webki" +
"t-scrollbar-track { /*滚动条里面轨道*/\r\n        -webkit-box-shadow: inset 0 0 5px rgba(" +
"0,0,0,0.2);\r\n        /*border-radius: 10px;*/\r\n        background: #EDEDED;\r\n   " +
" }\r\n</style>\r\n<div");

WriteLiteral(" class=\"modal fade\"");

WriteLiteral(" id=\"kt_modal_1\"");

WriteLiteral(" tabindex=\"-1\"");

WriteLiteral(" role=\"dialog\"");

WriteLiteral(" aria-labelledby=\"exampleModalLabel\"");

WriteLiteral(" style=\"display: none;\"");

WriteLiteral(" aria-hidden=\"true\"");

WriteLiteral(">\r\n    <div");

WriteLiteral(" class=\"modal-dialog tab-content\"");

WriteLiteral(" role=\"document\"");

WriteLiteral(" style=\"float:right;margin:0;margin-right: -17px;width:500px;height:100%;\"");

WriteLiteral(">\r\n        <div");

WriteLiteral(" class=\"modal-content\"");

WriteLiteral(" style=\"height: 100%; border-radius: 0;\"");

WriteLiteral(">\r\n            <div");

WriteLiteral(" class=\"modal-header flex-shrink-0\"");

WriteLiteral(">\r\n                <h5");

WriteLiteral(" class=\"modal-title\"");

WriteLiteral(" id=\"exampleModalLabel\"");

WriteLiteral(">附加信息</h5>\r\n                <button");

WriteLiteral(" type=\"button\"");

WriteLiteral(" class=\"close\"");

WriteLiteral(" data-dismiss=\"modal\"");

WriteLiteral(" aria-label=\"Close\"");

WriteLiteral("></button>\r\n            </div>\r\n            <div");

WriteLiteral(" class=\"modal-body test-5\"");

WriteLiteral(" style=\"overflow-y: auto; overflow-x: hidden; height: calc(100% - 3.8rem);\"");

WriteLiteral(">\r\n                <div");

WriteLiteral(" class=\"tab-content\"");

WriteLiteral(">\r\n");

            
            #line 121 "..\..\Views\Shared\_Form_TaskView.cshtml"
                    
            
            #line default
            #line hidden
            
            #line 121 "..\..\Views\Shared\_Form_TaskView.cshtml"
                     if (fields.Any(f => f.ColumnName.EqualIgnoreCase("Tags")))
                    {
                        
            
            #line default
            #line hidden
            
            #line 123 "..\..\Views\Shared\_Form_TaskView.cshtml"
                   Write(Html.Partial("_Form_TaskView_Tags", entity));

            
            #line default
            #line hidden
            
            #line 123 "..\..\Views\Shared\_Form_TaskView.cshtml"
                                                                    
                    }

            
            #line default
            #line hidden
WriteLiteral("\r\n                    \r\n\r\n");

            
            #line 128 "..\..\Views\Shared\_Form_TaskView.cshtml"
                    
            
            #line default
            #line hidden
            
            #line 128 "..\..\Views\Shared\_Form_TaskView.cshtml"
                     if (!IsNew&&fields.Any(f => f.ColumnName.EqualIgnoreCase("LatLng")))
                    {
                        
            
            #line default
            #line hidden
            
            #line 130 "..\..\Views\Shared\_Form_TaskView.cshtml"
                   Write(Html.Partial("_Form_TaskView_Map", entity));

            
            #line default
            #line hidden
            
            #line 130 "..\..\Views\Shared\_Form_TaskView.cshtml"
                                                                   
                    }

            
            #line default
            #line hidden
WriteLiteral("                </div>\r\n            </div>\r\n            ");

WriteLiteral("\r\n        </div>\r\n    </div>\r\n</div>\r\n\r\n");

        }
    }
}
#pragma warning restore 1591
