#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Optimization;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using MUI.WebSite;
    using NewLife;
    
    #line 1 "..\..\Views\Shared\_Layout_Admin.cshtml"
    using NewLife.Common;
    
    #line default
    #line hidden
    
    #line 2 "..\..\Views\Shared\_Layout_Admin.cshtml"
    using NewLife.Cube;
    
    #line default
    #line hidden
    using NewLife.Reflection;
    using NewLife.Web;
    using XCode;
    using XCode.Membership;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Shared/_Layout_Admin.cshtml")]
    public partial class _Views_Shared__Layout_Admin_cshtml : System.Web.Mvc.WebViewPage<dynamic>
    {
        public _Views_Shared__Layout_Admin_cshtml()
        {
        }
        public override void Execute()
        {
            
            #line 3 "..\..\Views\Shared\_Layout_Admin.cshtml"
  
    var set = NewLife.Cube.Setting.Current;

            
            #line default
            #line hidden
WriteLiteral("\r\n<!DOCTYPE html>\r\n<html>\r\n<head>\r\n    <meta");

WriteLiteral(" charset=\"utf-8\"");

WriteLiteral(">\r\n    <meta");

WriteLiteral(" http-equiv=\"X-UA-Compatible\"");

WriteLiteral(" content=\"IE=edge\"");

WriteLiteral(">\r\n    <meta");

WriteLiteral(" name=\"viewport\"");

WriteLiteral(" content=\"width=device-width, initial-scale=1\"");

WriteLiteral(">\r\n    <meta");

WriteLiteral(" name=\"description\"");

WriteLiteral(" content=\"新生命团队,NewLife,魔方,Cube,XCode,Yooyeah,XIoT\"");

WriteLiteral(" />\r\n    ");

WriteLiteral("\r\n    <title>");

            
            #line 14 "..\..\Views\Shared\_Layout_Admin.cshtml"
      Write(ViewBag.Title);

            
            #line default
            #line hidden
WriteLiteral(" - ");

            
            #line 14 "..\..\Views\Shared\_Layout_Admin.cshtml"
                       Write(SysConfig.Current.DisplayName);

            
            #line default
            #line hidden
WriteLiteral("</title>\r\n    <link");

WriteAttribute("href", Tuple.Create(" href=\"", 498), Tuple.Create("\"", 518)
, Tuple.Create(Tuple.Create("", 505), Tuple.Create<System.Object, System.Int32>(Href("~/favicon.ico")
, 505), false)
);

WriteLiteral(" rel=\"shortcut icon\"");

WriteLiteral(" type=\"image/x-icon\"");

WriteLiteral(">\r\n\r\n    <!-- 网页字体 -->\r\n    <script");

WriteLiteral(" src=\"https://cdn.bootcss.com/webfont/1.6.16/webfontloader.js\"");

WriteLiteral(@"></script>
    <script>
        WebFont.load({
            google: { ""families"": [""Poppins:300,400,500,600,700"", ""Roboto:300,400,500,600,700""] },
            active: function () {
                sessionStorage.fonts = true;
            }
        });
    </script>
    <!-- 强制页面样式 -->
    <link");

WriteAttribute("href", Tuple.Create(" href=\"", 960), Tuple.Create("\"", 1035)
, Tuple.Create(Tuple.Create("", 967), Tuple.Create<System.Object, System.Int32>(Href("~/assets/vendors/general/perfect-scrollbar/css/perfect-scrollbar.css")
, 967), false)
);

WriteLiteral(" rel=\"stylesheet\"");

WriteLiteral(" type=\"text/css\"");

WriteLiteral(" />\r\n\r\n    <!-- 核心页面样式 -->\r\n    <link");

WriteAttribute("href", Tuple.Create(" href=\"", 1106), Tuple.Create("\"", 1174)
, Tuple.Create(Tuple.Create("", 1113), Tuple.Create<System.Object, System.Int32>(Href("~/Assets/vendors/general/bootstrap/dist/css/bootstrap.min.css")
, 1113), false)
);

WriteLiteral(" rel=\"stylesheet\"");

WriteLiteral(" type=\"text/css\"");

WriteLiteral(" />\r\n    <link");

WriteAttribute("href", Tuple.Create(" href=\"", 1222), Tuple.Create("\"", 1313)
, Tuple.Create(Tuple.Create("", 1229), Tuple.Create<System.Object, System.Int32>(Href("~/Assets/vendors/general/bootstrap-datepicker/dist/css/bootstrap-datepicker3.min." +
"css")
, 1229), false)
);

WriteLiteral(" rel=\"stylesheet\"");

WriteLiteral(" type=\"text/css\"");

WriteLiteral(" />\r\n    <link");

WriteAttribute("href", Tuple.Create(" href=\"", 1361), Tuple.Create("\"", 1451)
, Tuple.Create(Tuple.Create("", 1368), Tuple.Create<System.Object, System.Int32>(Href("~/Assets/vendors/general/bootstrap-datepicker/dist/css/bootstrap-datepicker.min.c" +
"ss")
, 1368), false)
);

WriteLiteral(" rel=\"stylesheet\"");

WriteLiteral(" type=\"text/css\"");

WriteLiteral(" />\r\n    <link");

WriteAttribute("href", Tuple.Create(" href=\"", 1499), Tuple.Create("\"", 1584)
, Tuple.Create(Tuple.Create("", 1506), Tuple.Create<System.Object, System.Int32>(Href("~/Assets/vendors/general/bootstrap-timepicker/css/bootstrap-timepicker.min.css")
, 1506), false)
);

WriteLiteral(" rel=\"stylesheet\"");

WriteLiteral(" type=\"text/css\"");

WriteLiteral(" />\r\n    <link");

WriteAttribute("href", Tuple.Create(" href=\"", 1632), Tuple.Create("\"", 1726)
, Tuple.Create(Tuple.Create("", 1639), Tuple.Create<System.Object, System.Int32>(Href("~/Assets/vendors/general/bootstrap-datetime-picker/css/bootstrap-datetimepicker.m" +
"in.css")
, 1639), false)
);

WriteLiteral(" rel=\"stylesheet\"");

WriteLiteral(" type=\"text/css\"");

WriteLiteral(" />\r\n    <link");

WriteAttribute("href", Tuple.Create(" href=\"", 1774), Tuple.Create("\"", 1851)
, Tuple.Create(Tuple.Create("", 1781), Tuple.Create<System.Object, System.Int32>(Href("~/assets/vendors/general/bootstrap-daterangepicker/daterangepicker.css")
, 1781), false)
);

WriteLiteral(" rel=\"stylesheet\"");

WriteLiteral(" type=\"text/css\"");

WriteLiteral(" />\r\n    <link");

WriteAttribute("href", Tuple.Create(" href=\"", 1899), Tuple.Create("\"", 1958)
, Tuple.Create(Tuple.Create("", 1906), Tuple.Create<System.Object, System.Int32>(Href("~/Assets/vendors/general/animate.css/animate.min.css")
, 1906), false)
);

WriteLiteral(" rel=\"stylesheet\"");

WriteLiteral(" type=\"text/css\"");

WriteLiteral(" />\r\n    <link");

WriteAttribute("href", Tuple.Create(" href=\"", 2006), Tuple.Create("\"", 2099)
, Tuple.Create(Tuple.Create("", 2013), Tuple.Create<System.Object, System.Int32>(Href("~/Assets/vendors/general/bootstrap-switch/dist/css/bootstrap3/bootstrap-switch.mi" +
"n.css")
, 2013), false)
);

WriteLiteral(" rel=\"stylesheet\"");

WriteLiteral(" type=\"text/css\"");

WriteLiteral(" />\r\n    <link");

WriteAttribute("href", Tuple.Create(" href=\"", 2147), Tuple.Create("\"", 2229)
, Tuple.Create(Tuple.Create("", 2154), Tuple.Create<System.Object, System.Int32>(Href("~/Assets/vendors/general/bootstrap-select/dist/css/bootstrap-select.min.css")
, 2154), false)
);

WriteLiteral(" rel=\"stylesheet\"");

WriteLiteral(" type=\"text/css\"");

WriteLiteral(" />\r\n    <link");

WriteAttribute("href", Tuple.Create(" href=\"", 2277), Tuple.Create("\"", 2341)
, Tuple.Create(Tuple.Create("", 2284), Tuple.Create<System.Object, System.Int32>(Href("~/Assets/vendors/general/select2/dist/css/select2.min.css")
, 2284), false)
);

WriteLiteral(" rel=\"stylesheet\"");

WriteLiteral(" type=\"text/css\"");

WriteLiteral(" />\r\n    <link");

WriteAttribute("href", Tuple.Create(" href=\"", 2389), Tuple.Create("\"", 2457)
, Tuple.Create(Tuple.Create("", 2396), Tuple.Create<System.Object, System.Int32>(Href("~/Assets/vendors/general/sweetalert2/dist/sweetalert2.min.css")
, 2396), false)
);

WriteLiteral(" rel=\"stylesheet\"");

WriteLiteral(" type=\"text/css\"");

WriteLiteral(" />\r\n    <link");

WriteAttribute("href", Tuple.Create(" href=\"", 2505), Tuple.Create("\"", 2572)
, Tuple.Create(Tuple.Create("", 2512), Tuple.Create<System.Object, System.Int32>(Href("~/Assets/vendors/custom/vendors/fontawesome5/css/all.min.css")
, 2512), false)
);

WriteLiteral(" rel=\"stylesheet\"");

WriteLiteral(" type=\"text/css\"");

WriteLiteral(" />\r\n    <link");

WriteAttribute("href", Tuple.Create(" href=\"", 2620), Tuple.Create("\"", 2680)
, Tuple.Create(Tuple.Create("", 2627), Tuple.Create<System.Object, System.Int32>(Href("~/Assets/vendors/custom/vendors/flaticon/flaticon.css")
, 2627), false)
);

WriteLiteral(" rel=\"stylesheet\"");

WriteLiteral(" type=\"text/css\"");

WriteLiteral(" />\r\n    <link");

WriteAttribute("href", Tuple.Create(" href=\"", 2728), Tuple.Create("\"", 2800)
, Tuple.Create(Tuple.Create("", 2735), Tuple.Create<System.Object, System.Int32>(Href("~/Assets/vendors/custom/vendors/line-awesome/css/line-awesome.css")
, 2735), false)
);

WriteLiteral(" rel=\"stylesheet\"");

WriteLiteral(" type=\"text/css\"");

WriteLiteral(" />\r\n    <link");

WriteAttribute("href", Tuple.Create(" href=\"", 2848), Tuple.Create("\"", 2903)
, Tuple.Create(Tuple.Create("", 2855), Tuple.Create<System.Object, System.Int32>(Href("~/assets/app/custom/wizard/wizard-v2.default.css")
, 2855), false)
);

WriteLiteral(" rel=\"stylesheet\"");

WriteLiteral(" type=\"text/css\"");

WriteLiteral(" />\r\n\r\n    <!-- 全局皮肤样式 -->\r\n    <link");

WriteAttribute("href", Tuple.Create(" href=\"", 2974), Tuple.Create("\"", 3029)
, Tuple.Create(Tuple.Create("", 2981), Tuple.Create<System.Object, System.Int32>(Href("~/Assets/theme/default/base/style.bundle.min.css")
, 2981), false)
);

WriteLiteral(" rel=\"stylesheet\"");

WriteLiteral(" type=\"text/css\"");

WriteLiteral(" />\r\n    <link");

WriteAttribute("href", Tuple.Create(" href=\"", 3077), Tuple.Create("\"", 3138)
, Tuple.Create(Tuple.Create("", 3084), Tuple.Create<System.Object, System.Int32>(Href("~/assets/theme/default/skins/header/base/light.min.css")
, 3084), false)
);

WriteLiteral(" rel=\"stylesheet\"");

WriteLiteral(" type=\"text/css\"");

WriteLiteral(" />\r\n    <link");

WriteAttribute("href", Tuple.Create(" href=\"", 3186), Tuple.Create("\"", 3247)
, Tuple.Create(Tuple.Create("", 3193), Tuple.Create<System.Object, System.Int32>(Href("~/assets/theme/default/skins/header/menu/light.min.css")
, 3193), false)
);

WriteLiteral(" rel=\"stylesheet\"");

WriteLiteral(" type=\"text/css\"");

WriteLiteral(" />\r\n    <link");

WriteAttribute("href", Tuple.Create(" href=\"", 3295), Tuple.Create("\"", 3349)
, Tuple.Create(Tuple.Create("", 3302), Tuple.Create<System.Object, System.Int32>(Href("~/assets/theme/default/skins/brand/dark.min.css")
, 3302), false)
);

WriteLiteral(" rel=\"stylesheet\"");

WriteLiteral(" type=\"text/css\"");

WriteLiteral(" />\r\n    <link");

WriteAttribute("href", Tuple.Create(" href=\"", 3397), Tuple.Create("\"", 3451)
, Tuple.Create(Tuple.Create("", 3404), Tuple.Create<System.Object, System.Int32>(Href("~/assets/theme/default/skins/aside/dark.min.css")
, 3404), false)
);

WriteLiteral(" rel=\"stylesheet\"");

WriteLiteral(" type=\"text/css\"");

WriteLiteral(" />\r\n    <link");

WriteAttribute("href", Tuple.Create(" href=\"", 3499), Tuple.Create("\"", 3541)
, Tuple.Create(Tuple.Create("", 3506), Tuple.Create<System.Object, System.Int32>(Href("~/Assets/app/custom/cube.styles.css")
, 3506), false)
);

WriteLiteral(" rel=\"stylesheet\"");

WriteLiteral(" type=\"text/css\"");

WriteLiteral(" /> <!-- 自定义样式 -->\r\n\r\n    <!--jquery必须放前面才可以使用多选 sk-->\r\n    <script");

WriteAttribute("src", Tuple.Create(" src=\"", 3642), Tuple.Create("\"", 3694)
, Tuple.Create(Tuple.Create("", 3648), Tuple.Create<System.Object, System.Int32>(Href("~/assets/vendors/general/jquery/dist/jquery.js")
, 3648), false)
);

WriteLiteral(" type=\"text/javascript\"");

WriteLiteral("></script>\r\n</head>\r\n<body");

WriteLiteral(" class=\"kt-subheader--fixed kt-subheader--enabled kt-subheader--solid\"");

WriteLiteral(">\r\n    <div");

WriteLiteral(" class=\"kt-grid__item kt-grid__item--fluid kt-grid kt-grid--hor\"");

WriteLiteral(">\r\n");

WriteLiteral("        ");

            
            #line 60 "..\..\Views\Shared\_Layout_Admin.cshtml"
   Write(Html.Partial("_Layout_Breadcrumbs"));

            
            #line default
            #line hidden
WriteLiteral("\r\n        <div");

WriteLiteral(" class=\"kt-content kt-grid__item kt-grid__item--fluid\"");

WriteLiteral(" style=\"display: flex; flex-direction: column;\"");

WriteLiteral(" id=\"kt_content\"");

WriteLiteral(">\r\n");

WriteLiteral("            ");

            
            #line 62 "..\..\Views\Shared\_Layout_Admin.cshtml"
       Write(RenderBody());

            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n");

            
            #line 64 "..\..\Views\Shared\_Layout_Admin.cshtml"
            
            
            #line default
            #line hidden
            
            #line 64 "..\..\Views\Shared\_Layout_Admin.cshtml"
             if (DbRunTimeModule.Enable)
            {

            
            #line default
            #line hidden
WriteLiteral("                <div");

WriteLiteral(" class=\"kt-padding-0\"");

WriteLiteral(">\r\n                    <div");

WriteLiteral(" class=\"alert alert-secondary\"");

WriteLiteral(" role=\"alert\"");

WriteLiteral(">\r\n                        <div");

WriteLiteral(" class=\"alert-text\"");

WriteLiteral(">\r\n");

WriteLiteral("                            ");

            
            #line 69 "..\..\Views\Shared\_Layout_Admin.cshtml"
                       Write(Html.Raw(DbRunTimeModule.GetInfo()));

            
            #line default
            #line hidden
WriteLiteral("\r\n                        </div>\r\n                    </div>\r\n                </d" +
"iv>\r\n");

            
            #line 73 "..\..\Views\Shared\_Layout_Admin.cshtml"
            }

            
            #line default
            #line hidden
WriteLiteral("        </div>\r\n    </div>\r\n    <div");

WriteLiteral(" id=\"kt_scrolltop\"");

WriteLiteral(" class=\"kt-scrolltop\"");

WriteLiteral(">\r\n        <i");

WriteLiteral(" class=\"fa fa-arrow-up\"");

WriteLiteral("></i>\r\n    </div>\r\n\r\n    <!-- 核心脚本资源 -->\r\n    <script");

WriteAttribute("src", Tuple.Create(" src=\"", 4649), Tuple.Create("\"", 4712)
, Tuple.Create(Tuple.Create("", 4655), Tuple.Create<System.Object, System.Int32>(Href("~/Assets/vendors/general/popper.js/dist/umd/popper.min.js")
, 4655), false)
);

WriteLiteral("></script>\r\n    <script");

WriteAttribute("src", Tuple.Create(" src=\"", 4736), Tuple.Create("\"", 4793)
, Tuple.Create(Tuple.Create("", 4742), Tuple.Create<System.Object, System.Int32>(Href("~/assets/vendors/general/block-ui/jquery.blockUI.js")
, 4742), false)
);

WriteLiteral("></script>\r\n    <script");

WriteAttribute("src", Tuple.Create(" src=\"", 4817), Tuple.Create("\"", 4882)
, Tuple.Create(Tuple.Create("", 4823), Tuple.Create<System.Object, System.Int32>(Href("~/Assets/vendors/general/bootstrap/dist/js/bootstrap.min.js")
, 4823), false)
);

WriteLiteral("></script>\r\n    <script");

WriteAttribute("src", Tuple.Create(" src=\"", 4906), Tuple.Create("\"", 4967)
, Tuple.Create(Tuple.Create("", 4912), Tuple.Create<System.Object, System.Int32>(Href("~/Assets/vendors/general/tooltip.js/dist/umd/tooltip.js")
, 4912), false)
);

WriteLiteral("></script>\r\n    <script");

WriteAttribute("src", Tuple.Create(" src=\"", 4991), Tuple.Create("\"", 5065)
, Tuple.Create(Tuple.Create("", 4997), Tuple.Create<System.Object, System.Int32>(Href("~/Assets/vendors/general/perfect-scrollbar/dist/perfect-scrollbar.js")
, 4997), false)
);

WriteLiteral("></script>\r\n    <script");

WriteAttribute("src", Tuple.Create(" src=\"", 5089), Tuple.Create("\"", 5148)
, Tuple.Create(Tuple.Create("", 5095), Tuple.Create<System.Object, System.Int32>(Href("~/assets/vendors/general/sticky-js/dist/sticky.min.js")
, 5095), false)
);

WriteLiteral("></script>\r\n    <script");

WriteAttribute("src", Tuple.Create(" src=\"", 5172), Tuple.Create("\"", 5259)
, Tuple.Create(Tuple.Create("", 5178), Tuple.Create<System.Object, System.Int32>(Href("~/Assets/vendors/general/bootstrap-datepicker/dist/js/bootstrap-datepicker.min.js" +
"")
, 5178), false)
);

WriteLiteral("></script>\r\n    <script");

WriteAttribute("src", Tuple.Create(" src=\"", 5283), Tuple.Create("\"", 5365)
, Tuple.Create(Tuple.Create("", 5289), Tuple.Create<System.Object, System.Int32>(Href("~/Assets/vendors/general/bootstrap-timepicker/js/bootstrap-timepicker.min.js")
, 5289), false)
);

WriteLiteral("></script>\r\n    <script");

WriteAttribute("src", Tuple.Create(" src=\"", 5389), Tuple.Create("\"", 5480)
, Tuple.Create(Tuple.Create("", 5395), Tuple.Create<System.Object, System.Int32>(Href("~/Assets/vendors/general/bootstrap-datetime-picker/js/bootstrap-datetimepicker.mi" +
"n.js")
, 5395), false)
);

WriteLiteral("></script>\r\n    <script");

WriteAttribute("src", Tuple.Create(" src=\"", 5504), Tuple.Create("\"", 5574)
, Tuple.Create(Tuple.Create("", 5510), Tuple.Create<System.Object, System.Int32>(Href("~/assets/vendors/general/bootstrap-daterangepicker/moment.min.js")
, 5510), false)
);

WriteLiteral("></script>\r\n    <script");

WriteAttribute("src", Tuple.Create(" src=\"", 5598), Tuple.Create("\"", 5673)
, Tuple.Create(Tuple.Create("", 5604), Tuple.Create<System.Object, System.Int32>(Href("~/assets/vendors/general/bootstrap-daterangepicker/daterangepicker.js")
, 5604), false)
);

WriteLiteral("></script>\r\n    <script");

WriteAttribute("src", Tuple.Create(" src=\"", 5697), Tuple.Create("\"", 5776)
, Tuple.Create(Tuple.Create("", 5703), Tuple.Create<System.Object, System.Int32>(Href("~/Assets/vendors/general/bootstrap-switch/dist/js/bootstrap-switch.min.js")
, 5703), false)
);

WriteLiteral("></script>\r\n    <script");

WriteAttribute("src", Tuple.Create(" src=\"", 5800), Tuple.Create("\"", 5879)
, Tuple.Create(Tuple.Create("", 5806), Tuple.Create<System.Object, System.Int32>(Href("~/Assets/vendors/general/bootstrap-select/dist/js/bootstrap-select.min.js")
, 5806), false)
);

WriteLiteral("></script>\r\n    <script");

WriteAttribute("src", Tuple.Create(" src=\"", 5903), Tuple.Create("\"", 5969)
, Tuple.Create(Tuple.Create("", 5909), Tuple.Create<System.Object, System.Int32>(Href("~/Assets/vendors/general/select2/dist/js/select2.full.min.js")
, 5909), false)
);

WriteLiteral("></script>\r\n    <script");

WriteAttribute("src", Tuple.Create(" src=\"", 5993), Tuple.Create("\"", 6063)
, Tuple.Create(Tuple.Create("", 5999), Tuple.Create<System.Object, System.Int32>(Href("~/Assets/vendors/general/sweetalert2/dist/sweetalert2.all.min.js")
, 5999), false)
);

WriteLiteral("></script>\r\n    <script");

WriteAttribute("src", Tuple.Create(" src=\"", 6087), Tuple.Create("\"", 6159)
, Tuple.Create(Tuple.Create("", 6093), Tuple.Create<System.Object, System.Int32>(Href("~/assets/vendors/general/jquery-validation/dist/jquery.validate.js")
, 6093), false)
);

WriteLiteral(" type=\"text/javascript\"");

WriteLiteral("></script>\r\n    <script");

WriteAttribute("src", Tuple.Create(" src=\"", 6206), Tuple.Create("\"", 6281)
, Tuple.Create(Tuple.Create("", 6212), Tuple.Create<System.Object, System.Int32>(Href("~/assets/vendors/general/jquery-validation/dist/additional-methods.js")
, 6212), false)
);

WriteLiteral(" type=\"text/javascript\"");

WriteLiteral("></script>\r\n    <!-- 可选脚本资源 -->\r\n    <script");

WriteAttribute("src", Tuple.Create(" src=\"", 6349), Tuple.Create("\"", 6406)
, Tuple.Create(Tuple.Create("", 6355), Tuple.Create<System.Object, System.Int32>(Href("~/Assets/vendors/general/jquery.repeater/src/lib.js")
, 6355), false)
);

WriteLiteral("></script>\r\n    <script");

WriteAttribute("src", Tuple.Create(" src=\"", 6430), Tuple.Create("\"", 6496)
, Tuple.Create(Tuple.Create("", 6436), Tuple.Create<System.Object, System.Int32>(Href("~/Assets/vendors/general/jquery.repeater/src/jquery.input.js")
, 6436), false)
);

WriteLiteral("></script>\r\n    <script");

WriteAttribute("src", Tuple.Create(" src=\"", 6520), Tuple.Create("\"", 6582)
, Tuple.Create(Tuple.Create("", 6526), Tuple.Create<System.Object, System.Int32>(Href("~/Assets/vendors/general/jquery.repeater/src/repeater.js")
, 6526), false)
);

WriteLiteral("></script>\r\n    <!-- 全局脚本资源 -->\r\n    <script");

WriteAttribute("src", Tuple.Create(" src=\"", 6627), Tuple.Create("\"", 6682)
, Tuple.Create(Tuple.Create("", 6633), Tuple.Create<System.Object, System.Int32>(Href("~/Assets/theme/default/base/scripts.bundle.min.js")
, 6633), false)
);

WriteLiteral("></script>\r\n    <script");

WriteAttribute("src", Tuple.Create(" src=\"", 6706), Tuple.Create("\"", 6771)
, Tuple.Create(Tuple.Create("", 6712), Tuple.Create<System.Object, System.Int32>(Href("~/assets/vendors/custom/datatables/datatables.bundle.min.js")
, 6712), false)
);

WriteLiteral("></script>\r\n    <script");

WriteAttribute("src", Tuple.Create(" src=\"", 6795), Tuple.Create("\"", 6873)
, Tuple.Create(Tuple.Create("", 6801), Tuple.Create<System.Object, System.Int32>(Href("~/assets/vendors/general/perfect-scrollbar/dist/perfect-scrollbar.min.js")
, 6801), false)
);

WriteLiteral("></script>\r\n\r\n    <!-- 模板自定义脚本资源 -->\r\n    <script");

WriteAttribute("src", Tuple.Create(" src=\"", 6923), Tuple.Create("\"", 6967)
, Tuple.Create(Tuple.Create("", 6929), Tuple.Create<System.Object, System.Int32>(Href("~/assets/app/custom/cube.app.bundle.js")
, 6929), false)
);

WriteLiteral("></script>\r\n\r\n");

WriteLiteral("    ");

            
            #line 110 "..\..\Views\Shared\_Layout_Admin.cshtml"
Write(RenderSection("scripts", required: false));

            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n    <!--日历控件支持-->\r\n    <script>\r\n        $(function () {\r\n            $(\'.for" +
"m_datetime\').each(function () {\r\n                var df = $(this).attr(\'dateform" +
"at\');\r\n                if (!df) {\r\n                    $(this).attr(\'dateformat\'" +
", \'yyyy-mm-dd hh:ii:ss\');\r\n                    //$(this).width(140);\r\n          " +
"      }\r\n                else {\r\n                    // 把C#标准格式化替换为控件格式\r\n       " +
"             df = df.replace(\'mm\', \'ii\').replace(\'MM\', \'mm\').replace(\'HH\', \'hh\')" +
";\r\n                    $(this).attr(\'dateformat\', df);\r\n\r\n                    //" +
" 根据时间日期格式，锁定日期输入框宽度\r\n                    //if (df.indexOf(\'hh\') >= 0)\r\n         " +
"           //    $(this).width(140);\r\n                    //else\r\n              " +
"      //    $(this).width(80);\r\n                }\r\n\r\n                //根据日期格式自动推" +
"算日期选择view显示的范围\r\n                var sv = 2;\r\n                var mv = 2;\r\n      " +
"          var autoView = $(this).attr(\'autoView\');\r\n                if (autoView" +
" !== \'false\') {\r\n                    df = $(this).attr(\'dateformat\');\r\n         " +
"           if (df.indexOf(\'ii\') >= 0) {\r\n                        mv = 0;\r\n      " +
"                  if (df.indexOf(\'dd\') >= 0) {\r\n                            sv =" +
" 2;\r\n                        } else {\r\n                            sv = 1;\r\n    " +
"                    }\r\n                    } else if (df.indexOf(\'hh\') >= 0) {\r\n" +
"                        mv = 1;\r\n                        if (df.indexOf(\'dd\') >=" +
" 0) {\r\n                            sv = 2;\r\n                        } else {\r\n  " +
"                          sv = 1;\r\n                        }\r\n                  " +
"  } else if (df.indexOf(\'dd\') >= 0) {\r\n                        mv = 2;\r\n        " +
"                sv = 2;\r\n                    } else if (df.indexOf(\'mm\') >= 0) {" +
"\r\n                        mv = 3;\r\n                        sv = 3;\r\n            " +
"        } else if (df.indexOf(\'yyyy\') >= 0) {\r\n                        mv = 4;\r\n" +
"                        sv = 4;\r\n                    }\r\n                }\r\n\r\n   " +
"             $(this).attr(\'startview\', sv);\r\n                $(this).attr(\'minvi" +
"ew\', mv);\r\n            });\r\n            $(\"[dateformat]\").each(function () {\r\n  " +
"              $(this).datetimepicker({\r\n                    format: $(this).attr" +
"(\"dateformat\"),\r\n                    autoclose: true,\r\n                    langu" +
"age: \"zh-CN\",\r\n                    forceParse: false,\r\n                    start" +
"View: parseInt($(this).attr(\'startview\')),\r\n                    minView: parseIn" +
"t($(this).attr(\'minview\'))\r\n                });\r\n            });\r\n           \r\n " +
"           //$(\'.multiselect\').each(function () {\r\n            //    $(this).mul" +
"tiselect({\r\n            //        // 下拉列表仅在列表项比较多时显示过滤框\r\n            //        e" +
"nableFiltering: $(this).children().length > 10,\r\n            //        buttonCla" +
"ss: \'btn btn-white btn-primary\',\r\n            //        templates: {\r\n          " +
"  //            button: \'<button type=\"button\" class=\"multiselect dropdown-toggl" +
"e\" data-toggle=\"dropdown\"></button>\',\r\n            //            ul: \'<ul class=" +
"\"multiselect-container dropdown-menu\"></ul>\',\r\n            //            filter:" +
" \'<li class=\"multiselect-item filter\"><div class=\"input-group\"><span class=\"inpu" +
"t-group-addon\"><i class=\"fa fa-search\"></i></span><input class=\"form-control mul" +
"tiselect-search\" type=\"text\"></div></li>\',\r\n            //            filterClea" +
"rBtn: \'<span class=\"input-group-btn\"><button class=\"btn btn-default btn-white bt" +
"n-grey multiselect-clear-filter\" type=\"button\"><i class=\"fa fa-times-circle red2" +
"\"></i></button></span>\',\r\n            //            li: \'<li><a href=\"javascript" +
":void(0);\"><label></label></a></li>\',\r\n            //            divider: \'<li c" +
"lass=\"multiselect-item divider\"></li>\',\r\n            //            liGroup: \'<li" +
" class=\"multiselect-item group\"><label class=\"multiselect-group\"></label></li>\'\r" +
"\n            //        },\r\n            //        filterPlaceholder: \'搜索\',\r\n     " +
"       //        nonSelectedText: \'无\',\r\n            //        allSelectedText: \'" +
"全选\'\r\n            //    });\r\n            //});\r\n           \r\n            ");

WriteLiteral(@"
            $('tr').dblclick(function () {
                var $this = $(this);
                var row = $this.closest(""tr"");
                var findcell = row.find('.editcell');
                if (findcell.length > 0) window.location.href = findcell.attr(""href"");
            });
        });
    </script>

    <!--开关插件-->
    <script");

WriteAttribute("src", Tuple.Create(" src=\"", 11592), Tuple.Create("\"", 11671)
, Tuple.Create(Tuple.Create("", 11598), Tuple.Create<System.Object, System.Int32>(Href("~/Assets/vendors/general/bootstrap-switch/dist/js/bootstrap-switch.min.js")
, 11598), false)
);

WriteLiteral("></script>\r\n    <script>\r\n        $(function () {\r\n            $(\"input.chkSwitch" +
"\").bootstrapSwitch();\r\n\r\n            //区间时间插件\r\n            $(\"input[name=\'dtRang" +
"e\']\").daterangepicker(\r\n                {\r\n                    // autoApply: tru" +
"e,\r\n                    // autoUpdateInput: false,\r\n                    // alway" +
"sShowCalendars: true,\r\n                    buttonClasses: \'btn\',\r\n              " +
"      applyClass: \'btn-primary\',\r\n                    cancelClass: \'btn-secondar" +
"y\',\r\n                    ranges: {\r\n                        \'今天\': [moment(), mom" +
"ent()],\r\n                        \'昨天\': [moment().subtract(1, \'days\'), moment().s" +
"ubtract(1, \'days\')],\r\n                        \'近7天\': [moment().subtract(7, \'days" +
"\'), moment()],\r\n                        \'近30天\': [moment().subtract(29, \'days\'), " +
"moment()],\r\n                        \'这个月\': [moment().startOf(\'month\'), moment()." +
"endOf(\'month\')],\r\n                        \'上个月\': [moment().subtract(1, \'month\')." +
"startOf(\'month\'), moment().subtract(1, \'month\').endOf(\'month\')]\r\n               " +
"     },\r\n                    locale: {\r\n                        format: \"YYYY/MM" +
"/DD HH:mm:SS\",\r\n                        separator: \" - \",\r\n                     " +
"   applyLabel: \"确认\",\r\n                        cancelLabel: \"清空\",\r\n              " +
"          fromLabel: \"开始时间\",\r\n                        toLabel: \"结束时间\",\r\n        " +
"                customRangeLabel: \"自定义日期范围\",\r\n                        daysOfWeek" +
": [\"日\", \"一\", \"二\", \"三\", \"四\", \"五\", \"六\"],\r\n                        monthNames: [\"一月" +
"\", \"二月\", \"三月\", \"四月\", \"五月\", \"六月\", \"七月\", \"八月\", \"九月\", \"十月\", \"十一月\", \"十二月\"]\r\n        " +
"            }\r\n                }\r\n            ).on(\'cancel.daterangepicker\', fun" +
"ction (ev, picker) {\r\n                $(\"#dtRange\").val(\"请选择日期范围\");\r\n           " +
"     $(\"#dtStart\").val(\"\");\r\n                $(\"#dtEnd\").val(\"\");\r\n            }" +
").on(\'apply.daterangepicker\', function (ev, picker) {\r\n                $(\"#dtSta" +
"rt\").val(picker.startDate.format(\'YYYY-MM-DD\'));\r\n                $(\"#dtEnd\").va" +
"l(picker.endDate.format(\'YYYY-MM-DD\'));\r\n                $(\"#dtRange\").val(picke" +
"r.startDate.format(\'YYYY-MM-DD\') + \" 至 \" + picker.endDate.format(\'YYYY-MM-DD\'));" +
"\r\n            });\r\n        });\r\n    </script>\r\n    <script>\r\n        var KTAppOp" +
"tions = {\r\n            \"colors\": {\r\n                \"state\": {\r\n                " +
"    \"brand\": \"#5d78ff\",\r\n                    \"dark\": \"#282a3c\",\r\n               " +
"     \"light\": \"#ffffff\",\r\n                    \"primary\": \"#5867dd\",\r\n           " +
"         \"success\": \"#34bfa3\",\r\n                    \"info\": \"#36a3f7\",\r\n        " +
"            \"warning\": \"#ffb822\",\r\n                    \"danger\": \"#fd3995\"\r\n    " +
"            },\r\n                \"base\": {\r\n                    \"label\": [\"#c5cbe" +
"3\", \"#a1a8c3\", \"#3d4465\", \"#3e4466\"],\r\n                    \"shape\": [\"#f0f3ff\", " +
"\"#d9dffa\", \"#afb4d4\", \"#646c9a\"]\r\n                }\r\n            }\r\n        };\r\n" +
"    </script>\r\n\r\n    ");

WriteLiteral("\r\n    ");

WriteLiteral("\r\n    ");

WriteLiteral("\r\n    ");

WriteLiteral("\r\n</body>\r\n</html>\r\n");

        }
    }
}
#pragma warning restore 1591
