#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Optimization;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using MUI.WebSite;
    
    #line 1 "..\..\Views\Shared\_ListTree_Data.cshtml"
    using NewLife;
    
    #line default
    #line hidden
    using NewLife.Cube;
    using NewLife.Reflection;
    
    #line 2 "..\..\Views\Shared\_ListTree_Data.cshtml"
    using NewLife.Web;
    
    #line default
    #line hidden
    
    #line 3 "..\..\Views\Shared\_ListTree_Data.cshtml"
    using XCode;
    
    #line default
    #line hidden
    
    #line 4 "..\..\Views\Shared\_ListTree_Data.cshtml"
    using XCode.Configuration;
    
    #line default
    #line hidden
    using XCode.Membership;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Shared/_ListTree_Data.cshtml")]
    public partial class _Views_Shared__ListTree_Data_cshtml : System.Web.Mvc.WebViewPage<dynamic>
    {
        public _Views_Shared__ListTree_Data_cshtml()
        {
        }
        public override void Execute()
        {
            
            #line 5 "..\..\Views\Shared\_ListTree_Data.cshtml"
  
    var fact = ViewBag.Factory as IEntityOperate;
    var page = ViewBag.Page as Pager;
    var fields = ViewBag.Fields as IList<FieldItem>;
    var fk = fact.Unique;
    var enableSelect = this.EnableSelect();

    var hasUser = fields.Any(f => f.Name.EqualIgnoreCase("CreateUserID", "UpdateUserID"));
    if (hasUser && ViewData["Provider"] == null) { ViewData["Provider"] = ManageProvider.Provider; }

            
            #line default
            #line hidden
WriteLiteral("\r\n<div");

WriteLiteral(" style=\" overflow-x: auto;\"");

WriteLiteral(">\r\n    <table");

WriteLiteral(" class=\"table table-sm table-hover\"");

WriteLiteral(">\r\n        <thead>\r\n            <tr");

WriteLiteral(" class=\"kt-datatable__row\"");

WriteLiteral(">\r\n");

            
            #line 19 "..\..\Views\Shared\_ListTree_Data.cshtml"
                
            
            #line default
            #line hidden
            
            #line 19 "..\..\Views\Shared\_ListTree_Data.cshtml"
                 if (enableSelect)
                {

            
            #line default
            #line hidden
WriteLiteral("                    <th");

WriteLiteral(" class=\"kt-datatable__cell--center kt-datatable__cell kt-datatable__cell--check\"");

WriteLiteral(" style=\"width:20px;\"");

WriteLiteral(">\r\n                        <label");

WriteLiteral(" class=\"kt-checkbox kt-checkbox--single kt-checkbox--all kt-checkbox--solid\"");

WriteLiteral(">\r\n                            <input");

WriteLiteral(" type=\"checkbox\"");

WriteLiteral(" id=\"chkAll\"");

WriteLiteral(" title=\"全选\"");

WriteLiteral(" />\r\n                            <span></span>\r\n                        </label>\r" +
"\n                    </th>\r\n");

            
            #line 27 "..\..\Views\Shared\_ListTree_Data.cshtml"
                }

            
            #line default
            #line hidden
WriteLiteral("                ");

            
            #line 28 "..\..\Views\Shared\_ListTree_Data.cshtml"
                 foreach (var item in fields)
                {
                    var sortUrl = item.OriField != null ? page.GetSortUrl(item.OriField.Name) : page.GetSortUrl(item.Name);
                    var cls = item.IsIdentity ? "text-center hidden-md hidden-sm hidden-xs" : "text-center";

            
            #line default
            #line hidden
WriteLiteral("                    <th");

WriteAttribute("class", Tuple.Create(" class=\"", 1459), Tuple.Create("\"", 1471)
            
            #line 32 "..\..\Views\Shared\_ListTree_Data.cshtml"
, Tuple.Create(Tuple.Create("", 1467), Tuple.Create<System.Object, System.Int32>(cls
            
            #line default
            #line hidden
, 1467), false)
);

WriteAttribute("title", Tuple.Create(" title=\"", 1472), Tuple.Create("\"", 1497)
            
            #line 32 "..\..\Views\Shared\_ListTree_Data.cshtml"
, Tuple.Create(Tuple.Create("", 1480), Tuple.Create<System.Object, System.Int32>(item.Description
            
            #line default
            #line hidden
, 1480), false)
);

WriteLiteral("><a");

WriteAttribute("href", Tuple.Create(" href=\"", 1501), Tuple.Create("\"", 1526)
            
            #line 32 "..\..\Views\Shared\_ListTree_Data.cshtml"
, Tuple.Create(Tuple.Create("", 1508), Tuple.Create<System.Object, System.Int32>(Html.Raw(sortUrl)
            
            #line default
            #line hidden
, 1508), false)
);

WriteLiteral(">");

            
            #line 32 "..\..\Views\Shared\_ListTree_Data.cshtml"
                                                                                       Write(item.DisplayName);

            
            #line default
            #line hidden
WriteLiteral("</a></th>\r\n");

            
            #line 33 "..\..\Views\Shared\_ListTree_Data.cshtml"
                }

            
            #line default
            #line hidden
WriteLiteral("                ");

            
            #line 34 "..\..\Views\Shared\_ListTree_Data.cshtml"
                 if (this.Has(PermissionFlags.Update, PermissionFlags.Delete))
                {

            
            #line default
            #line hidden
WriteLiteral("                    <th");

WriteLiteral(" class=\"text-center\"");

WriteLiteral(">升</th>\r\n");

WriteLiteral("                    <th");

WriteLiteral(" class=\"text-center\"");

WriteLiteral(">降</th>\r\n");

WriteLiteral("                    <th");

WriteLiteral(" class=\"text-center\"");

WriteLiteral(">操作</th>\r\n");

            
            #line 39 "..\..\Views\Shared\_ListTree_Data.cshtml"
                }

            
            #line default
            #line hidden
WriteLiteral("            </tr>\r\n        </thead>\r\n        <tbody>\r\n");

            
            #line 43 "..\..\Views\Shared\_ListTree_Data.cshtml"
            
            
            #line default
            #line hidden
            
            #line 43 "..\..\Views\Shared\_ListTree_Data.cshtml"
             foreach (IEntityTree entity in Model)
            {
                var FirstFlag = 0;
                var p = entity.Parent as IEntityTree;
                if (p == null)
                {
                    p = fact.EntityType.GetValue("Root") as IEntityTree;
                }
                var id = entity["ID"];

            
            #line default
            #line hidden
WriteLiteral("                <tr>\r\n");

            
            #line 53 "..\..\Views\Shared\_ListTree_Data.cshtml"
                    
            
            #line default
            #line hidden
            
            #line 53 "..\..\Views\Shared\_ListTree_Data.cshtml"
                     if (enableSelect)
                    {

            
            #line default
            #line hidden
WriteLiteral("                        <td");

WriteLiteral(" class=\"text-center\"");

WriteLiteral(" style=\"width:20px;\"");

WriteLiteral(">\r\n                            <label");

WriteLiteral(" class=\"kt-checkbox kt-checkbox--single kt-checkbox--all kt-checkbox--solid\"");

WriteLiteral(">\r\n                                <input");

WriteLiteral(" type=\"checkbox\"");

WriteLiteral(" name=\"keys\"");

WriteAttribute("value", Tuple.Create(" value=\"", 2580), Tuple.Create("\"", 2604)
            
            #line 57 "..\..\Views\Shared\_ListTree_Data.cshtml"
, Tuple.Create(Tuple.Create("", 2588), Tuple.Create<System.Object, System.Int32>(entity[fk.Name]
            
            #line default
            #line hidden
, 2588), false)
);

WriteLiteral(" />\r\n                                <span></span>\r\n                            <" +
"/label>\r\n                        </td>\r\n");

            
            #line 61 "..\..\Views\Shared\_ListTree_Data.cshtml"
                    }

            
            #line default
            #line hidden
WriteLiteral("                    ");

            
            #line 62 "..\..\Views\Shared\_ListTree_Data.cshtml"
                     foreach (var item in fields)
                    {
                        if (FirstFlag == 0)
                        {
                            
            
            #line default
            #line hidden
            
            #line 66 "..\..\Views\Shared\_ListTree_Data.cshtml"
                       Write(Html.Partial("_List_Data_Item_First", new Pair(entity, item)));

            
            #line default
            #line hidden
            
            #line 66 "..\..\Views\Shared\_ListTree_Data.cshtml"
                                                                                          
                        }
                        else
                        {
                            
            
            #line default
            #line hidden
            
            #line 70 "..\..\Views\Shared\_ListTree_Data.cshtml"
                       Write(Html.Partial("_List_Data_Item", new Pair(entity, item)));

            
            #line default
            #line hidden
            
            #line 70 "..\..\Views\Shared\_ListTree_Data.cshtml"
                                                                                    
                        }

                        FirstFlag++;
                    }

            
            #line default
            #line hidden
WriteLiteral("                    ");

            
            #line 75 "..\..\Views\Shared\_ListTree_Data.cshtml"
                     if (this.Has(PermissionFlags.Update, PermissionFlags.Delete))
                    {

            
            #line default
            #line hidden
WriteLiteral("                        <td");

WriteLiteral(" class=\"text-center\"");

WriteLiteral(" style=\"width:50px;\"");

WriteLiteral(">\r\n");

            
            #line 78 "..\..\Views\Shared\_ListTree_Data.cshtml"
                            
            
            #line default
            #line hidden
            
            #line 78 "..\..\Views\Shared\_ListTree_Data.cshtml"
                             if (p != null && p.Childs != null && p.Childs.Count > 0 && entity != p.Childs[0])
                            {

            
            #line default
            #line hidden
WriteLiteral("                                <a");

WriteAttribute("href", Tuple.Create(" href=\"", 3601), Tuple.Create("\"", 3637)
            
            #line 80 "..\..\Views\Shared\_ListTree_Data.cshtml"
, Tuple.Create(Tuple.Create("", 3608), Tuple.Create<System.Object, System.Int32>(Url.Action("Up", new { id })
            
            #line default
            #line hidden
, 3608), false)
);

WriteLiteral("><span");

WriteLiteral(" class=\"la la-angle-up\"");

WriteLiteral(" style=\"color: green;\"");

WriteLiteral("></span></a>\r\n");

            
            #line 81 "..\..\Views\Shared\_ListTree_Data.cshtml"
                            }

            
            #line default
            #line hidden
WriteLiteral("                        </td>\r\n");

WriteLiteral("                        <td");

WriteLiteral(" class=\"text-center\"");

WriteLiteral(" style=\"width:50px;\"");

WriteLiteral(">\r\n");

            
            #line 84 "..\..\Views\Shared\_ListTree_Data.cshtml"
                            
            
            #line default
            #line hidden
            
            #line 84 "..\..\Views\Shared\_ListTree_Data.cshtml"
                             if (p != null && entity != p.Childs[p.Childs.Count - 1])
                            {

            
            #line default
            #line hidden
WriteLiteral("                                <a");

WriteAttribute("href", Tuple.Create(" href=\"", 3987), Tuple.Create("\"", 4025)
            
            #line 86 "..\..\Views\Shared\_ListTree_Data.cshtml"
, Tuple.Create(Tuple.Create("", 3994), Tuple.Create<System.Object, System.Int32>(Url.Action("Down", new { id })
            
            #line default
            #line hidden
, 3994), false)
);

WriteLiteral("><span");

WriteLiteral(" class=\"la la-angle-down\"");

WriteLiteral(" style=\"color: red;\"");

WriteLiteral("></span></a>\r\n");

            
            #line 87 "..\..\Views\Shared\_ListTree_Data.cshtml"
                            }

            
            #line default
            #line hidden
WriteLiteral("                        </td>\r\n");

WriteLiteral("                        <td");

WriteLiteral(" class=\"text-right\"");

WriteLiteral(" style=\"width:90px;\"");

WriteLiteral(">\r\n");

WriteLiteral("                            ");

            
            #line 90 "..\..\Views\Shared\_ListTree_Data.cshtml"
                       Write(Html.Partial("_List_Data_Action", (Object)entity));

            
            #line default
            #line hidden
WriteLiteral("\r\n                        </td>\r\n");

            
            #line 92 "..\..\Views\Shared\_ListTree_Data.cshtml"
                    }

            
            #line default
            #line hidden
WriteLiteral("                </tr>\r\n");

            
            #line 94 "..\..\Views\Shared\_ListTree_Data.cshtml"
            }

            
            #line default
            #line hidden
WriteLiteral("        </tbody>\r\n    </table>\r\n</div>");

        }
    }
}
#pragma warning restore 1591
