#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Optimization;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using MUI.WebSite;
    using NewLife;
    using NewLife.Cube;
    using NewLife.Reflection;
    
    #line 1 "..\..\Views\Shared\_List_Toolbar_DateRange.cshtml"
    using NewLife.Web;
    
    #line default
    #line hidden
    using XCode;
    using XCode.Membership;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Shared/_List_Toolbar_DateRange.cshtml")]
    public partial class _Views_Shared__List_Toolbar_DateRange_cshtml : System.Web.Mvc.WebViewPage<dynamic>
    {
        public _Views_Shared__List_Toolbar_DateRange_cshtml()
        {
        }
        public override void Execute()
        {
            
            #line 2 "..\..\Views\Shared\_List_Toolbar_DateRange.cshtml"
  
    var formatStr = (Model is String) ? Model : "yyyy-MM-dd";
    var p = ViewBag.Page as Pager;

            
            #line default
            #line hidden
WriteLiteral("\r\n<!--根据时间筛选-->\r\n<label");

WriteLiteral(" class=\"btn btn-sm p-0 pull-right\"");

WriteLiteral(">\r\n    <div");

WriteLiteral(" class=\"input-group input-group-sm flex-nowrap align-items-stretch\"");

WriteLiteral(">\r\n        <div");

WriteLiteral(" class=\"input-group-prepend\"");

WriteLiteral("><span");

WriteLiteral(" class=\"input-group-text p-0 pl-2\"");

WriteLiteral("><i");

WriteLiteral(" class=\"la la-calendar\"");

WriteLiteral(" aria-hidden=\"true\"");

WriteLiteral("></i></span></div>\r\n        <input");

WriteLiteral(" type=\"text\"");

WriteLiteral(" name=\"dtStart\"");

WriteLiteral(" class=\"form-control form-control-sm pull-right form_datetime\"");

WriteLiteral(" autocomplete=\"off\"");

WriteLiteral(" placeholder=\"开始时间\"");

WriteAttribute("value", Tuple.Create(" value=\"", 548), Tuple.Create("\"", 569)
            
            #line 10 "..\..\Views\Shared\_List_Toolbar_DateRange.cshtml"
                                                                      , Tuple.Create(Tuple.Create("", 556), Tuple.Create<System.Object, System.Int32>(p["dtStart"]
            
            #line default
            #line hidden
, 556), false)
);

WriteLiteral(" aria-describedby=\"basic-addon2\"");

WriteLiteral(" style=\"width: 95px;\"");

WriteLiteral(">\r\n        <input");

WriteLiteral(" type=\"text\"");

WriteLiteral(" name=\"dtEnd\"");

WriteLiteral(" class=\"form-control form-control-sm pull-right form_datetime\"");

WriteLiteral(" autocomplete=\"off\"");

WriteLiteral(" placeholder=\"结束时间\"");

WriteAttribute("value", Tuple.Create(" value=\"", 765), Tuple.Create("\"", 784)
            
            #line 11 "..\..\Views\Shared\_List_Toolbar_DateRange.cshtml"
                                                                    , Tuple.Create(Tuple.Create("", 773), Tuple.Create<System.Object, System.Int32>(p["dtEnd"]
            
            #line default
            #line hidden
, 773), false)
);

WriteLiteral(" aria-describedby=\"basic-addon2\"");

WriteLiteral(" style=\"width: 95px;\"");

WriteLiteral(">\r\n    </div>\r\n</label>");

        }
    }
}
#pragma warning restore 1591
