#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Optimization;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using MUI.WebSite;
    using NewLife;
    using NewLife.Cube;
    using NewLife.Reflection;
    
    #line 1 "..\..\Views\Shared\_List_Pager.cshtml"
    using NewLife.Web;
    
    #line default
    #line hidden
    using XCode;
    using XCode.Membership;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Shared/_List_Pager.cshtml")]
    public partial class _Views_Shared__List_Pager_cshtml : System.Web.Mvc.WebViewPage<dynamic>
    {
        public _Views_Shared__List_Pager_cshtml()
        {
        }
        public override void Execute()
        {
            
            #line 2 "..\..\Views\Shared\_List_Pager.cshtml"
  
    var page = ViewBag.Page as Pager;
    //page.PageUrlTemplate = page.PageUrlTemplate.Replace("{链接}", Url.Action("Index") + "{链接}");
    // 没有总记录数的时候不显示分页，可以认为不启用分页

    var act = ViewBag.Action as String;
    if (act.IsNullOrEmpty()) { act = Url.Action("Index"); }

            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n    \r\n\r\n");

            
            #line 13 "..\..\Views\Shared\_List_Pager.cshtml"
 if (page.TotalCount > 0)
{

            
            #line default
            #line hidden
WriteLiteral("    <form");

WriteAttribute("action", Tuple.Create(" action=\"", 351), Tuple.Create("\"", 400)
            
            #line 15 "..\..\Views\Shared\_List_Pager.cshtml"
, Tuple.Create(Tuple.Create("", 360), Tuple.Create<System.Object, System.Int32>(act
            
            #line default
            #line hidden
, 360), false)
, Tuple.Create(Tuple.Create("", 364), Tuple.Create("?", 364), true)
            
            #line 15 "..\..\Views\Shared\_List_Pager.cshtml"
, Tuple.Create(Tuple.Create("", 365), Tuple.Create<System.Object, System.Int32>(page.GetBaseUrl(true, true, false)
            
            #line default
            #line hidden
, 365), false)
);

WriteLiteral(" method=\"post\"");

WriteLiteral(" role=\"form\"");

WriteLiteral(" class=\"flex justify-content-between\"");

WriteLiteral(">\r\n        <div");

WriteLiteral(" class=\"kt-portlet__foot flex flex-grow-1 justify-content-between flex-wrap p-0 p" +
"t-4\"");

WriteLiteral(">\r\n            <div");

WriteLiteral(" class=\"kt-section\"");

WriteLiteral(">\r\n                <div");

WriteLiteral(" class=\"kt-pagination kt-pagination--brand \"");

WriteLiteral(" style=\"justify-content:flex-end\"");

WriteLiteral(">\r\n\r\n                    <div");

WriteLiteral(" class=\"btn-group btn-group-sm pl-3 pr-3\"");

WriteLiteral(" role=\"group\"");

WriteLiteral(" aria-label=\"Small button group\"");

WriteLiteral(">\r\n");

WriteLiteral("                        ");

            
            #line 21 "..\..\Views\Shared\_List_Pager.cshtml"
                   Write(Html.Raw(page.GetPage("首页")));

            
            #line default
            #line hidden
WriteLiteral("&nbsp;&nbsp;\r\n");

WriteLiteral("                        ");

            
            #line 22 "..\..\Views\Shared\_List_Pager.cshtml"
                   Write(Html.Raw(page.GetPage("上一页")));

            
            #line default
            #line hidden
WriteLiteral("&nbsp;&nbsp;\r\n");

WriteLiteral("                        ");

            
            #line 23 "..\..\Views\Shared\_List_Pager.cshtml"
                   Write(Html.Raw(page.GetPage("下一页")));

            
            #line default
            #line hidden
WriteLiteral("&nbsp;&nbsp;\r\n");

WriteLiteral("                        ");

            
            #line 24 "..\..\Views\Shared\_List_Pager.cshtml"
                   Write(Html.Raw(page.GetPage("尾页")));

            
            #line default
            #line hidden
WriteLiteral(" &nbsp;&nbsp;\r\n                    </div>\r\n\r\n                    <div");

WriteLiteral(" class=\"kt-pagination__toolbar\"");

WriteLiteral(">\r\n                        <span");

WriteLiteral(" class=\"pagination__desc\"");

WriteLiteral(">\r\n                            <div");

WriteLiteral(" class=\"flex align-items-center flex-shrink-0\"");

WriteLiteral(">\r\n                                共<span>&nbsp;");

            
            #line 30 "..\..\Views\Shared\_List_Pager.cshtml"
                                        Write(page.TotalCount.ToString("n0"));

            
            #line default
            #line hidden
WriteLiteral("&nbsp;</span> &nbsp;条\r\n                                共<span>&nbsp;");

            
            #line 31 "..\..\Views\Shared\_List_Pager.cshtml"
                                        Write(page.PageCount.ToString("n0"));

            
            #line default
            #line hidden
WriteLiteral("&nbsp;</span>页&nbsp;\r\n                            </div>\r\n                       " +
" </span>\r\n                        第<input");

WriteLiteral(" name=\"PageIndex\"");

WriteLiteral(" type=\"text\"");

WriteAttribute("value", Tuple.Create(" value=\"", 1642), Tuple.Create("\"", 1665)
            
            #line 34 "..\..\Views\Shared\_List_Pager.cshtml"
, Tuple.Create(Tuple.Create("", 1650), Tuple.Create<System.Object, System.Int32>(page.PageIndex
            
            #line default
            #line hidden
, 1650), false)
);

WriteLiteral(" class=\"form-control form-control-sm\"");

WriteLiteral(" style=\"width: 40px; height:25px; padding-left: 5px; margin: 0 5px;\"");

WriteLiteral(" />页\r\n                        <input");

WriteLiteral(" type=\"submit\"");

WriteLiteral(" value=\"GO\"");

WriteLiteral(" class=\"btn btn-sm btn-secondary  kt-margin-l-5 kt-margin-r-5\"");

WriteLiteral(" style=\" padding: 0; width: 30px; height:25px; line-height: 25px;margin-top: -1px" +
";\"");

WriteLiteral(" />\r\n                        页大小\r\n                        <select");

WriteLiteral(" id=\"PageSize\"");

WriteLiteral(" name=\"PageSize\"");

WriteLiteral(" onchange=\"$(this).parents(\'form\').submit();\"");

WriteLiteral(" class=\"custom-select custom-select-sm form-control form-control-sm\"");

WriteLiteral(" style=\"width:40px; height:25px; padding-top: 0;padding-bottom: 0;\"");

WriteLiteral(">\r\n                            <option");

WriteLiteral(" value=\"5\"");

WriteLiteral(">5</option>\r\n                            <option");

WriteLiteral(" value=\"10\"");

WriteLiteral(">10</option>\r\n                            <option");

WriteLiteral(" value=\"20\"");

WriteLiteral(">20</option>\r\n                            <option");

WriteLiteral(" value=\"30\"");

WriteLiteral(">30</option>\r\n                            <option");

WriteLiteral(" value=\"50\"");

WriteLiteral(">50</option>\r\n                            <option");

WriteLiteral(" value=\"100\"");

WriteLiteral(">100</option>\r\n                            <option");

WriteLiteral(" value=\"200\"");

WriteLiteral(">200</option>\r\n                            <option");

WriteLiteral(" value=\"500\"");

WriteLiteral(">500</option>\r\n                        </select>\r\n                        <script" +
"");

WriteLiteral(" type=\"text/javascript\"");

WriteLiteral(">\r\n                    $(function() {\r\n                        $(\'#PageSize\').val" +
"(");

            
            #line 49 "..\..\Views\Shared\_List_Pager.cshtml"
                                      Write(page.PageSize);

            
            #line default
            #line hidden
WriteLiteral(");\r\n                    });\r\n                        </script>\r\n\r\n               " +
"     </div>\r\n\r\n                </div>\r\n            </div>\r\n\r\n\r\n\r\n\r\n\r\n        </d" +
"iv>\r\n    </form>\r\n");

            
            #line 64 "..\..\Views\Shared\_List_Pager.cshtml"
}

            
            #line default
            #line hidden
        }
    }
}
#pragma warning restore 1591
