#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Optimization;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using MUI.WebSite;
    
    #line 1 "..\..\Views\Shared\_List_Toolbar.cshtml"
    using NewLife;
    
    #line default
    #line hidden
    
    #line 2 "..\..\Views\Shared\_List_Toolbar.cshtml"
    using NewLife.Cube;
    
    #line default
    #line hidden
    using NewLife.Reflection;
    
    #line 3 "..\..\Views\Shared\_List_Toolbar.cshtml"
    using NewLife.Web;
    
    #line default
    #line hidden
    
    #line 4 "..\..\Views\Shared\_List_Toolbar.cshtml"
    using XCode;
    
    #line default
    #line hidden
    
    #line 5 "..\..\Views\Shared\_List_Toolbar.cshtml"
    using XCode.Membership;
    
    #line default
    #line hidden
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Shared/_List_Toolbar.cshtml")]
    public partial class _Views_Shared__List_Toolbar_cshtml : System.Web.Mvc.WebViewPage<dynamic>
    {
        public _Views_Shared__List_Toolbar_cshtml()
        {
        }
        public override void Execute()
        {
            
            #line 6 "..\..\Views\Shared\_List_Toolbar.cshtml"
  
    var fact = ViewBag.Factory as IEntityOperate;
    var page = ViewBag.Page as Pager;
    var cls_collapsed = (page["kt-portlet--collapsed"] + "").Equals("1") ? "" : "kt-portlet--collapsed";

    var act = ViewBag.Action as String;
    if (act.IsNullOrEmpty()) { act = Url.Action("Index"); }

    var enableSelect = this.EnableSelect();
    var btn_add = "添加" + ViewContext.Controller.GetType().GetDisplayName();

            
            #line default
            #line hidden
WriteLiteral("\r\n<!--查询菜单栏-->\r\n<form");

WriteLiteral(" class=\"kt-portlet mb-0 \"");

WriteAttribute("action", Tuple.Create(" action=\"", 574), Tuple.Create("\"", 617)
            
            #line 18 "..\..\Views\Shared\_List_Toolbar.cshtml"
, Tuple.Create(Tuple.Create("", 583), Tuple.Create<System.Object, System.Int32>(Html.Raw(page.GetFormAction(act))
            
            #line default
            #line hidden
, 583), false)
);

WriteLiteral(" method=\"post\"");

WriteLiteral(" role=\"form\"");

WriteLiteral(">\r\n    <div");

WriteAttribute("class", Tuple.Create(" class=\"", 655), Tuple.Create("\"", 693)
, Tuple.Create(Tuple.Create("", 663), Tuple.Create("kt-portlet", 663), true)
, Tuple.Create(Tuple.Create(" ", 673), Tuple.Create("mb-0", 674), true)
            
            #line 19 "..\..\Views\Shared\_List_Toolbar.cshtml"
, Tuple.Create(Tuple.Create(" ", 678), Tuple.Create<System.Object, System.Int32>(cls_collapsed
            
            #line default
            #line hidden
, 679), false)
);

WriteLiteral(" data-ktportlet=\"true\"");

WriteLiteral(" id=\"kt_portlet_tools_1\"");

WriteLiteral(">\r\n        <input");

WriteLiteral(" type=\"hidden\"");

WriteLiteral(" id=\"kt-portlet--collapsed\"");

WriteLiteral(" name=\"kt-portlet--collapsed\"");

WriteAttribute("value", Tuple.Create(" value=\"", 827), Tuple.Create("\"", 865)
            
            #line 20 "..\..\Views\Shared\_List_Toolbar.cshtml"
             , Tuple.Create(Tuple.Create("", 835), Tuple.Create<System.Object, System.Int32>(page["kt-portlet--collapsed"]
            
            #line default
            #line hidden
, 835), false)
);

WriteLiteral(" />\r\n        <div");

WriteLiteral(" class=\"kt-portlet__head p-0 border-bottom-0\"");

WriteLiteral(">\r\n            <!--左边工具栏-->\r\n            <div");

WriteLiteral(" class=\"kt-portlet__head-label\"");

WriteLiteral(">\r\n                <div");

WriteLiteral(" class=\"kt-portlet__head-group pl-2\"");

WriteLiteral(">\r\n");

            
            #line 25 "..\..\Views\Shared\_List_Toolbar.cshtml"
                    
            
            #line default
            #line hidden
            
            #line 25 "..\..\Views\Shared\_List_Toolbar.cshtml"
                     if (this.Has(PermissionFlags.Insert))
                    {

            
            #line default
            #line hidden
WriteLiteral("                        <a");

WriteAttribute("href", Tuple.Create(" href=\"", 1175), Tuple.Create("\"", 1200)
            
            #line 27 "..\..\Views\Shared\_List_Toolbar.cshtml"
, Tuple.Create(Tuple.Create("", 1182), Tuple.Create<System.Object, System.Int32>(Url.Action("Add")
            
            #line default
            #line hidden
, 1182), false)
);

WriteLiteral(" class=\"btn btn-success btn-sm\"");

WriteLiteral("><i");

WriteLiteral(" class=\"la la-plus\"");

WriteLiteral("></i>");

            
            #line 27 "..\..\Views\Shared\_List_Toolbar.cshtml"
                                                                                                         Write(btn_add);

            
            #line default
            #line hidden
WriteLiteral("</a>\r\n");

            
            #line 28 "..\..\Views\Shared\_List_Toolbar.cshtml"
                    }

            
            #line default
            #line hidden
WriteLiteral("                    ");

            
            #line 29 "..\..\Views\Shared\_List_Toolbar.cshtml"
                     if (enableSelect)
                    {
                        
            
            #line default
            #line hidden
            
            #line 31 "..\..\Views\Shared\_List_Toolbar.cshtml"
                   Write(Html.Partial("_List_Toolbar_Batch"));

            
            #line default
            #line hidden
            
            #line 31 "..\..\Views\Shared\_List_Toolbar.cshtml"
                                                            
                    }

            
            #line default
            #line hidden
WriteLiteral("                </div>\r\n            </div>\r\n            <!--右边查询栏-->\r\n           " +
" <div");

WriteLiteral(" class=\"kt-portlet__head-toolbar\"");

WriteLiteral(">\r\n                <div");

WriteLiteral(" class=\"kt-portlet__head-group\"");

WriteLiteral(">\r\n                    <label");

WriteLiteral(" class=\"btn btn-sm p-0 pull-right\"");

WriteLiteral(">\r\n                        <a");

WriteLiteral(" href=\"#\"");

WriteLiteral(" data-ktportlet-tool=\"toggle\"");

WriteLiteral(" class=\"btn btn-outline-brand btn-sm \"");

WriteLiteral(">高级 <i");

WriteLiteral(" class=\"la la-angle-down\"");

WriteLiteral("></i></a>\r\n                    </label>\r\n");

WriteLiteral("                    ");

            
            #line 41 "..\..\Views\Shared\_List_Toolbar.cshtml"
               Write(Html.Partial("_List_Toolbar_Search"));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("                    ");

            
            #line 42 "..\..\Views\Shared\_List_Toolbar.cshtml"
               Write(Html.Partial("_List_Toolbar_Search_Udf"));

            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n                </div>\r\n            </div>\r\n        </div>\r\n        <!--更多筛选-" +
"->\r\n        <div");

WriteLiteral(" class=\"kt-portlet__body p-0 pb-3\"");

WriteLiteral(">\r\n            <div");

WriteLiteral(" class=\"kt-portlet__content\"");

WriteLiteral(">\r\n");

WriteLiteral("                ");

            
            #line 50 "..\..\Views\Shared\_List_Toolbar.cshtml"
           Write(Html.Partial("_List_Toolbar_Adv"));

            
            #line default
            #line hidden
WriteLiteral("\r\n            </div>\r\n        </div>\r\n    </div>\r\n</form>\r\n\r\n\r\n");

            
            #line 57 "..\..\Views\Shared\_List_Toolbar.cshtml"
 if (enableSelect)
{

            
            #line default
            #line hidden
WriteLiteral("    <script>\r\n        $(function () {\r\n            var $toolbarContext = $(\'.tool" +
"bar-batch\'),\r\n                $batchButtons = $(\'button[data-action=\"action\"], i" +
"nput[data-action=\"action\"]\'), //button, input=button, a 3种类型都可以\r\n               " +
" $table = $(\'.table\'),\r\n                $keys = $(\'input[name=\"keys\"]\', $table);" +
"\r\n\r\n            $table.on(\'click\', \'#chkAll\', function () {\r\n                // " +
"全选\r\n                $keys.prop(\'checked\', this.checked);\r\n                // 启用禁" +
"用批量操作区\r\n                $batchButtons.prop(\'disabled\', !this.checked);\r\n        " +
"    });\r\n\r\n            $table.on(\'click.checked\', \'tbody input[name=\"keys\"]\', fu" +
"nction (e) {\r\n                //页面中所有的checkbox\r\n                var allbox = $ta" +
"ble.find(\'tbody :checkbox[name=\"keys\"]\');\r\n                //页面中所选中的checkbox\r\n  " +
"              var selecteds = $table.find(\'tbody :checkbox:checked[name=\"keys\"]\'" +
");\r\n                if (selecteds.length > 0) {\r\n                    // 启用禁用批量操作" +
"区\r\n                    $batchButtons.prop(\'disabled\', false);\r\n                 " +
"   //需要判断当前页面所有行的checkbox是否都选中，以此来决定是否需要改变checkbox#chkAll 的状态\r\n                 " +
"   if (allbox.length == selecteds.length) {\r\n                        $table.find" +
"(\'#chkAll\').prop(\'checked\', true);\r\n                    } else {\r\n              " +
"          $table.find(\'#chkAll\').prop(\'checked\', false);\r\n                    }\r" +
"\n                }\r\n                else {\r\n                    $batchButtons.pr" +
"op(\'disabled\', true);\r\n                    $table.find(\'#chkAll\').prop(\'checked\'" +
", false);\r\n                }\r\n            });\r\n        })\r\n    </script>\r\n");

            
            #line 95 "..\..\Views\Shared\_List_Toolbar.cshtml"
}

            
            #line default
            #line hidden
        }
    }
}
#pragma warning restore 1591
