#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Optimization;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using MUI.WebSite;
    
    #line 1 "..\..\Views\Shared\_List_Data.cshtml"
    using NewLife;
    
    #line default
    #line hidden
    using NewLife.Cube;
    using NewLife.Reflection;
    
    #line 2 "..\..\Views\Shared\_List_Data.cshtml"
    using NewLife.Web;
    
    #line default
    #line hidden
    
    #line 3 "..\..\Views\Shared\_List_Data.cshtml"
    using XCode;
    
    #line default
    #line hidden
    
    #line 4 "..\..\Views\Shared\_List_Data.cshtml"
    using XCode.Configuration;
    
    #line default
    #line hidden
    
    #line 5 "..\..\Views\Shared\_List_Data.cshtml"
    using XCode.Membership;
    
    #line default
    #line hidden
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Shared/_List_Data.cshtml")]
    public partial class _Views_Shared__List_Data_cshtml : System.Web.Mvc.WebViewPage<dynamic>
    {
        public _Views_Shared__List_Data_cshtml()
        {
        }
        public override void Execute()
        {
            
            #line 6 "..\..\Views\Shared\_List_Data.cshtml"
  
    var fact = ViewBag.Factory as IEntityOperate;
    var page = ViewBag.Page as Pager;
    var fields = ViewBag.Fields as IList<FieldItem>;
    var fk = fact.Unique;
    var enableSelect = this.EnableSelect();

    var hasUser = fields.Any(f => f.Name.EqualIgnoreCase("CreateUserID", "UpdateUserID"));
    if (hasUser && ViewData["Provider"] == null) { ViewData["Provider"] = ManageProvider.Provider; }

            
            #line default
            #line hidden
WriteLiteral("\r\n<div");

WriteLiteral(" style=\" overflow-x: auto;\"");

WriteLiteral(">\r\n    <table");

WriteLiteral(" class=\"table table-sm table-hover\"");

WriteLiteral(" id=\"list_table\"");

WriteLiteral(">\r\n        <thead>\r\n            <tr");

WriteLiteral(" class=\"kt-datatable__row\"");

WriteLiteral(">\r\n");

            
            #line 20 "..\..\Views\Shared\_List_Data.cshtml"
                
            
            #line default
            #line hidden
            
            #line 20 "..\..\Views\Shared\_List_Data.cshtml"
                 if (enableSelect)
                {
                    
            
            #line default
            #line hidden
            
            #line 27 "..\..\Views\Shared\_List_Data.cshtml"
                           
                }

            
            #line default
            #line hidden
WriteLiteral("                ");

            
            #line 29 "..\..\Views\Shared\_List_Data.cshtml"
                 foreach (var item in fields)
                {
                    var sortUrl = item.OriField != null ? page.GetSortUrl(item.OriField.Name) : page.GetSortUrl(item.Name);
                    if (item.IsIdentity)
                    {

            
            #line default
            #line hidden
WriteLiteral("                        <th");

WriteLiteral(" class=\"text-center\"");

WriteAttribute("title", Tuple.Create(" title=\"", 1483), Tuple.Create("\"", 1508)
            
            #line 34 "..\..\Views\Shared\_List_Data.cshtml"
, Tuple.Create(Tuple.Create("", 1491), Tuple.Create<System.Object, System.Int32>(item.Description
            
            #line default
            #line hidden
, 1491), false)
);

WriteLiteral("><a");

WriteAttribute("href", Tuple.Create(" href=\"", 1512), Tuple.Create("\"", 1537)
            
            #line 34 "..\..\Views\Shared\_List_Data.cshtml"
   , Tuple.Create(Tuple.Create("", 1519), Tuple.Create<System.Object, System.Int32>(Html.Raw(sortUrl)
            
            #line default
            #line hidden
, 1519), false)
);

WriteLiteral(">");

            
            #line 34 "..\..\Views\Shared\_List_Data.cshtml"
                                                                                                  Write(item.DisplayName);

            
            #line default
            #line hidden
WriteLiteral("</a></th>\r\n");

            
            #line 35 "..\..\Views\Shared\_List_Data.cshtml"
                    }
                    else if (item.Type == typeof(String))
                    {

            
            #line default
            #line hidden
WriteLiteral("                        <th");

WriteLiteral(" class=\"text-left\"");

WriteAttribute("title", Tuple.Create(" title=\"", 1717), Tuple.Create("\"", 1742)
            
            #line 38 "..\..\Views\Shared\_List_Data.cshtml"
, Tuple.Create(Tuple.Create("", 1725), Tuple.Create<System.Object, System.Int32>(item.Description
            
            #line default
            #line hidden
, 1725), false)
);

WriteLiteral("><a");

WriteAttribute("href", Tuple.Create(" href=\"", 1746), Tuple.Create("\"", 1771)
            
            #line 38 "..\..\Views\Shared\_List_Data.cshtml"
 , Tuple.Create(Tuple.Create("", 1753), Tuple.Create<System.Object, System.Int32>(Html.Raw(sortUrl)
            
            #line default
            #line hidden
, 1753), false)
);

WriteLiteral(">");

            
            #line 38 "..\..\Views\Shared\_List_Data.cshtml"
                                                                                                Write(item.DisplayName);

            
            #line default
            #line hidden
WriteLiteral("</a></th>\r\n");

            
            #line 39 "..\..\Views\Shared\_List_Data.cshtml"
                    }
                    else if (item.Type == typeof(Decimal) || item.Type == typeof(Int32) || item.Type == typeof(Double))
                    {

            
            #line default
            #line hidden
WriteLiteral("                        <th");

WriteLiteral(" class=\"text-right\"");

WriteAttribute("title", Tuple.Create(" title=\"", 2014), Tuple.Create("\"", 2039)
            
            #line 42 "..\..\Views\Shared\_List_Data.cshtml"
, Tuple.Create(Tuple.Create("", 2022), Tuple.Create<System.Object, System.Int32>(item.Description
            
            #line default
            #line hidden
, 2022), false)
);

WriteLiteral("><a");

WriteAttribute("href", Tuple.Create(" href=\"", 2043), Tuple.Create("\"", 2068)
            
            #line 42 "..\..\Views\Shared\_List_Data.cshtml"
  , Tuple.Create(Tuple.Create("", 2050), Tuple.Create<System.Object, System.Int32>(Html.Raw(sortUrl)
            
            #line default
            #line hidden
, 2050), false)
);

WriteLiteral(">");

            
            #line 42 "..\..\Views\Shared\_List_Data.cshtml"
                                                                                                 Write(item.DisplayName);

            
            #line default
            #line hidden
WriteLiteral("</a></th>\r\n");

            
            #line 43 "..\..\Views\Shared\_List_Data.cshtml"
                    }
                    else if (item.Type == typeof(DateTime))
                    {

            
            #line default
            #line hidden
WriteLiteral("                        <th");

WriteLiteral(" class=\"text-left\"");

WriteLiteral(" style=\"min-width:134px;\"");

WriteAttribute("title", Tuple.Create(" title=\"", 2275), Tuple.Create("\"", 2300)
            
            #line 46 "..\..\Views\Shared\_List_Data.cshtml"
, Tuple.Create(Tuple.Create("", 2283), Tuple.Create<System.Object, System.Int32>(item.Description
            
            #line default
            #line hidden
, 2283), false)
);

WriteLiteral("><a");

WriteAttribute("href", Tuple.Create(" href=\"", 2304), Tuple.Create("\"", 2329)
            
            #line 46 "..\..\Views\Shared\_List_Data.cshtml"
                          , Tuple.Create(Tuple.Create("", 2311), Tuple.Create<System.Object, System.Int32>(Html.Raw(sortUrl)
            
            #line default
            #line hidden
, 2311), false)
);

WriteLiteral(">");

            
            #line 46 "..\..\Views\Shared\_List_Data.cshtml"
                                                                                                                         Write(item.DisplayName);

            
            #line default
            #line hidden
WriteLiteral("</a></th>\r\n");

            
            #line 47 "..\..\Views\Shared\_List_Data.cshtml"
                    }
                    else
                    {

            
            #line default
            #line hidden
WriteLiteral("                        <th");

WriteLiteral(" class=\"text-center\"");

WriteAttribute("title", Tuple.Create(" title=\"", 2478), Tuple.Create("\"", 2503)
            
            #line 50 "..\..\Views\Shared\_List_Data.cshtml"
, Tuple.Create(Tuple.Create("", 2486), Tuple.Create<System.Object, System.Int32>(item.Description
            
            #line default
            #line hidden
, 2486), false)
);

WriteLiteral("><a");

WriteAttribute("href", Tuple.Create(" href=\"", 2507), Tuple.Create("\"", 2532)
            
            #line 50 "..\..\Views\Shared\_List_Data.cshtml"
   , Tuple.Create(Tuple.Create("", 2514), Tuple.Create<System.Object, System.Int32>(Html.Raw(sortUrl)
            
            #line default
            #line hidden
, 2514), false)
);

WriteLiteral(">");

            
            #line 50 "..\..\Views\Shared\_List_Data.cshtml"
                                                                                                  Write(item.DisplayName);

            
            #line default
            #line hidden
WriteLiteral("</a></th>\r\n");

            
            #line 51 "..\..\Views\Shared\_List_Data.cshtml"
                    }
                }

            
            #line default
            #line hidden
WriteLiteral("                ");

            
            #line 53 "..\..\Views\Shared\_List_Data.cshtml"
                 if (this.Has(PermissionFlags.Update, PermissionFlags.Delete))
                {

            
            #line default
            #line hidden
WriteLiteral("                    <th");

WriteLiteral(" class=\"text-center\"");

WriteLiteral(" style=\"min-width:50px;\"");

WriteLiteral(">操作</th>\r\n");

            
            #line 56 "..\..\Views\Shared\_List_Data.cshtml"
                }

            
            #line default
            #line hidden
WriteLiteral("            </tr>\r\n        </thead>\r\n        <tbody>\r\n");

            
            #line 60 "..\..\Views\Shared\_List_Data.cshtml"
            
            
            #line default
            #line hidden
            
            #line 60 "..\..\Views\Shared\_List_Data.cshtml"
             foreach (var entity in Model)
            {

            
            #line default
            #line hidden
WriteLiteral("                <tr>\r\n                    ");

WriteLiteral("\r\n");

            
            #line 72 "..\..\Views\Shared\_List_Data.cshtml"
                    
            
            #line default
            #line hidden
            
            #line 72 "..\..\Views\Shared\_List_Data.cshtml"
                     foreach (var item in fields)
                    {
                        
            
            #line default
            #line hidden
            
            #line 74 "..\..\Views\Shared\_List_Data.cshtml"
                   Write(Html.Partial("_List_Data_Item", new Pair(entity, item)));

            
            #line default
            #line hidden
            
            #line 74 "..\..\Views\Shared\_List_Data.cshtml"
                                                                                
                    }

            
            #line default
            #line hidden
WriteLiteral("                    ");

            
            #line 76 "..\..\Views\Shared\_List_Data.cshtml"
                     if (this.Has(PermissionFlags.Update, PermissionFlags.Delete))
                    {

            
            #line default
            #line hidden
WriteLiteral("                        <td");

WriteLiteral(" class=\"text-right\"");

WriteLiteral(" style=\"width:100px;\"");

WriteLiteral(">\r\n");

WriteLiteral("                            ");

            
            #line 79 "..\..\Views\Shared\_List_Data.cshtml"
                       Write(Html.Partial("_List_Data_Action", (Object)entity));

            
            #line default
            #line hidden
WriteLiteral("\r\n                        </td>\r\n");

            
            #line 81 "..\..\Views\Shared\_List_Data.cshtml"
                    }

            
            #line default
            #line hidden
WriteLiteral("                </tr>\r\n");

            
            #line 83 "..\..\Views\Shared\_List_Data.cshtml"
            }

            
            #line default
            #line hidden
WriteLiteral("            ");

            
            #line 84 "..\..\Views\Shared\_List_Data.cshtml"
             if (page.State != null)
            {
                
            
            #line default
            #line hidden
            
            #line 86 "..\..\Views\Shared\_List_Data.cshtml"
           Write(Html.Partial("_List_Data_Stat", page.State));

            
            #line default
            #line hidden
            
            #line 86 "..\..\Views\Shared\_List_Data.cshtml"
                                                            
            }

            
            #line default
            #line hidden
WriteLiteral("        </tbody>\r\n    </table>\r\n</div>");

        }
    }
}
#pragma warning restore 1591
