#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Optimization;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using MUI.WebSite;
    using NewLife;
    
    #line 1 "..\..\Views\Shared\_Nav_TopBar.cshtml"
    using NewLife.Common;
    
    #line default
    #line hidden
    using NewLife.Cube;
    using NewLife.Reflection;
    using NewLife.Web;
    using XCode;
    
    #line 2 "..\..\Views\Shared\_Nav_TopBar.cshtml"
    using XCode.Membership;
    
    #line default
    #line hidden
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Shared/_Nav_TopBar.cshtml")]
    public partial class _Views_Shared__Nav_TopBar_cshtml : System.Web.Mvc.WebViewPage<dynamic>
    {
        public _Views_Shared__Nav_TopBar_cshtml()
        {
        }
        public override void Execute()
        {
            
            #line 3 "..\..\Views\Shared\_Nav_TopBar.cshtml"
  
  

            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n<!-- 顶部菜单栏-->\r\n    <div");

WriteLiteral(" class=\"kt-header__topbar\"");

WriteLiteral(">\r\n        <!--购物车 -->\r\n        <div");

WriteLiteral(" class=\"kt-header__topbar-item dropdown\"");

WriteLiteral(" id=\"div_nav_mycart\"");

WriteLiteral(">\r\n");

WriteLiteral("            ");

            
            #line 11 "..\..\Views\Shared\_Nav_TopBar.cshtml"
       Write(Html.Partial("_Nav_MyCart"));

            
            #line default
            #line hidden
WriteLiteral("\r\n        </div>\r\n        <!--通知栏-->\r\n        <div");

WriteLiteral(" class=\"kt-header__topbar-item dropdown\"");

WriteLiteral(">\r\n");

WriteLiteral("            ");

            
            #line 15 "..\..\Views\Shared\_Nav_TopBar.cshtml"
       Write(Html.Partial("_Nav_TopMenu_Notice"));

            
            #line default
            #line hidden
WriteLiteral("\r\n        </div>\r\n\r\n        <!--快捷操作-->\r\n        <div");

WriteLiteral(" class=\"kt-header__topbar-item dropdown\"");

WriteLiteral(">\r\n");

WriteLiteral("            ");

            
            #line 20 "..\..\Views\Shared\_Nav_TopBar.cshtml"
       Write(Html.Partial("_Nav_TopMenu_Quick"));

            
            #line default
            #line hidden
WriteLiteral("\r\n        </div>\r\n\r\n        <!--用户 -->\r\n        <div");

WriteLiteral(" class=\"kt-header__topbar-item kt-header__topbar-item--user\"");

WriteLiteral(">\r\n");

WriteLiteral("            ");

            
            #line 25 "..\..\Views\Shared\_Nav_TopBar.cshtml"
       Write(Html.Partial("_Nav_TopMenu_User"));

            
            #line default
            #line hidden
WriteLiteral("\r\n        </div>\r\n\r\n    </div>\r\n");

        }
    }
}
#pragma warning restore 1591
