#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Optimization;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using MUI.WebSite;
    using NewLife;
    using NewLife.Cube;
    using NewLife.Reflection;
    using NewLife.Web;
    using XCode;
    using XCode.Membership;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Shared/_Nav_Aside.cshtml")]
    public partial class _Views_Shared__Nav_Aside_cshtml : System.Web.Mvc.WebViewPage<dynamic>
    {
        public _Views_Shared__Nav_Aside_cshtml()
        {
        }
        public override void Execute()
        {
WriteLiteral("<!-- logo及展开缩放图标 -->\r\n<div");

WriteLiteral(" class=\"kt-aside__brand kt-grid__item\"");

WriteLiteral(" id=\"kt_aside_brand\"");

WriteLiteral(">\r\n    <div");

WriteLiteral(" class=\"kt-aside__brand-logo\"");

WriteLiteral(">\r\n        <a");

WriteAttribute("href", Tuple.Create(" href=\"", 137), Tuple.Create("\"", 183)
            
            #line 4 "..\..\Views\Shared\_Nav_Aside.cshtml"
, Tuple.Create(Tuple.Create("", 144), Tuple.Create<System.Object, System.Int32>(NewLife.Cube.Setting.Current.StartPage
            
            #line default
            #line hidden
, 144), false)
);

WriteLiteral("><img");

WriteLiteral(" alt=\"Logo\"");

WriteAttribute("src", Tuple.Create(" src=\"", 200), Tuple.Create("\"", 229)
, Tuple.Create(Tuple.Create("", 206), Tuple.Create<System.Object, System.Int32>(Href("~/assets/image/logo.png")
, 206), false)
);

WriteLiteral(" style=\"width:40px;height:40px;\"");

WriteLiteral(" /></a>\r\n    </div>\r\n    <div");

WriteLiteral(" class=\"kt-aside__brand-tools\"");

WriteLiteral(">\r\n        <button");

WriteLiteral(" class=\"kt-aside__brand-aside-toggler\"");

WriteLiteral(" id=\"kt_aside_toggler\"");

WriteLiteral(">\r\n            <span>\r\n                <svg");

WriteLiteral(" xmlns=\"http://www.w3.org/2000/svg\"");

WriteLiteral(" xmlns:xlink=\"http://www.w3.org/1999/xlink\"");

WriteLiteral(" width=\"24px\"");

WriteLiteral(" height=\"24px\"");

WriteLiteral(" viewBox=\"0 0 24 24\"");

WriteLiteral(" version=\"1.1\"");

WriteLiteral(" class=\"kt-svg-icon\"");

WriteLiteral(">\r\n                    <g");

WriteLiteral(" stroke=\"none\"");

WriteLiteral(" stroke-width=\"1\"");

WriteLiteral(" fill=\"none\"");

WriteLiteral(" fill-rule=\"evenodd\"");

WriteLiteral(">\r\n                        <polygon");

WriteLiteral(" id=\"Shape\"");

WriteLiteral(" points=\"0 0 24 0 24 24 0 24\"");

WriteLiteral(" />\r\n                        <path");

WriteLiteral(@" d=""M5.29288961,6.70710318 C4.90236532,6.31657888 4.90236532,5.68341391 5.29288961,5.29288961 C5.68341391,4.90236532 6.31657888,4.90236532 6.70710318,5.29288961 L12.7071032,11.2928896 C13.0856821,11.6714686 13.0989277,12.281055 12.7371505,12.675721 L7.23715054,18.675721 C6.86395813,19.08284 6.23139076,19.1103429 5.82427177,18.7371505 C5.41715278,18.3639581 5.38964985,17.7313908 5.76284226,17.3242718 L10.6158586,12.0300721 L5.29288961,6.70710318 Z""");

WriteLiteral(" id=\"Path-94\"");

WriteLiteral(" fill=\"#000000\"");

WriteLiteral(" fill-rule=\"nonzero\"");

WriteLiteral(" transform=\"translate(8.999997, 11.999999) scale(-1, 1) translate(-8.999997, -11." +
"999999) \"");

WriteLiteral(" />\r\n                        <path");

WriteLiteral(@" d=""M10.7071009,15.7071068 C10.3165766,16.0976311 9.68341162,16.0976311 9.29288733,15.7071068 C8.90236304,15.3165825 8.90236304,14.6834175 9.29288733,14.2928932 L15.2928873,8.29289322 C15.6714663,7.91431428 16.2810527,7.90106866 16.6757187,8.26284586 L22.6757187,13.7628459 C23.0828377,14.1360383 23.1103407,14.7686056 22.7371482,15.1757246 C22.3639558,15.5828436 21.7313885,15.6103465 21.3242695,15.2371541 L16.0300699,10.3841378 L10.7071009,15.7071068 Z""");

WriteLiteral(" id=\"Path-94\"");

WriteLiteral(" fill=\"#000000\"");

WriteLiteral(" fill-rule=\"nonzero\"");

WriteLiteral(" opacity=\"0.3\"");

WriteLiteral(" transform=\"translate(15.999997, 11.999999) scale(-1, 1) rotate(-270.000000) tran" +
"slate(-15.999997, -11.999999) \"");

WriteLiteral(" />\r\n                    </g>\r\n                </svg>\r\n            </span>\r\n     " +
"       <span>\r\n                <svg");

WriteLiteral(" xmlns=\"http://www.w3.org/2000/svg\"");

WriteLiteral(" xmlns:xlink=\"http://www.w3.org/1999/xlink\"");

WriteLiteral(" width=\"24px\"");

WriteLiteral(" height=\"24px\"");

WriteLiteral(" viewBox=\"0 0 24 24\"");

WriteLiteral(" version=\"1.1\"");

WriteLiteral(" class=\"kt-svg-icon\"");

WriteLiteral(">\r\n                    <g");

WriteLiteral(" stroke=\"none\"");

WriteLiteral(" stroke-width=\"1\"");

WriteLiteral(" fill=\"none\"");

WriteLiteral(" fill-rule=\"evenodd\"");

WriteLiteral(">\r\n                        <polygon");

WriteLiteral(" id=\"Shape\"");

WriteLiteral(" points=\"0 0 24 0 24 24 0 24\"");

WriteLiteral(" />\r\n                        <path");

WriteLiteral(@" d=""M12.2928955,6.70710318 C11.9023712,6.31657888 11.9023712,5.68341391 12.2928955,5.29288961 C12.6834198,4.90236532 13.3165848,4.90236532 13.7071091,5.29288961 L19.7071091,11.2928896 C20.085688,11.6714686 20.0989336,12.281055 19.7371564,12.675721 L14.2371564,18.675721 C13.863964,19.08284 13.2313966,19.1103429 12.8242777,18.7371505 C12.4171587,18.3639581 12.3896557,17.7313908 12.7628481,17.3242718 L17.6158645,12.0300721 L12.2928955,6.70710318 Z""");

WriteLiteral(" id=\"Path-94\"");

WriteLiteral(" fill=\"#000000\"");

WriteLiteral(" fill-rule=\"nonzero\"");

WriteLiteral(" />\r\n                        <path");

WriteLiteral(@" d=""M3.70710678,15.7071068 C3.31658249,16.0976311 2.68341751,16.0976311 2.29289322,15.7071068 C1.90236893,15.3165825 1.90236893,14.6834175 2.29289322,14.2928932 L8.29289322,8.29289322 C8.67147216,7.91431428 9.28105859,7.90106866 9.67572463,8.26284586 L15.6757246,13.7628459 C16.0828436,14.1360383 16.1103465,14.7686056 15.7371541,15.1757246 C15.3639617,15.5828436 14.7313944,15.6103465 14.3242754,15.2371541 L9.03007575,10.3841378 L3.70710678,15.7071068 Z""");

WriteLiteral(" id=\"Path-94\"");

WriteLiteral(" fill=\"#000000\"");

WriteLiteral(" fill-rule=\"nonzero\"");

WriteLiteral(" opacity=\"0.3\"");

WriteLiteral(" transform=\"translate(9.000003, 11.999999) rotate(-270.000000) translate(-9.00000" +
"3, -11.999999) \"");

WriteLiteral(" />\r\n                    </g>\r\n                </svg>\r\n            </span>\r\n     " +
"   </button>\r\n\r\n    </div>\r\n</div>\r\n");

        }
    }
}
#pragma warning restore 1591
