#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Optimization;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using MUI.WebSite;
    using NewLife;
    using NewLife.Cube;
    
    #line 1 "..\..\Views\Shared\_Nav_AsideMenu_Item.cshtml"
    using NewLife.Model;
    
    #line default
    #line hidden
    using NewLife.Reflection;
    using NewLife.Web;
    using XCode;
    
    #line 2 "..\..\Views\Shared\_Nav_AsideMenu_Item.cshtml"
    using XCode.Membership;
    
    #line default
    #line hidden
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Shared/_Nav_AsideMenu_Item.cshtml")]
    public partial class _Views_Shared__Nav_AsideMenu_Item_cshtml : System.Web.Mvc.WebViewPage<dynamic>
    {
        public _Views_Shared__Nav_AsideMenu_Item_cshtml()
        {
        }
        public override void Execute()
        {
            
            #line 3 "..\..\Views\Shared\_Nav_AsideMenu_Item.cshtml"
  
    var user = ViewBag.User as IUser ?? User.Identity as IUser;

    var fact = ObjectContainer.Current.Resolve<IMenuFactory>();

    var item = Model as IMenu;
    var childs = fact.GetMySubMenus(item.ID, user).Where(m => m.Visible);
    var url = item.Url.IsNullOrEmpty() ? "" : Url.Content(item.Url);

    var _controller = ViewContext.RouteData.Values["controller"]+"";
    var cfgs_list = new List<string>() { "Core","Cube","XCode","Sys","CompanySetting" };
    if (cfgs_list.Contains(_controller)) { _controller = "Cube"; }

            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n");

            
            #line 17 "..\..\Views\Shared\_Nav_AsideMenu_Item.cshtml"
 if (childs.Any())
{

            
            #line default
            #line hidden
WriteLiteral("    <li");

WriteLiteral(" class=\"kt-menu__item kt-menu__item--submenu\"");

WriteLiteral(" aria-haspopup=\"true\"");

WriteLiteral(" m-menu-submenu-toggle=\"hover\"");

WriteLiteral(">   \r\n        <a");

WriteLiteral(" href=\"javascript:;\"");

WriteLiteral(" class=\"kt-menu__link kt-menu__toggle\"");

WriteLiteral(">\r\n");

            
            #line 21 "..\..\Views\Shared\_Nav_AsideMenu_Item.cshtml"
            
            
            #line default
            #line hidden
            
            #line 21 "..\..\Views\Shared\_Nav_AsideMenu_Item.cshtml"
             if (!@item.Icon.IsNullOrEmpty())
            {

            
            #line default
            #line hidden
WriteLiteral("                <i");

WriteAttribute("class", Tuple.Create(" class=\"", 882), Tuple.Create("\"", 919)
, Tuple.Create(Tuple.Create("", 890), Tuple.Create("kt-menu__link-icon", 890), true)
            
            #line 23 "..\..\Views\Shared\_Nav_AsideMenu_Item.cshtml"
, Tuple.Create(Tuple.Create(" ", 908), Tuple.Create<System.Object, System.Int32>(item.Icon
            
            #line default
            #line hidden
, 909), false)
);

WriteLiteral("></i>\r\n");

            
            #line 24 "..\..\Views\Shared\_Nav_AsideMenu_Item.cshtml"
            }
            else
            {

            
            #line default
            #line hidden
WriteLiteral("                <i");

WriteLiteral(" class=\"kt-menu__link-bullet kt-menu__link-bullet--dot\"");

WriteLiteral("><span></span></i>\r\n");

            
            #line 28 "..\..\Views\Shared\_Nav_AsideMenu_Item.cshtml"
            }

            
            #line default
            #line hidden
WriteLiteral("            <span");

WriteLiteral(" class=\"kt-menu__link-text\"");

WriteLiteral(">");

            
            #line 29 "..\..\Views\Shared\_Nav_AsideMenu_Item.cshtml"
                                        Write(item.DisplayName);

            
            #line default
            #line hidden
WriteLiteral("</span>\r\n            <i");

WriteLiteral(" class=\"kt-menu__ver-arrow la la-angle-right\"");

WriteLiteral("></i>\r\n        </a>\r\n        <div");

WriteLiteral(" class=\"kt-menu__submenu\"");

WriteLiteral(">\r\n            <span");

WriteLiteral(" class=\"kt-menu__arrow\"");

WriteLiteral("></span>\r\n            <ul");

WriteLiteral(" class=\"kt-menu__subnav\"");

WriteLiteral(">\r\n                <li");

WriteLiteral(" class=\"kt-menu__item kt-menu__item--parent\"");

WriteLiteral(" aria-haspopup=\"true\"");

WriteLiteral(">\r\n                    <span");

WriteLiteral(" class=\"kt-menu__link\"");

WriteLiteral("><span");

WriteLiteral(" class=\"kt-menu__link-text\"");

WriteLiteral(">");

            
            #line 36 "..\..\Views\Shared\_Nav_AsideMenu_Item.cshtml"
                                                                            Write(item.DisplayName);

            
            #line default
            #line hidden
WriteLiteral("</span></span>\r\n                </li>\r\n");

            
            #line 38 "..\..\Views\Shared\_Nav_AsideMenu_Item.cshtml"
                
            
            #line default
            #line hidden
            
            #line 38 "..\..\Views\Shared\_Nav_AsideMenu_Item.cshtml"
                 foreach (var menu in childs)
                {
                    
            
            #line default
            #line hidden
            
            #line 40 "..\..\Views\Shared\_Nav_AsideMenu_Item.cshtml"
               Write(Html.Partial("_Nav_AsideMenu_Item", menu));

            
            #line default
            #line hidden
            
            #line 40 "..\..\Views\Shared\_Nav_AsideMenu_Item.cshtml"
                                                              ;
                }

            
            #line default
            #line hidden
WriteLiteral("            </ul>\r\n        </div>\r\n    </li>\r\n");

            
            #line 45 "..\..\Views\Shared\_Nav_AsideMenu_Item.cshtml"
}
else
{
    var  _open= _controller == item.Name ? "kt-menu__item--active" : "";

            
            #line default
            #line hidden
WriteLiteral("    <li");

WriteAttribute("class", Tuple.Create(" class=\"", 1879), Tuple.Create("\"", 1907)
, Tuple.Create(Tuple.Create("", 1887), Tuple.Create("kt-menu__item", 1887), true)
            
            #line 49 "..\..\Views\Shared\_Nav_AsideMenu_Item.cshtml"
, Tuple.Create(Tuple.Create(" ", 1900), Tuple.Create<System.Object, System.Int32>(_open
            
            #line default
            #line hidden
, 1901), false)
);

WriteLiteral(" aria-haspopup=\"true\"");

WriteLiteral(">\r\n        <a");

WriteAttribute("href", Tuple.Create(" href=\"", 1942), Tuple.Create("\"", 1953)
            
            #line 50 "..\..\Views\Shared\_Nav_AsideMenu_Item.cshtml"
, Tuple.Create(Tuple.Create("", 1949), Tuple.Create<System.Object, System.Int32>(url
            
            #line default
            #line hidden
, 1949), false)
);

WriteLiteral(" class=\"kt-menu__link\"");

WriteLiteral(" target=\"_self\"");

WriteLiteral(" >\r\n");

            
            #line 51 "..\..\Views\Shared\_Nav_AsideMenu_Item.cshtml"
            
            
            #line default
            #line hidden
            
            #line 51 "..\..\Views\Shared\_Nav_AsideMenu_Item.cshtml"
             if (!@item.Icon.IsNullOrEmpty())
            {

            
            #line default
            #line hidden
WriteLiteral("                <i");

WriteAttribute("class", Tuple.Create(" class=\"", 2075), Tuple.Create("\"", 2112)
, Tuple.Create(Tuple.Create("", 2083), Tuple.Create("kt-menu__link-icon", 2083), true)
            
            #line 53 "..\..\Views\Shared\_Nav_AsideMenu_Item.cshtml"
, Tuple.Create(Tuple.Create(" ", 2101), Tuple.Create<System.Object, System.Int32>(item.Icon
            
            #line default
            #line hidden
, 2102), false)
);

WriteLiteral("></i>\r\n");

            
            #line 54 "..\..\Views\Shared\_Nav_AsideMenu_Item.cshtml"
            }
            else
            {

            
            #line default
            #line hidden
WriteLiteral("                <i");

WriteLiteral(" class=\"kt-menu__link-bullet kt-menu__link-bullet--dot\"");

WriteLiteral("><span></span></i>\r\n");

            
            #line 58 "..\..\Views\Shared\_Nav_AsideMenu_Item.cshtml"
            }

            
            #line default
            #line hidden
WriteLiteral("            <span");

WriteLiteral(" class=\"kt-menu__link-text \"");

WriteLiteral("> ");

            
            #line 59 "..\..\Views\Shared\_Nav_AsideMenu_Item.cshtml"
                                          Write(item.DisplayName);

            
            #line default
            #line hidden
WriteLiteral("</span>\r\n        </a>\r\n    </li>\r\n");

            
            #line 62 "..\..\Views\Shared\_Nav_AsideMenu_Item.cshtml"
}
            
            #line default
            #line hidden
        }
    }
}
#pragma warning restore 1591
