#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Optimization;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using MUI.WebSite;
    using NewLife;
    using NewLife.Cube;
    using NewLife.Reflection;
    using NewLife.Web;
    using XCode;
    using XCode.Membership;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Shared/_Nav_TopMenu_Quick.cshtml")]
    public partial class _Views_Shared__Nav_TopMenu_Quick_cshtml : System.Web.Mvc.WebViewPage<dynamic>
    {
        public _Views_Shared__Nav_TopMenu_Quick_cshtml()
        {
        }
        public override void Execute()
        {
            
            #line 1 "..\..\Views\Shared\_Nav_TopMenu_Quick.cshtml"
  
     var user = ManageProvider.User;

            
            #line default
            #line hidden
WriteLiteral("\r\n<!--快捷菜单-->\r\n<div");

WriteLiteral(" class=\"kt-header__topbar-wrapper\"");

WriteLiteral(" data-toggle=\"dropdown\"");

WriteLiteral(" data-offset=\"30px,0px\"");

WriteLiteral(" aria-expanded=\"true\"");

WriteLiteral(">\r\n    <span");

WriteLiteral(" class=\"kt-header__topbar-icon\"");

WriteLiteral(">\r\n        <svg");

WriteLiteral(" xmlns=\"http://www.w3.org/2000/svg\"");

WriteLiteral(" xmlns:xlink=\"http://www.w3.org/1999/xlink\"");

WriteLiteral(" width=\"24px\"");

WriteLiteral(" height=\"24px\"");

WriteLiteral(" viewBox=\"0 0 24 24\"");

WriteLiteral(" version=\"1.1\"");

WriteLiteral(" class=\"kt-svg-icon\"");

WriteLiteral(">\r\n            <g");

WriteLiteral(" stroke=\"none\"");

WriteLiteral(" stroke-width=\"1\"");

WriteLiteral(" fill=\"none\"");

WriteLiteral(" fill-rule=\"evenodd\"");

WriteLiteral(">\r\n                <rect");

WriteLiteral(" id=\"bound\"");

WriteLiteral(" x=\"0\"");

WriteLiteral(" y=\"0\"");

WriteLiteral(" width=\"24\"");

WriteLiteral(" height=\"24\"");

WriteLiteral("></rect>\r\n                <rect");

WriteLiteral(" id=\"Rectangle-62-Copy\"");

WriteLiteral(" fill=\"#000000\"");

WriteLiteral(" opacity=\"0.3\"");

WriteLiteral(" x=\"13\"");

WriteLiteral(" y=\"4\"");

WriteLiteral(" width=\"3\"");

WriteLiteral(" height=\"16\"");

WriteLiteral(" rx=\"1.5\"");

WriteLiteral("></rect>\r\n                <rect");

WriteLiteral(" id=\"Rectangle-62-Copy-2\"");

WriteLiteral(" fill=\"#000000\"");

WriteLiteral(" x=\"8\"");

WriteLiteral(" y=\"9\"");

WriteLiteral(" width=\"3\"");

WriteLiteral(" height=\"11\"");

WriteLiteral(" rx=\"1.5\"");

WriteLiteral("></rect>\r\n                <rect");

WriteLiteral(" id=\"Rectangle-62-Copy-4\"");

WriteLiteral(" fill=\"#000000\"");

WriteLiteral(" x=\"18\"");

WriteLiteral(" y=\"11\"");

WriteLiteral(" width=\"3\"");

WriteLiteral(" height=\"9\"");

WriteLiteral(" rx=\"1.5\"");

WriteLiteral("></rect>\r\n                <rect");

WriteLiteral(" id=\"Rectangle-62-Copy-3\"");

WriteLiteral(" fill=\"#000000\"");

WriteLiteral(" x=\"3\"");

WriteLiteral(" y=\"13\"");

WriteLiteral(" width=\"3\"");

WriteLiteral(" height=\"7\"");

WriteLiteral(" rx=\"1.5\"");

WriteLiteral("></rect>\r\n            </g>\r\n        </svg>\r\n    </span>\r\n</div>\r\n<div");

WriteLiteral(" class=\"dropdown-menu dropdown-menu-fit dropdown-menu-right dropdown-menu-anim dr" +
"opdown-menu-top-unround dropdown-menu-xl\"");

WriteLiteral(">\r\n    <form>\r\n        <!--begin: Head -->\r\n        <div");

WriteLiteral(" class=\"kt-head kt-head--skin-dark\"");

WriteLiteral(" style=\"background-image: url(../../../../assets/media/bg/bg-1.jpg)\"");

WriteLiteral(">\r\n            <h3");

WriteLiteral(" class=\"kt-head__title\"");

WriteLiteral(">\r\n                快捷操作\r\n            </h3>\r\n        </div>\r\n        <!--end: Head" +
" -->\r\n        <!--begin: Grid Nav -->\r\n        <div");

WriteLiteral(" class=\"kt-grid-nav kt-grid-nav--skin-light\"");

WriteLiteral(">\r\n            <div");

WriteLiteral(" class=\"kt-grid-nav__row\"");

WriteLiteral(">\r\n                <a");

WriteAttribute("href", Tuple.Create(" href=\"", 1632), Tuple.Create("\"", 1749)
, Tuple.Create(Tuple.Create("", 1639), Tuple.Create("http://cb.yuewusheng.com/Login/Index?name=", 1639), true)
            
            #line 30 "..\..\Views\Shared\_Nav_TopMenu_Quick.cshtml"
, Tuple.Create(Tuple.Create("", 1681), Tuple.Create<System.Object, System.Int32>(user.Name
            
            #line default
            #line hidden
, 1681), false)
, Tuple.Create(Tuple.Create("", 1691), Tuple.Create("&pwd=", 1691), true)
            
            #line 30 "..\..\Views\Shared\_Nav_TopMenu_Quick.cshtml"
  , Tuple.Create(Tuple.Create("", 1696), Tuple.Create<System.Object, System.Int32>(user.Password
            
            #line default
            #line hidden
, 1696), false)
, Tuple.Create(Tuple.Create("", 1710), Tuple.Create("&dn=", 1710), true)
            
            #line 30 "..\..\Views\Shared\_Nav_TopMenu_Quick.cshtml"
                    , Tuple.Create(Tuple.Create("", 1714), Tuple.Create<System.Object, System.Int32>(user.DisplayName
            
            #line default
            #line hidden
, 1714), false)
, Tuple.Create(Tuple.Create("", 1731), Tuple.Create("&role=", 1731), true)
            
            #line 30 "..\..\Views\Shared\_Nav_TopMenu_Quick.cshtml"
                                           , Tuple.Create(Tuple.Create("", 1737), Tuple.Create<System.Object, System.Int32>(user.RoleID
            
            #line default
            #line hidden
, 1737), false)
);

WriteLiteral(" class=\"kt-grid-nav__item\"");

WriteLiteral(" target=\"_blank\"");

WriteLiteral(">\r\n                    <span");

WriteLiteral(" class=\"kt-grid-nav__icon\"");

WriteLiteral(">\r\n                        <svg");

WriteLiteral(" xmlns=\"http://www.w3.org/2000/svg\"");

WriteLiteral(" xmlns:xlink=\"http://www.w3.org/1999/xlink\"");

WriteLiteral(" width=\"24px\"");

WriteLiteral(" height=\"24px\"");

WriteLiteral(" viewBox=\"0 0 24 24\"");

WriteLiteral(" version=\"1.1\"");

WriteLiteral(" class=\"kt-svg-icon kt-svg-icon--success kt-svg-icon--lg\"");

WriteLiteral(">\r\n                            <g");

WriteLiteral(" stroke=\"none\"");

WriteLiteral(" stroke-width=\"1\"");

WriteLiteral(" fill=\"none\"");

WriteLiteral(" fill-rule=\"evenodd\"");

WriteLiteral(">\r\n                                <rect");

WriteLiteral(" id=\"bound\"");

WriteLiteral(" x=\"0\"");

WriteLiteral(" y=\"0\"");

WriteLiteral(" width=\"24\"");

WriteLiteral(" height=\"24\"");

WriteLiteral("></rect>\r\n                                <path");

WriteLiteral(@" d=""M4.3618034,10.2763932 L4.8618034,9.2763932 C4.94649941,9.10700119 5.11963097,9 5.30901699,9 L15.190983,9 C15.4671254,9 15.690983,9.22385763 15.690983,9.5 C15.690983,9.57762255 15.6729105,9.65417908 15.6381966,9.7236068 L15.1381966,10.7236068 C15.0535006,10.8929988 14.880369,11 14.690983,11 L4.80901699,11 C4.53287462,11 4.30901699,10.7761424 4.30901699,10.5 C4.30901699,10.4223775 4.32708954,10.3458209 4.3618034,10.2763932 Z M14.6381966,13.7236068 L14.1381966,14.7236068 C14.0535006,14.8929988 13.880369,15 13.690983,15 L4.80901699,15 C4.53287462,15 4.30901699,14.7761424 4.30901699,14.5 C4.30901699,14.4223775 4.32708954,14.3458209 4.3618034,14.2763932 L4.8618034,13.2763932 C4.94649941,13.1070012 5.11963097,13 5.30901699,13 L14.190983,13 C14.4671254,13 14.690983,13.2238576 14.690983,13.5 C14.690983,13.5776225 14.6729105,13.6541791 14.6381966,13.7236068 Z""");

WriteLiteral(" id=\"Combined-Shape\"");

WriteLiteral(" fill=\"#000000\"");

WriteLiteral(" opacity=\"0.3\"");

WriteLiteral("></path>\r\n                                <path");

WriteLiteral(" d=\"M17.369,7.618 C16.976998,7.08599734 16.4660031,6.69750122 15.836,6.4525 C15.2" +
"059968,6.20749878 14.590003,6.085 13.988,6.085 C13.2179962,6.085 12.5180032,6.22" +
"49986 11.888,6.505 C11.2579969,6.7850014 10.7155023,7.16999755 10.2605,7.66 C9.8" +
"0549773,8.15000245 9.45550123,8.72399671 9.2105,9.382 C8.96549878,10.0400033 8.8" +
"43,10.7539961 8.843,11.524 C8.843,12.3360041 8.96199881,13.0779966 9.2,13.75 C9." +
"43800119,14.4220034 9.7774978,14.9994976 10.2185,15.4825 C10.6595022,15.9655024 " +
"11.1879969,16.3399987 11.804,16.606 C12.4200031,16.8720013 13.1129962,17.005 13." +
"883,17.005 C14.681004,17.005 15.3879969,16.8475016 16.004,16.5325 C16.6200031,16" +
".2174984 17.1169981,15.8010026 17.495,15.283 L19.616,16.774 C18.9579967,17.60000" +
"41 18.1530048,18.2404977 17.201,18.6955 C16.2489952,19.1505023 15.1360064,19.378" +
" 13.862,19.378 C12.6999942,19.378 11.6325049,19.1855019 10.6595,18.8005 C9.68649" +
"514,18.4154981 8.8500035,17.8765035 8.15,17.1835 C7.4499965,16.4904965 6.9040019" +
"6,15.6645048 6.512,14.7055 C6.11999804,13.7464952 5.924,12.6860058 5.924,11.524 " +
"C5.924,10.333994 6.13049794,9.25950479 6.5435,8.3005 C6.95650207,7.34149521 7.52" +
"34964,6.52600336 8.2445,5.854 C8.96550361,5.18199664 9.8159951,4.66400182 10.796" +
",4.3 C11.7760049,3.93599818 12.8399943,3.754 13.988,3.754 C14.4640024,3.754 14.9" +
"609974,3.79949954 15.479,3.8905 C15.9970026,3.98150045 16.4939976,4.12149906 16." +
"97,4.3105 C17.4460024,4.49950095 17.8939979,4.7339986 18.314,5.014 C18.7340021,5" +
".2940014 19.0909985,5.62999804 19.385,6.022 L17.369,7.618 Z\"");

WriteLiteral(" id=\"C\"");

WriteLiteral(" fill=\"#000000\"");

WriteLiteral("></path>\r\n                            </g>\r\n                        </svg>\r\n     " +
"               </span>\r\n                    <span");

WriteLiteral(" class=\"kt-grid-nav__title\"");

WriteLiteral(">成本系统</span>\r\n                </a>\r\n                <a");

WriteLiteral(" href=\"http://www.yuewusheng.com\"");

WriteLiteral(" class=\"kt-grid-nav__item\"");

WriteLiteral(" target=\"_blank\"");

WriteLiteral(">\r\n                    <span");

WriteLiteral(" class=\"kt-grid-nav__icon\"");

WriteLiteral(">\r\n                        <svg");

WriteLiteral(" xmlns=\"http://www.w3.org/2000/svg\"");

WriteLiteral(" xmlns:xlink=\"http://www.w3.org/1999/xlink\"");

WriteLiteral(" width=\"24px\"");

WriteLiteral(" height=\"24px\"");

WriteLiteral(" viewBox=\"0 0 24 24\"");

WriteLiteral(" version=\"1.1\"");

WriteLiteral(" class=\"kt-svg-icon kt-svg-icon--success kt-svg-icon--lg\"");

WriteLiteral(">\r\n                            <g");

WriteLiteral(" stroke=\"none\"");

WriteLiteral(" stroke-width=\"1\"");

WriteLiteral(" fill=\"none\"");

WriteLiteral(" fill-rule=\"evenodd\"");

WriteLiteral(">\r\n                                <rect");

WriteLiteral(" id=\"bound\"");

WriteLiteral(" x=\"0\"");

WriteLiteral(" y=\"0\"");

WriteLiteral(" width=\"24\"");

WriteLiteral(" height=\"24\"");

WriteLiteral("></rect>\r\n                                <path");

WriteLiteral(@" d=""M4,9.67471899 L10.880262,13.6470401 C10.9543486,13.689814 11.0320333,13.7207107 11.1111111,13.740321 L11.1111111,21.4444444 L4.49070127,17.526473 C4.18655139,17.3464765 4,17.0193034 4,16.6658832 L4,9.67471899 Z M20,9.56911707 L20,16.6658832 C20,17.0193034 19.8134486,17.3464765 19.5092987,17.526473 L12.8888889,21.4444444 L12.8888889,13.6728275 C12.9050191,13.6647696 12.9210067,13.6561758 12.9368301,13.6470401 L20,9.56911707 Z""");

WriteLiteral(" id=\"Combined-Shape\"");

WriteLiteral(" fill=\"#000000\"");

WriteLiteral("></path>\r\n                                <path");

WriteLiteral(@" d=""M4.21611835,7.74669402 C4.30015839,7.64056877 4.40623188,7.55087574 4.5299008,7.48500698 L11.5299008,3.75665466 C11.8237589,3.60013944 12.1762411,3.60013944 12.4700992,3.75665466 L19.4700992,7.48500698 C19.5654307,7.53578262 19.6503066,7.60071528 19.7226939,7.67641889 L12.0479413,12.1074394 C11.9974761,12.1365754 11.9509488,12.1699127 11.9085461,12.2067543 C11.8661433,12.1699127 11.819616,12.1365754 11.7691509,12.1074394 L4.21611835,7.74669402 Z""");

WriteLiteral(" id=\"Path\"");

WriteLiteral(" fill=\"#000000\"");

WriteLiteral(" opacity=\"0.3\"");

WriteLiteral("></path>\r\n                            </g>\r\n                        </svg>\r\n     " +
"               </span>\r\n                    <span");

WriteLiteral(" class=\"kt-grid-nav__title\"");

WriteLiteral(">月无声官网</span>\r\n                </a>\r\n            </div>\r\n        </div>\r\n        " +
"<!--end: Grid Nav -->\r\n    </form>\r\n</div>\r\n");

        }
    }
}
#pragma warning restore 1591
