#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Optimization;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using MUI.WebSite;
    using NewLife;
    
    #line 1 "..\..\Views\Shared\_Nav_TopMenu_User.cshtml"
    using NewLife.Common;
    
    #line default
    #line hidden
    using NewLife.Cube;
    using NewLife.Reflection;
    using NewLife.Web;
    using XCode;
    
    #line 2 "..\..\Views\Shared\_Nav_TopMenu_User.cshtml"
    using XCode.Membership;
    
    #line default
    #line hidden
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Shared/_Nav_TopMenu_User.cshtml")]
    public partial class _Views_Shared__Nav_TopMenu_User_cshtml : System.Web.Mvc.WebViewPage<dynamic>
    {
        public _Views_Shared__Nav_TopMenu_User_cshtml()
        {
        }
        public override void Execute()
        {
            
            #line 3 "..\..\Views\Shared\_Nav_TopMenu_User.cshtml"
  
    var user = ManageProvider.User as IUser ?? User.Identity as IUser;
    var uid = 0;
    var roleName = "";
    var userName = "";
    if (user != null)
    {
        uid = user.ID;
        roleName = user.Roles == null ? " " : user.Roles.Join() + " ";
        userName = user.Name + " ( " + user.DisplayName + " ) ";
    }

    var home = NewLife.Cube.Setting.Current.StartPage;

            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n<!--用户菜单-->\r\n<div");

WriteLiteral(" class=\"kt-header__topbar-wrapper\"");

WriteLiteral(" data-toggle=\"dropdown\"");

WriteLiteral(" data-offset=\"0px,0px\"");

WriteLiteral(" aria-expanded=\"false\"");

WriteLiteral(">\r\n    <div");

WriteLiteral(" class=\"kt-header__topbar-user\"");

WriteLiteral(">\r\n        <span");

WriteLiteral(" class=\"kt-header__topbar-welcome kt-hidden-mobile\"");

WriteLiteral(">你好,</span>\r\n        <span");

WriteLiteral(" class=\"kt-header__topbar-username kt-hidden-mobile\"");

WriteLiteral(">");

            
            #line 22 "..\..\Views\Shared\_Nav_TopMenu_User.cshtml"
                                                             Write(user.Name);

            
            #line default
            #line hidden
WriteLiteral("</span>\r\n        <span");

WriteLiteral(" class=\"kt-badge kt-badge--username kt-badge--unified-success kt-badge--lg kt-bad" +
"ge--rounded kt-badge--bold\"");

WriteLiteral(">");

            
            #line 23 "..\..\Views\Shared\_Nav_TopMenu_User.cshtml"
                                                                                                                     Write(user.Name.Substring(0, 1).ToUpper());

            
            #line default
            #line hidden
WriteLiteral("</span>\r\n    </div>\r\n</div>\r\n\r\n<div");

WriteLiteral(" class=\"dropdown-menu dropdown-menu-fit dropdown-menu-right dropdown-menu-anim dr" +
"opdown-menu-top-unround dropdown-menu-xl\"");

WriteLiteral(" x-placement=\"bottom-end\"");

WriteLiteral(" style=\"position: absolute; will-change: transform; top: 0px; left: 0px; transfor" +
"m: translate3d(1650px, 64px, 0px);\"");

WriteLiteral(">\r\n    <div");

WriteLiteral(" class=\"kt-user-card kt-user-card--skin-dark kt-notification-item-padding-x\"");

WriteLiteral(" style=\"background-image: url(../../../../assets/media/bg/bg-1.jpg)\"");

WriteLiteral(">\r\n        <div");

WriteLiteral(" class=\"kt-user-card__avatar\"");

WriteLiteral(">\r\n            <span");

WriteLiteral(" class=\"kt-badge kt-badge--lg kt-badge--rounded kt-badge--bold kt-font-success\"");

WriteLiteral(">");

            
            #line 30 "..\..\Views\Shared\_Nav_TopMenu_User.cshtml"
                                                                                            Write(user.Name.Substring(0, 1).ToUpper());

            
            #line default
            #line hidden
WriteLiteral("</span>\r\n        </div>\r\n        <div");

WriteLiteral(" class=\"kt-user-card__name\"");

WriteLiteral(">\r\n");

WriteLiteral("            ");

            
            #line 33 "..\..\Views\Shared\_Nav_TopMenu_User.cshtml"
       Write(userName);

            
            #line default
            #line hidden
WriteLiteral("\r\n        </div>\r\n    </div>\r\n    <!--导航 -->\r\n    <div");

WriteLiteral(" class=\"kt-notification\"");

WriteLiteral(">\r\n        <a");

WriteAttribute("href", Tuple.Create(" href=\"", 1749), Tuple.Create("\"", 1758)
, Tuple.Create(Tuple.Create("", 1756), Tuple.Create<System.Object, System.Int32>(Href("~/")
, 1756), false)
);

WriteLiteral(" class=\"kt-notification__item\"");

WriteLiteral(">\r\n            <div");

WriteLiteral(" class=\"kt-notification__item-icon\"");

WriteLiteral(">\r\n                <i");

WriteLiteral(" class=\"fa fa-home kt-font-primary\"");

WriteLiteral("></i>\r\n            </div>\r\n            <div");

WriteLiteral(" class=\"kt-notification__item-details\"");

WriteLiteral(">\r\n                <div");

WriteLiteral(" class=\"kt-notification__item-title kt-font-bold\"");

WriteLiteral(">\r\n                    网站首页\r\n                </div>\r\n            </div>\r\n        " +
"</a>\r\n        <a");

WriteAttribute("href", Tuple.Create(" href=\"", 2149), Tuple.Create("\"", 2178)
, Tuple.Create(Tuple.Create("", 2156), Tuple.Create<System.Object, System.Int32>(Href("~/Admin/User/Info/")
, 2156), false)
            
            #line 48 "..\..\Views\Shared\_Nav_TopMenu_User.cshtml"
, Tuple.Create(Tuple.Create("", 2174), Tuple.Create<System.Object, System.Int32>(uid
            
            #line default
            #line hidden
, 2174), false)
);

WriteLiteral(" class=\"kt-notification__item\"");

WriteLiteral(" target=\"main\"");

WriteLiteral(">\r\n            <div");

WriteLiteral(" class=\"kt-notification__item-icon\"");

WriteLiteral(">\r\n                <i");

WriteLiteral(" class=\"fa fa-user-cog kt-font-success\"");

WriteLiteral("></i>\r\n            </div>\r\n            <div");

WriteLiteral(" class=\"kt-notification__item-details\"");

WriteLiteral(">\r\n                <div");

WriteLiteral(" class=\"kt-notification__item-title kt-font-bold\"");

WriteLiteral(">\r\n                    帐户信息\r\n                </div>\r\n            </div>\r\n        " +
"</a>\r\n        <div");

WriteLiteral(" class=\"kt-notification__custom\"");

WriteLiteral(">\r\n            <a");

WriteAttribute("href", Tuple.Create(" href=\"", 2638), Tuple.Create("\"", 2664)
, Tuple.Create(Tuple.Create("", 2645), Tuple.Create<System.Object, System.Int32>(Href("~/Admin/User/Logout")
, 2645), false)
);

WriteLiteral(" target=\"_parent\"");

WriteLiteral(" class=\"btn btn-google btn-sm\"");

WriteLiteral(">注 销</a>\r\n        </div>\r\n    </div>\r\n    <!--end: Navigation -->\r\n</div>");

        }
    }
}
#pragma warning restore 1591
