#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Optimization;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using MUI.WebSite;
    using NewLife;
    using NewLife.Cube;
    using NewLife.Reflection;
    using NewLife.Web;
    using XCode;
    using XCode.Membership;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Shared/_Object_Nav.cshtml")]
    public partial class _Views_Shared__Object_Nav_cshtml : System.Web.Mvc.WebViewPage<dynamic>
    {
        public _Views_Shared__Object_Nav_cshtml()
        {
        }
        public override void Execute()
        {
WriteLiteral("\r\n");

            
            #line 2 "..\..\Views\Shared\_Object_Nav.cshtml"
  
    var Obj = Model as Object;

            
            #line default
            #line hidden
WriteLiteral("\r\n<!-- 新的设置菜单-->\r\n<div");

WriteLiteral(" class=\"text-center col-md-12 cube-flex-con cube-flex-items\"");

WriteLiteral(">\r\n    <ul");

WriteLiteral(" class=\"kt-nav col-12\"");

WriteLiteral(">\r\n");

            
            #line 8 "..\..\Views\Shared\_Object_Nav.cshtml"
        
            
            #line default
            #line hidden
            
            #line 8 "..\..\Views\Shared\_Object_Nav.cshtml"
         foreach (var link in MUI.WebSite.ConfigSettingService.Current.Links)
        {

            
            #line default
            #line hidden
WriteLiteral("            <li");

WriteLiteral(" class=\"kt-nav__item\"");

WriteLiteral(" style=\"text-align:left;\"");

WriteLiteral(">\r\n                <a");

WriteAttribute("href", Tuple.Create(" href=\"", 328), Tuple.Create("\"", 359)
            
            #line 11 "..\..\Views\Shared\_Object_Nav.cshtml"
, Tuple.Create(Tuple.Create("", 335), Tuple.Create<System.Object, System.Int32>(Url.Content(link.Value)
            
            #line default
            #line hidden
, 335), false)
);

WriteLiteral(" class=\"kt-nav__link\"");

WriteLiteral(">\r\n                    <span");

WriteLiteral(" class=\"kt-nav__link-bullet kt-nav__link-bullet--line\"");

WriteLiteral(">\r\n                        <span></span>\r\n                    </span>\r\n          " +
"          <span");

WriteLiteral(" class=\"kt-nav__link-text\"");

WriteLiteral(">");

            
            #line 15 "..\..\Views\Shared\_Object_Nav.cshtml"
                                               Write(link.Key);

            
            #line default
            #line hidden
WriteLiteral("</span>\r\n                </a>\r\n            </li>\r\n");

            
            #line 18 "..\..\Views\Shared\_Object_Nav.cshtml"
        }

            
            #line default
            #line hidden
WriteLiteral("    </ul>\r\n</div>\r\n");

        }
    }
}
#pragma warning restore 1591
