#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Optimization;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using MUI.WebSite;
    using NewLife;
    
    #line 2 "..\..\Views\Shared\Form.cshtml"
    using NewLife.Cube;
    
    #line default
    #line hidden
    using NewLife.Reflection;
    using NewLife.Web;
    
    #line 1 "..\..\Views\Shared\Form.cshtml"
    using XCode;
    
    #line default
    #line hidden
    using XCode.Membership;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Shared/Form.cshtml")]
    public partial class _Views_Shared_Form_cshtml : System.Web.Mvc.WebViewPage<dynamic>
    {
        public _Views_Shared_Form_cshtml()
        {
        }
        public override void Execute()
        {
            
            #line 3 "..\..\Views\Shared\Form.cshtml"
  
    Layout = NewLife.Cube.Setting.Current.Layout;
    var entity = Model as IEntity;
    var isNew = entity.IsNullKey;
    var rv = entity.GetRouteKey();

            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n<div");

WriteLiteral(" id=\"main_portlet\"");

WriteLiteral(">\r\n");

            
            #line 11 "..\..\Views\Shared\Form.cshtml"
    
            
            #line default
            #line hidden
            
            #line 11 "..\..\Views\Shared\Form.cshtml"
     using (Html.BeginForm((isNew ? "Add" : "Edit"), null, rv))
    {

            
            #line default
            #line hidden
WriteLiteral("        <div");

WriteLiteral(" class=\"form-horizontal kt-portlet kt-portlet--last kt-portlet--responsive-mobile" +
"\"");

WriteLiteral(">\r\n");

WriteLiteral("            ");

            
            #line 14 "..\..\Views\Shared\Form.cshtml"
       Write(Html.Partial("_Form_Action", entity));

            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n");

WriteLiteral("            ");

            
            #line 16 "..\..\Views\Shared\Form.cshtml"
       Write(Html.Partial("_Form_TaskView", entity));

            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n");

WriteLiteral("            ");

            
            #line 18 "..\..\Views\Shared\Form.cshtml"
       Write(Html.Partial("_Form_Header", entity));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("            ");

            
            #line 19 "..\..\Views\Shared\Form.cshtml"
       Write(Html.AntiForgeryToken());

            
            #line default
            #line hidden
WriteLiteral("\r\n            ");

WriteLiteral("\r\n            ");

WriteLiteral("\r\n\r\n");

            
            #line 23 "..\..\Views\Shared\Form.cshtml"
            
            
            #line default
            #line hidden
            
            #line 23 "..\..\Views\Shared\Form.cshtml"
             foreach (var item in ViewData.ModelState.Values)
            {
                foreach (var error in item.Errors)
                {

            
            #line default
            #line hidden
WriteLiteral("                    <ul>\r\n                        <li>");

            
            #line 28 "..\..\Views\Shared\Form.cshtml"
                       Write(error.Exception);

            
            #line default
            #line hidden
WriteLiteral("</li>\r\n                    </ul>\r\n");

            
            #line 30 "..\..\Views\Shared\Form.cshtml"
                }
            }

            
            #line default
            #line hidden
WriteLiteral("            ");

            
            #line 32 "..\..\Views\Shared\Form.cshtml"
       Write(Html.Partial("_Form_Body", entity));

            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n");

WriteLiteral("            ");

            
            #line 34 "..\..\Views\Shared\Form.cshtml"
       Write(Html.Partial("_Form_Action_Footer", entity));

            
            #line default
            #line hidden
WriteLiteral("\r\n        </div>\r\n");

            
            #line 36 "..\..\Views\Shared\Form.cshtml"
    }

            
            #line default
            #line hidden
WriteLiteral("</div>\r\n\r\n\r\n");

        }
    }
}
#pragma warning restore 1591
