#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    
    #line 2 "..\..\Areas\Admin\Views\Index\ProcessModules.cshtml"
    using System.Collections;
    
    #line default
    #line hidden
    using System.Collections.Generic;
    
    #line 1 "..\..\Areas\Admin\Views\Index\ProcessModules.cshtml"
    using System.Diagnostics;
    
    #line default
    #line hidden
    using System.IO;
    using System.Linq;
    using System.Net;
    
    #line 3 "..\..\Areas\Admin\Views\Index\ProcessModules.cshtml"
    using System.Reflection;
    
    #line default
    #line hidden
    
    #line 4 "..\..\Areas\Admin\Views\Index\ProcessModules.cshtml"
    using System.Runtime.Versioning;
    
    #line default
    #line hidden
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using NewLife;
    
    #line 5 "..\..\Areas\Admin\Views\Index\ProcessModules.cshtml"
    using NewLife.Common;
    
    #line default
    #line hidden
    using NewLife.Cube;
    using NewLife.Reflection;
    using NewLife.Web;
    using XCode;
    using XCode.Membership;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Areas/Admin/Views/Index/ProcessModules.cshtml")]
    public partial class _Areas_Admin_Views_Index_ProcessModules_cshtml : System.Web.Mvc.WebViewPage<dynamic>
    {
        public _Areas_Admin_Views_Index_ProcessModules_cshtml()
        {
        }
        public override void Execute()
        {
            
            #line 6 "..\..\Areas\Admin\Views\Index\ProcessModules.cshtml"
  
    Layout = NewLife.Cube.Setting.Current.Layout;

    ViewBag.Title = "进程模块";
    var Act = ViewBag.Act;

    var asm = Assembly.GetExecutingAssembly();
    var att = asm.GetCustomAttribute<TargetFrameworkAttribute>();
    var ver = att.FrameworkDisplayName ?? att.FrameworkName;

    var isAll = String.Equals("All", Request["Mode"], StringComparison.OrdinalIgnoreCase);

    var process = Process.GetCurrentProcess();
    var list = new List<ProcessModule>();
    foreach (ProcessModule item in process.Modules)
    {
        if (isAll || item.FileVersionInfo.CompanyName != "Microsoft Corporation") { list.Add(item); }
    }

            
            #line default
            #line hidden
WriteLiteral("          \r\n\r\n<div");

WriteLiteral(" class=\"kt-portlet kt-portlet--last kt-portlet--mobile\"");

WriteLiteral(">\r\n    <div");

WriteLiteral(" class=\"kt-portlet__head\"");

WriteLiteral(">\r\n        <div");

WriteLiteral(" class=\"kt-portlet__head-label\"");

WriteLiteral(">\r\n                <span");

WriteLiteral(" class=\"kt-portlet__head-icon\"");

WriteLiteral(">\r\n                    <i");

WriteLiteral(" class=\"la la-gear\"");

WriteLiteral("></i>\r\n                </span>\r\n                <h3");

WriteLiteral(" class=\"kt-portlet__head-title\"");

WriteLiteral(">\r\n                    进程模块(");

            
            #line 33 "..\..\Areas\Admin\Views\Index\ProcessModules.cshtml"
                    Write(process.ProcessName);

            
            #line default
            #line hidden
WriteLiteral(" , PID=");

            
            #line 33 "..\..\Areas\Admin\Views\Index\ProcessModules.cshtml"
                                               Write(process.Id);

            
            #line default
            #line hidden
WriteLiteral(" )\r\n");

            
            #line 34 "..\..\Areas\Admin\Views\Index\ProcessModules.cshtml"
                    
            
            #line default
            #line hidden
            
            #line 34 "..\..\Areas\Admin\Views\Index\ProcessModules.cshtml"
                     if (!isAll)
                    {

            
            #line default
            #line hidden
WriteLiteral("                        ");

WriteLiteral("（<a");

WriteLiteral(" href=\"?Mode=All\"");

WriteLiteral(">完整</a>，仅用户）：");

WriteLiteral("\r\n");

            
            #line 37 "..\..\Areas\Admin\Views\Index\ProcessModules.cshtml"
                    }
                    else
                    {

            
            #line default
            #line hidden
WriteLiteral("                        ");

WriteLiteral("（完整，<a");

WriteLiteral(" href=\"?Mode=OnlyUser\"");

WriteLiteral(">仅用户</a>）：");

WriteLiteral("\r\n");

            
            #line 41 "..\..\Areas\Admin\Views\Index\ProcessModules.cshtml"
                    }

            
            #line default
            #line hidden
WriteLiteral("                </h3>\r\n        </div>\r\n    </div>\r\n    <div");

WriteLiteral(" class=\"kt-portlet__body\"");

WriteLiteral(">\r\n        <table");

WriteLiteral(" class=\"table table-bordered table-hover table-striped table-condensed\"");

WriteLiteral(">\r\n            <tr>\r\n                <th>模块名称</th>\r\n                <th>公司名称</th>" +
"\r\n                <th>产品名称</th>\r\n                <th>描述</th>\r\n                <t" +
"h>版本</th>\r\n                <th>大小</th>\r\n                <th>路径</th>\r\n           " +
" </tr>\r\n");

            
            #line 56 "..\..\Areas\Admin\Views\Index\ProcessModules.cshtml"
            
            
            #line default
            #line hidden
            
            #line 56 "..\..\Areas\Admin\Views\Index\ProcessModules.cshtml"
             foreach (ProcessModule item in list)
            {

            
            #line default
            #line hidden
WriteLiteral("                <tr>\r\n                    <td>");

            
            #line 59 "..\..\Areas\Admin\Views\Index\ProcessModules.cshtml"
                   Write(item.ModuleName);

            
            #line default
            #line hidden
WriteLiteral("</td>\r\n                    <td>");

            
            #line 60 "..\..\Areas\Admin\Views\Index\ProcessModules.cshtml"
                   Write(item.FileVersionInfo.CompanyName);

            
            #line default
            #line hidden
WriteLiteral("</td>\r\n                    <td>");

            
            #line 61 "..\..\Areas\Admin\Views\Index\ProcessModules.cshtml"
                   Write(item.FileVersionInfo.ProductName);

            
            #line default
            #line hidden
WriteLiteral("</td>\r\n                    <td>");

            
            #line 62 "..\..\Areas\Admin\Views\Index\ProcessModules.cshtml"
                   Write(item.FileVersionInfo.FileDescription);

            
            #line default
            #line hidden
WriteLiteral("</td>\r\n                    <td>");

            
            #line 63 "..\..\Areas\Admin\Views\Index\ProcessModules.cshtml"
                   Write(item.FileVersionInfo.FileVersion);

            
            #line default
            #line hidden
WriteLiteral("</td>\r\n                    <td>");

            
            #line 64 "..\..\Areas\Admin\Views\Index\ProcessModules.cshtml"
                   Write(item.ModuleMemorySize);

            
            #line default
            #line hidden
WriteLiteral("</td>\r\n                    <td>");

            
            #line 65 "..\..\Areas\Admin\Views\Index\ProcessModules.cshtml"
                   Write(item.FileName);

            
            #line default
            #line hidden
WriteLiteral("</td>\r\n                </tr>\r\n");

            
            #line 67 "..\..\Areas\Admin\Views\Index\ProcessModules.cshtml"
            }

            
            #line default
            #line hidden
WriteLiteral("        </table>\r\n    </div>\r\n</div>\r\n");

        }
    }
}
#pragma warning restore 1591
