#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    
    #line 2 "..\..\Areas\Admin\Views\Index\Session.cshtml"
    using System.Collections;
    
    #line default
    #line hidden
    using System.Collections.Generic;
    
    #line 1 "..\..\Areas\Admin\Views\Index\Session.cshtml"
    using System.Diagnostics;
    
    #line default
    #line hidden
    using System.IO;
    using System.Linq;
    using System.Net;
    
    #line 3 "..\..\Areas\Admin\Views\Index\Session.cshtml"
    using System.Reflection;
    
    #line default
    #line hidden
    
    #line 4 "..\..\Areas\Admin\Views\Index\Session.cshtml"
    using System.Runtime.Versioning;
    
    #line default
    #line hidden
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using NewLife;
    
    #line 5 "..\..\Areas\Admin\Views\Index\Session.cshtml"
    using NewLife.Common;
    
    #line default
    #line hidden
    using NewLife.Cube;
    using NewLife.Reflection;
    using NewLife.Web;
    using XCode;
    using XCode.Membership;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Areas/Admin/Views/Index/Session.cshtml")]
    public partial class _Areas_Admin_Views_Index_Session_cshtml : System.Web.Mvc.WebViewPage<dynamic>
    {
        public _Areas_Admin_Views_Index_Session_cshtml()
        {
        }
        public override void Execute()
        {
            
            #line 6 "..\..\Areas\Admin\Views\Index\Session.cshtml"
  
    Layout = NewLife.Cube.Setting.Current.Layout;

    ViewBag.Title = "Session列表";
    var Act = ViewBag.Act;

    var asm = Assembly.GetExecutingAssembly();
    var att = asm.GetCustomAttribute<TargetFrameworkAttribute>();
    var ver = att.FrameworkDisplayName ?? att.FrameworkName;

            
            #line default
            #line hidden
WriteLiteral("       \r\n\r\n<div");

WriteLiteral(" class=\"kt-portlet kt-portlet--last kt-portlet--mobile\"");

WriteLiteral(">\r\n    <div");

WriteLiteral(" class=\"kt-portlet__head\"");

WriteLiteral(">\r\n        <div");

WriteLiteral(" class=\"kt-portlet__head-label\"");

WriteLiteral(">\r\n                <span");

WriteLiteral(" class=\"kt-portlet__head-icon\"");

WriteLiteral(">\r\n                    <i");

WriteLiteral(" class=\"la la-gear\"");

WriteLiteral("></i>\r\n                </span>\r\n                <h3");

WriteLiteral(" class=\"kt-portlet__head-title\"");

WriteLiteral(">\r\n                    Session列表(");

            
            #line 24 "..\..\Areas\Admin\Views\Index\Session.cshtml"
                         Write(Session.Contents.Count);

            
            #line default
            #line hidden
WriteLiteral(" )\r\n                </h3>\r\n        </div>\r\n    </div>\r\n    <div");

WriteLiteral(" class=\"kt-portlet__body\"");

WriteLiteral(">    \r\n        <table");

WriteLiteral(" class=\"table table-bordered table-hover table-striped table-condensed\"");

WriteLiteral(">\r\n            <tr>\r\n                <th>名称</th>\r\n                <th>类型</th>\r\n  " +
"              <th>数值</th>\r\n            </tr>\r\n");

            
            #line 35 "..\..\Areas\Admin\Views\Index\Session.cshtml"
            
            
            #line default
            #line hidden
            
            #line 35 "..\..\Areas\Admin\Views\Index\Session.cshtml"
             foreach (String item in Session.Keys)
            {

            
            #line default
            #line hidden
WriteLiteral("                <tr>\r\n                    <td>");

            
            #line 38 "..\..\Areas\Admin\Views\Index\Session.cshtml"
                   Write(item);

            
            #line default
            #line hidden
WriteLiteral("</td>\r\n                    <td>");

            
            #line 39 "..\..\Areas\Admin\Views\Index\Session.cshtml"
                   Write(Session[item].GetType().FullName);

            
            #line default
            #line hidden
WriteLiteral("</td>\r\n                    <td>");

            
            #line 40 "..\..\Areas\Admin\Views\Index\Session.cshtml"
                   Write(Session[item]);

            
            #line default
            #line hidden
WriteLiteral("</td>\r\n                </tr>\r\n");

            
            #line 42 "..\..\Areas\Admin\Views\Index\Session.cshtml"
            }

            
            #line default
            #line hidden
WriteLiteral("        </table>\r\n    </div>\r\n</div>\r\n\r\n");

        }
    }
}
#pragma warning restore 1591
